Repository harness/developer-hub, pull requests merged in 2023-11, with the labels that each got.

#3992 [DOC-3717] Update smp and pl tutorial landing pages
  src/components/LandingPage/Platform.tsx
  src/components/LandingPage/SMP.tsx
Labels: DO NOT MERGE

#3955 CDS 813xx release notes.
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/continuous-delivery.md
  release-notes/whats-new.md
Labels: release notes

#4010 Adding new tutorial under /tutorials/cd-pipelines/kubernetes/
  src/components/Tutorials/ContinuousDeliveryK8SData.ts
  tutorials/cd-pipelines/kubernetes/cosign-opa.md
  tutorials/cd-pipelines/static/k8s-cosign-opa-tutorial/cosign_verify_success.png
  tutorials/cd-pipelines/static/k8s-cosign-opa-tutorial/developer-flow-with-cosign-opa.png
  tutorials/cd-pipelines/static/k8s-cosign-opa-tutorial/updated-deploy-guestbook-stage.png
Labels: tutorial

#4038 [DOC-3853]: Update ECR Trigger docs for support of registryId): first d…
  docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
  docs/platform/triggers/trigger-on-a-new-artifact.md
Labels: documentation, draft, tech review, DO NOT MERGE, pm review

#4041 Docs 2815 smriti
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-rate-limit.md
Labels: documentation

#4043 FAQ of the week
  kb/platform/harness-platform-faqs.md
Labels: DO NOT MERGE

#4057 Docs review for CHAOS-2892
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-loss.md
Labels: documentation

#4056 Changed the delegate version in the release note for CDS-81032.
  release-notes/continuous-delivery.md
Labels: release notes

#4039 Docs review 2873
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-corruption.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-duplication.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-loss.md
Labels: documentation

#4063 CDS-74778 (Documentation for CDS-71229 - support ECR as OCI helm rep…
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-services.md
  docs/continuous-delivery/deploy-srv-diff-platforms/native-helm-quickstart.md
Labels: Waiting for Release, ready to merge

#4100 CDS-80824 (Issue with JEXL Scripting).
  docs/platform/variables-and-expressions/expression-v2.md
Labels: tech review, DO NOT MERGE

#4089 CDS-80260 (Documentation for CDS-70967 - EKS Connector: Optional Regi…
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
Labels: documentation, enhancement, draft, tech review, DO NOT MERGE, pm review

#4114 feat: [CDS-83189]: Missing documentation about timeout setting and ho…
  docs/platform/pipelines/w_pipeline-steps-reference/timeout-settings.md
Labels: DO NOT MERGE, PR test

#4120 [SMP-2283] SMP 0.10.1 release notes
  release-notes/self-managed-enterprise-edition.md
Labels: tech review, DO NOT MERGE

#3989 Code docs initial setup
  docs/code-repository.md
  docs/code-repository/_category_.json
  docs/code-repository/code-supported.md
  docs/code-repository/config-repos/_category_.json
  docs/code-repository/config-repos/create-repo.md
  docs/code-repository/config-repos/delete-repo.md
  docs/code-repository/config-repos/import-repo.md
  docs/code-repository/config-repos/rules.md
  docs/code-repository/config-repos/webhooks.md
  docs/code-repository/get-started/_category_.json
  docs/code-repository/get-started/key-concepts.md
  docs/code-repository/get-started/onboarding-guide.md
  docs/code-repository/get-started/overview.md
  docs/code-repository/pipelines/_category_.json
  docs/code-repository/pipelines/code-triggers.md
  docs/code-repository/pipelines/codebase-from-harness-code.md
  docs/code-repository/pull-requests/_category_.json
  docs/code-repository/pull-requests/create-pr.md
  docs/code-repository/pull-requests/merge-pr.md
  docs/code-repository/pull-requests/review-pr.md
  docs/code-repository/work-in-repos/_category_.json
  docs/code-repository/work-in-repos/branch.md
  docs/code-repository/work-in-repos/clone-repos.md
  docs/code-repository/work-in-repos/commit.md
  docs/code-repository/work-in-repos/static/inspect-commit.png
  docs/code-repository/work-in-repos/tag.md
  docs/continuous-integration/_category_.json
  docs/get-started/harness-platform-architecture.md
  docs/get-started/supported-platforms-and-technologies.md
  docs/platform/automation/api/api-permissions-reference.md
  docs/platform/role-based-access-control/add-manage-roles.md
  docs/platform/role-based-access-control/permissions-reference.md
  docs/software-supply-chain-assurance/get-started/key-concepts.md
  docusaurus.config.js
  release-notes/early-access.md
  sidebars.js
  src/components/Docs/CodeRepository.tsx
  src/components/Docs/data/codeRepositoryData.tsx
  src/components/LandingPage/TutorialCard.module.scss
  src/components/LandingPage/styles.module.scss
  src/components/LearnAboutPlatform/data/moduleListData.tsx
  src/components/NavbarItems/CoveoSearch.scss
  src/constants.ts
  src/css/custom.css
  static/img/code.png
  static/img/icon_code.svg
  static/img/icon_code_s.svg
Labels: work in progress, DO NOT MERGE

#4159 Cds 814xx relnotes
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/continuous-delivery.md
Labels: release notes, DO NOT MERGE

#4093 814xx release notes
  release-notes/continuous-integration.md
  release-notes/sto-pulldown-filters-sto-5212.png
Labels: DO NOT MERGE

#4113 Release notes 1.24.x [WIP]
  release-notes/chaos-engineering.md
Labels: work in progress, release notes, Waiting for Release

#3980 Delegate hotfix version 81015 for CDS-82385, ZD-52612
  release-notes/delegate.md
Labels: DO NOT MERGE

#4082 CHAOS-2912 docs review
  docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cf-app-route-unmap.md
  docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cf-app-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/cloud-foundry/cloud-foundry.md
Labels: documentation

#4220 [CDS-84418] Documentation for CDS-80057: Allow for Per Metric Fail on…
  docs/continuous-delivery/verify/verify-deployments-with-the-verify-step.md
Labels: documentation, enhancement, draft, tech review, DO NOT MERGE, pm review

#4183 [PL-42561] Platform 81502 release notes
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#4221 Update release notes to match the new format
  release-notes/chaos-engineering.md
Labels: release notes, peer review, pm review

#4239 [CDS-81969] Add ServiceNow app release in whats new section of the docs.
  release-notes/continuous-delivery.md
Labels: enhancement, draft, release notes, tech review, DO NOT MERGE, pm review

#4238 [CDS-77309] CD doc :: CDS-77006 :: Allow check box to update multiple…
  docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-service-now-tickets-in-cd-stages.md
Labels: documentation, enhancement, draft, tech review, DO NOT MERGE, pm review

#4234 [CDS-74740] Documentation for CDS-72495 - Enhancement-Abbot - Service…
  docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-service-now-tickets-in-cd-stages.md
Labels: documentation, enhancement, draft, tech review, DO NOT MERGE, pm review

#4205 DOC 1965 ChaosGuard
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/_category_.json
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/chaosguard-concepts.md
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/configuring-chaosguard.md
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/introduction-to-chaosguard.md
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/chaosguard-concepts/add-conditions.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/chaosguard-concepts/chaos-studio-condition.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/chaosguard-concepts/chaosguard-access-control.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/chaosguard-concepts/flow-chart-chaosguard.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/add-params-rule.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/chaosguard-page.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/chaosguard-rules.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/click-next.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/edit-condition.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/new-condition-chaosguard.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/new-condition.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/new-rule-select.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/new-rule.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/rule-evaluation-fail.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/rule-evaluation-pass.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/rule-saved.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/save-condition.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/select-condition.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/configure-chaosguard/select-multiple-user-groups.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/introduction-to-chaosguard/fine-grain-control.png
  docs/chaos-engineering/configure-chaos-experiments/chaosguard/static/introduction-to-chaosguard/new-user-entry.png
Labels: documentation, DO NOT MERGE, pm review

#4285 Adding Pipeline/Stage Timeouts
  docs/platform/pipelines/w_pipeline-steps-reference/pipeline-settings.md
Labels: tech review, DO NOT MERGE

#4291 CHAOS-3118 Group faults based on ec2, serverless and both
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-and-serverless-faults.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-agent-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-http-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-http-modify-body.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-http-reset-peer.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-http-status-code.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-io-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-memory-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-network-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-volume-detach.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-fargate-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-fargate-memory-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-instance-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-invalid-container-image.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-network-restrict.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-task-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-update-container-resource-limit.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-update-container-timeout.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-update-task-role.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/manifests/ecs-task-stop/task-stop-svc.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/manifests/ecs-task-stop/task-stop-task-affected.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/manifests/ecs-task-stop/task-stop-task.yaml
Labels: enhancement, DO NOT MERGE, peer review, pm review

#4313 [CDS-83649] Docs improvement for CDS-83415 (Selector logic for helm d…
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/add-a-custom-remote-script-and-manifests.md
Labels: bug, tech review, DO NOT MERGE

#4279 [CDS-85246] CDS 816xx release notes.
  release-notes/continuous-delivery.md
Labels: draft, release notes, tech review, DO NOT MERGE

#4348 [CDS-85211] Documentation: Skip Verification for CV
  docs/continuous-delivery/verify/configure-cv/abort-verification.md
  docs/platform/pipelines/abort-pipeline.md
Labels: documentation, enhancement, question, draft, tech review, DO NOT MERGE, pm review

#4334 Edits to merged PR #4306
  docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
Labels: edit, pm review

#4251 [PL-42975] Platform NG 81612 FG 81609 Delegate 23.11.81601 release notes
  docs/first-gen/firstgen-release-notes/fg-delegate.md
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/delegate.md
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#4050 [DOC-3857] Delegate scale down
  docs/platform/delegates/manage-delegates/auto-scale-using-replicas.md
Labels: tech review, DO NOT MERGE
