Repository harness/developer-hub, pull requests merged in 2023-02, with the labels that each got.

#566 Add delegate metrics
  docs/platform/2_Delegates/manage-delegates/delegate-metrics.md
Labels: documentation

#573 Update delegate-metrics.md
  docs/platform/2_Delegates/manage-delegates/delegate-metrics.md
Labels: documentation

#571 update azure images
  docs/chaos-engineering/chaos-faults/azure/static/images/azure-disk-loss.png
  docs/chaos-engineering/chaos-faults/azure/static/images/azure-instance-cpu-hog.png
  docs/chaos-engineering/chaos-faults/azure/static/images/azure-instance-io-stress.png
  docs/chaos-engineering/chaos-faults/azure/static/images/azure-instance-memory-hog.png
  docs/chaos-engineering/chaos-faults/azure/static/images/azure-instance-stop.png
  docs/chaos-engineering/chaos-faults/azure/static/images/azure-web-app-access-restrict.png
  docs/chaos-engineering/chaos-faults/azure/static/images/azure-web-app-stop.png
Labels: documentation

#530 DEL NextGen relnotes for 02/01/23
  release-notes/delegate.md
Labels: release notes

#533 Update fg-delegate.md
  docs/first-gen/firstgen-release-notes/fg-delegate.md
Labels: release notes

#560 Update release notes 0.7
  release-notes/chaos-engineering.md
Labels: documentation

#577 Create install-delegates-with-custom-certs.md
  docs/platform/2_Delegates/secure-delegates/install-delegates-with-custom-certs.md
Labels: documentation

#556 New topic for dashboard overview
  docs/platform/18_Dashboards/dashboards-overview.md
  docs/platform/18_Dashboards/static/dashboard-view-options.png
  docs/platform/18_Dashboards/static/dashboards-overview.png
  docs/platform/18_Dashboards/static/filter-dashboard-data.png
Labels: draft

#609 Add updated images for VMware
  docs/chaos-engineering/chaos-faults/vmware/static/images/vm-poweroff.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-cpu-hog.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-disk-loss.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-dns-chaos.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-host-reboot.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-http-latency.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-http-modify-response.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-http-reset-peer.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-io-stress.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-memory-hog.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-network-chaos.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-network-latency.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-network-loss.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-process-kill.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-service-stop.png
  docs/chaos-engineering/chaos-faults/vmware/static/images/vmware-vm-poweroff.png
  docs/chaos-engineering/chaos-faults/vmware/vmware-network-latency.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-network-loss.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-vm-poweroff.md
Labels: documentation

#619 Updated images for Kubernetes node-level faults
  docs/chaos-engineering/chaos-faults/kubernetes/node/docker-service-kill.md
  docs/chaos-engineering/chaos-faults/kubernetes/node/kubelet-service-kill.md
  docs/chaos-engineering/chaos-faults/kubernetes/node/static/images/docker-service-kill.png
  docs/chaos-engineering/chaos-faults/kubernetes/node/static/images/kubelet-service-kill.png
  docs/chaos-engineering/chaos-faults/kubernetes/node/static/images/node-drain.png
  docs/chaos-engineering/chaos-faults/kubernetes/node/static/images/node-restart.png
  docs/chaos-engineering/chaos-faults/kubernetes/node/static/images/node-stress.png
  docs/chaos-engineering/chaos-faults/kubernetes/node/static/images/node-taint.png
  docs/chaos-engineering/chaos-faults/kubernetes/node/static/images/svc-kill.png
Labels: documentation

#620 Updated Kubernetes pod-level fault images
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-cpu-hog-exec.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-cpu-hog.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-latency.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-modify-body.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-modify-header.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-reset-peer.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-status-code.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-io-stress.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-memory-hog-exec.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-memory-hog.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-corruption.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-duplication.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-latency.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-loss.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-partition.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/container-kill.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/disk-fill.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/dns-chaos.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/network-chaos.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-autoscaler.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-cpu-hog-exec.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-cpu-hog.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-delete.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-dns-spoof.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-http-latency.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-http-modify-body.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-http-modify-header.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-http-reset-peer.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-http-status-code.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-http.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-io-stress.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-memory-hog-exec.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-memory-hog.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-network-corruption.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-network-duplication.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-network-latency.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-network-loss.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-network-partition.png
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/images/pod-stress.png
Labels: documentation

#584 CCM AutoStopping Proxy
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-azure.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-gcp.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-terraform.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-autostopping-rules-aws.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-alb-port-config.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-autostopping-proxy-https.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-load-balancer-healthcheck.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-proxy-healthcheck.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-proxy-port-config.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-set-up-tcp.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/azure-autostopping-proxy-rule-creation.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/create-auto-stopping-rules-for-azure-51.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/create-autoproxy-aws-lb.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/create-autoproxy-gcp-lb.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/create-azure-autoproxy-lb.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/create-custom-load-balancer-for-gcp.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/create-load-balancer-aws.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/static/aws-autoproxy-lb.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/static/aws-autoproxy-secrets-manager.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/static/azure-autoproxy-creation.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/static/gcp-autoproxy-lb-creation.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/static/gcp-secret-version.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/static/secret-creation-aws.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/static/secret-name-convention-aws.png
  docs/frequently-asked-questions/harness-faqs/cloud-cost-management-faqs.md
Labels: edit

#622 update release notes
  release-notes/chaos-engineering.md
Labels: release notes

#626 Doc - 2571 Update Error Tracking collector url
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/install-the-error-tracking-agent.md
Labels: bug, documentation, edit

#624 DOC-2495 (Docs: Enforcement Limits): documented the new centralized p…
  docs/platform/17_Settings/pipeline-settings/pipeline-settings.md
Labels: draft, work in progress

#628 Removed feature flag notification
  docs/service-reliability-management/howtos-service-reliability-management/composite-slo-quickstart.md
Labels: documentation

#639 Corrected a dead link
  docs/first-gen/continuous-delivery/continuous-verification/continuous-verification-overview/concepts-cv/cv-providers.md
Labels: bug, documentation, edit

#640 Fixed typo in header
  docs/platform/6_Security/2-add-use-text-secrets.md
Labels: bug

#642 Add a note
  release-notes/chaos-engineering.md
Labels: release notes

#540 restructure pod delete
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-delete.md
Labels: documentation

#646 Fix link
  docs/chaos-engineering/chaos-faults/kube-resilience/kube-resilience.md
Labels: documentation

#602 Update self-managed-enterprise-edition.md
  release-notes/self-managed-enterprise-edition.md
Labels: work in progress, release notes

#607 Add smp-cg-relnotes-020623
  docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
Labels: work in progress, release notes

#658 Update harness-git-experience-quickstart.md
  docs/platform/10_Git-Experience/harness-git-experience-quickstart.md
Labels: documentation

#668 broken link fix
  docs/platform/6_Security/2-add-use-text-secrets.md
Labels: bug

#681 Fixed error
  docs/chaos-engineering/chaos-faults/kubernetes/node/docker-service-kill.md
  docs/chaos-engineering/chaos-faults/kubernetes/node/kubelet-service-kill.md
  docs/chaos-engineering/chaos-faults/kubernetes/node/node-drain.md
  docs/chaos-engineering/chaos-faults/kubernetes/node/node-restart.md
  docs/chaos-engineering/chaos-faults/kubernetes/node/node-taint.md
Labels: documentation

#680 Restructure GCP and Kube-resilience faults
  docs/chaos-engineering/chaos-faults/gcp/gcp-vm-disk-loss-by-label.md
  docs/chaos-engineering/chaos-faults/gcp/gcp-vm-disk-loss.md
  docs/chaos-engineering/chaos-faults/gcp/gcp-vm-instance-stop-by-label.md
  docs/chaos-engineering/chaos-faults/gcp/gcp-vm-instance-stop.md
  docs/chaos-engineering/chaos-faults/gcp/static/manifests/gcp-vm-instance-stop-by-label/managed-instance-group.yaml
  docs/chaos-engineering/chaos-faults/kube-resilience/kubelet-density.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-delete.md
Labels: documentation

#667 CDS-51349-HTTP Step supports API KEY in the auth header
  docs/continuous-delivery/cd-technical-reference/cd-gen-ref-category/http-step.md
Labels: DO NOT MERGE, peer review

#683 VMware restructure
  docs/chaos-engineering/chaos-faults/vmware/static/manifests/http-modify-response/status-code.yaml
  docs/chaos-engineering/chaos-faults/vmware/static/manifests/vmware-memory-hog/vm-memory-hog-memconsumptionperc.yaml
  docs/chaos-engineering/chaos-faults/vmware/static/manifests/vmware-service-stop/vmware-service-stop-self-healing.yaml
  docs/chaos-engineering/chaos-faults/vmware/vmware-cpu-hog.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-disk-loss.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-dns-chaos.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-host-reboot.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-http-latency.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-http-modify-response.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-http-reset-peer.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-io-stress.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-memory-hog.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-network-latency.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-network-loss.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-process-kill.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-service-stop.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-vm-poweroff.md
Labels: documentation

#720 SRM Release Notes for build number: 78421
  release-notes/service-reliability-management.md
Labels: release notes

#694 add-ng-delegate-relnotes-784xx
  release-notes/delegate.md
  release-notes/whats-new.md
Labels: release notes

#717 Error tracking quickstart
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/error-tracking-in-srm.md
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-agent-connection-status.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-arc-code-tab.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-arc-log-tab.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-arc-screen.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-environment-tab.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-errortracking-dashboard.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-generate-new-token.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-moniterdservice-created.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-moniterdservice-navigate.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-new-token-created.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-open-arc.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-overview-diagram.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-token-navigate.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-view-event-list.png
Labels: edit

#677 784xx Release Notes - CI
  release-notes/continuous-integration.md
  release-notes/static/ci-codebase-config-exp-values.png
  release-notes/whats-new.md
Labels: release notes

#718 [DOC-2545] Restructure Azure faults
  docs/chaos-engineering/chaos-faults/azure/azure-disk-loss.md
  docs/chaos-engineering/chaos-faults/azure/azure-instance-cpu-hog.md
  docs/chaos-engineering/chaos-faults/azure/azure-instance-io-stress.md
  docs/chaos-engineering/chaos-faults/azure/azure-instance-memory-hog.md
  docs/chaos-engineering/chaos-faults/azure/azure-instance-stop.md
  docs/chaos-engineering/chaos-faults/azure/azure-web-app-access-restrict.md
  docs/chaos-engineering/chaos-faults/azure/azure-web-app-stop.md
  docs/chaos-engineering/chaos-faults/azure/azure.md
  docs/chaos-engineering/chaos-faults/azure/experiments.ts
Labels: documentation

#655 [CI-5455] [DOC-2581] - Windows support on Hosted
  docs/continuous-integration/ci-quickstarts/hosted-builds-on-virtual-machines-quickstart.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
Labels: DO NOT MERGE

#708 Fix import syntax
  tutorials/build-code/ci-tutorial-push-to-gar.md
Labels: peer review

#679 [CI-5758] [CI-6410] [DOC-2351] - Connector settings, Connector authentication, Connectors in CI steps
  docs/continuous-integration/ci-technical-reference/build-and-push-to-docker-hub-step-settings.md
  docs/continuous-integration/ci-technical-reference/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/ci-technical-reference/build-and-push-to-gcr-step-settings.md
  docs/continuous-integration/ci-technical-reference/restore-cache-from-gcs-settings.md
  docs/continuous-integration/ci-technical-reference/restore-cache-from-s-3-step-settings.md
  docs/continuous-integration/ci-technical-reference/save-cache-to-gcs-step-settings.md
  docs/continuous-integration/ci-technical-reference/save-cache-to-s-3-step-settings.md
  docs/continuous-integration/ci-technical-reference/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/ci-technical-reference/upload-artifacts-to-jfrog-artifactory-step-settings.md
  docs/continuous-integration/ci-technical-reference/upload-artifacts-to-s-3-step-settings.md
  docs/platform/7_Connectors/add-aws-connector.md
  docs/platform/7_Connectors/connect-to-google-cloud-platform-gcp.md
  docs/platform/7_Connectors/ref-cloud-providers/aws-connector-settings-reference.md
  docs/platform/7_Connectors/ref-cloud-providers/gcs-connector-settings-reference.md
Labels: peer review

#674 [CI-4735] [CI-4604] - Add shortCommitSha variable
  docs/continuous-integration/ci-technical-reference/built-in-cie-codebase-variables-reference.md
Labels: peer review

#661 [DOC-2534] [CI-5580] - Service Dependency deprecation
  docs/continuous-integration/ci-quickstarts/ci-concepts.md
  docs/continuous-integration/ci-quickstarts/ci-pipeline-basics.md
  docs/continuous-integration/ci-technical-reference/background-step-settings.md
  docs/continuous-integration/ci-technical-reference/configure-service-dependency-step-settings.md
  docs/continuous-integration/ci-technical-reference/run-step-settings.md
  docs/continuous-integration/ci-technical-reference/static/background-step-settings-call-id-in-other-step.png
  docs/continuous-integration/ci-technical-reference/static/icon-thumbtack.png
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/frequently-asked-questions/harness-faqs/continuous-integration-ci-faqs.md
Labels: escalated issue, peer review

#725 Fixed various errors
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/error-tracking-in-srm.md
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-arc-copystack.png
  docs/service-reliability-management/use-service-reliability-management/error-tracking-category/static/et-quickstart-verify-agent-navigate.png
Labels: edit

#701 Topic for Harness UI
  docs/getting-started/harness-ui-overview.md
  docs/getting-started/static/configure-leftnav.png
  docs/getting-started/static/drag-drop-modules.png
  docs/getting-started/static/module-info.png
  docs/getting-started/static/new-nav-left.png
  docs/getting-started/static/select-modules-leftnav.png
  docs/getting-started/static/select-modules-list.png
Labels: draft

#631 [CI-5155] [CI-5131] - revise set up test intelligence
  docs/continuous-integration/ci-technical-reference/configure-run-tests-step-settings.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
  docs/continuous-integration/use-ci/view-your-builds/viewing-tests.md
Labels: peer review

#749 Changed the setting name
  docs/platform/9_Approvals/adding-harness-approval-stages.md
Labels: enhancement

#745 DOCS-2514-Concatenate-pipeline-variables
  docs/platform/12_Variables-and-Expressions/harness-variables.md
Labels: DO NOT MERGE, peer review

#739 Update delegate-metrics.md
  docs/platform/2_Delegates/manage-delegates/delegate-metrics.md
Labels: edit

#770 Update category
  docs/chaos-engineering/overview/_category_.json
Labels: documentation

#755 CDS-53091-remove FF NEXUS3_RAW_REPOSITORY reference from docs
  docs/first-gen/firstgen-platform/techref-category/cd-ref/artifacts-ref/nexus-artifact-sources.md
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
Labels: tech review, DO NOT MERGE

#773 CDS-48463-Approval-Rejection-Description-Update
  docs/platform/8_Pipelines/w_pipeline-steps-reference/step-failure-strategy-settings.md
Labels: peer review

#757 CDS-52964-HTTP-step-capability-check
  docs/continuous-delivery/cd-technical-reference/cd-gen-ref-category/http-step.md
Labels: DO NOT MERGE, peer review

#799 Added note for remote pipeline chaining
  docs/platform/8_Pipelines/pipeline-chaining.md
Labels: question

#572 Chore(Exp-docs): Add Locust Loadgen Chaos Experiment Docs
  docs/chaos-engineering/chaos-faults/categories.tsx
  docs/chaos-engineering/chaos-faults/chaos-faults.md
  docs/chaos-engineering/chaos-faults/load/_category_.json
  docs/chaos-engineering/chaos-faults/load/experiments.ts
  docs/chaos-engineering/chaos-faults/load/load.md
  docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
  docs/chaos-engineering/chaos-faults/load/static/images/locust-loadgen-chaos.png
  docs/chaos-engineering/chaos-faults/load/static/manifests/locust-loadgen-chaos/host.yaml
  docs/chaos-engineering/chaos-faults/load/static/manifests/locust-loadgen-chaos/load-image.yaml
  docs/chaos-engineering/chaos-faults/load/static/manifests/locust-loadgen-chaos/spawn-rate.yaml
  docs/chaos-engineering/chaos-faults/load/static/manifests/locust-loadgen-chaos/users.yaml
  docs/chaos-engineering/chaos-faults/static/manifest/common/chaos-duration.yaml
  src/components/ChaosEngineering/utils/helper.ts
  src/components/ChaosEngineering/utils/types.ts
  static/img/chaos/load.svg
Labels: documentation

#797 Fixed formatting issues.
  docs/platform/13_Templates/create-a-secret-manager-template.md
  docs/platform/6_Security/9-custom-secret-manager.md
Labels: bug

#811 srm release notes 78507
  release-notes/service-reliability-management.md
Labels: release notes

#777 CHAOS-1219: Replaces default container runtime to containerd for faults
  docs/chaos-engineering/chaos-faults/kubernetes/pod/container-kill.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-cpu-hog.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-dns-error.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-dns-spoof.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-latency.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-modify-body.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-modify-header.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-reset-peer.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-http-status-code.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-io-stress.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-memory-hog.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-corruption.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-duplication.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-latency.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/pod-network-loss.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/container-kill/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-cpu-hog/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-dns-error/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-dns-spoof/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-http-latency/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-http-modify-body/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-http-modify-header/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-http-reset-peer/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-http-status-code/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-io-stress/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-network-corruption/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-network-duplication/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-network-latency/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/chaos-faults/kubernetes/pod/static/manifests/pod-network-loss/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/overview/Security/security-templates/psp.md
  docs/chaos-engineering/static/overview/manifest/kyverno-policies/allow-host-paths-for-litmus-experiments-which-uses-hostPaths.yaml
  docs/chaos-engineering/static/overview/manifest/psp/psp-litmus.yaml
Labels: documentation

#818 update locust-loadgen.md
  docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
Labels: bug, documentation

#580 [DOC-2554] Added security FAQs
  docs/frequently-asked-questions/harness-faqs/chaos-engineering-faq.md
Labels: documentation

#782 [CI-7046] CI troubleshooting - scm_skip_ssl delegate env var
  docs/continuous-integration/troubleshoot/troubleshooting-ci.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
Labels: peer review

#819 [DOC-2626] AWS fault pre-requisites
  docs/chaos-engineering/chaos-faults/aws/aws.md
Labels: documentation

#810 CDS-53858-add-errors
  docs/platform/8_Pipelines/w_pipeline-steps-reference/step-failure-strategy-settings.md
Labels: DO NOT MERGE, peer review

#778 Release notes 0.8.3
  release-notes/chaos-engineering.md
Labels: draft, release notes

#742 Create delegate-required-sdks
  docs/platform/2_Delegates/advanced-installation/install-a-delegate-with-3-rd-party-tool-custom-binaries.md
  docs/platform/2_Delegates/delegate-reference/delegate-required-sdks.md
Labels: documentation, edit

#840 [DOC-2599] Remove anti-hosted language, correct technical issues
  docs/continuous-integration/troubleshoot/troubleshooting-ci.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
Labels: peer review
