Repository harness/developer-hub, pull requests merged in 2023-01, with the labels that each got.

#329 Update canary-deployment-step.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/canary-deployment-step.md
Labels: documentation

#382 Update delegate release notes
  release-notes/delegate.md
Labels: documentation

#391 Update whats-new.md
  release-notes/whats-new.md
Labels: release notes

#384 chore(chaos): Correct typographical error in architecture docs
  docs/chaos-engineering/technical-reference/architecture.md
Labels: documentation

#400 Create fg-delegate.md
  docs/first-gen/firstgen-release-notes/fg-delegate.md
Labels: release notes

#376 Terraform provider overview
  docs/platform/19_Terraform/harness-terraform-provider-overview.md
Labels: Draft

#366 AWS-ECS-AutoStopping-Tag-Support
  docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-aws.md
  docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-azure.md
  docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-gcp.md
  docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-kubernetes.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/autostopping-dashboard.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-ecs.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-terraform.md
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/AWS-autostopping-select-ecs-service.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-console-add-tags.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-ecs-tags-2.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-ecs-tags.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/static/aws-ecs-use-tags.png
  docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/4-load-balancer/static/autoproxy-details-view.png
Labels: WIP

#411 added details for rate limits
  docs/platform/16_APIs/api-quickstart.md
Labels: Draft

#441 refac: [CHAOS-925]: Structure change for Chaos Sidebar
  docs/chaos-engineering/technical-reference/architecture.md
  docs/chaos-engineering/technical-reference/chaos-dashboard.md
  docs/chaos-engineering/technical-reference/chaos-hubs/_category_.json
  docs/chaos-engineering/technical-reference/chaos-hubs/chaos-hub-overview.md
  docs/chaos-engineering/technical-reference/chaos-hubs/enterprise-hub.md
  docs/chaos-engineering/technical-reference/chaos-infrastructures.md
  docs/chaos-engineering/technical-reference/environements.md
  docs/chaos-engineering/technical-reference/experiments.md
  docs/chaos-engineering/technical-reference/faults.md
  docs/chaos-engineering/technical-reference/overview.md
  docs/chaos-engineering/technical-reference/probes/_category_.json
Labels: documentation

#426 Delegate-reference-yaml
  client-redirects.js
  docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-kubernetes.md
  docs/continuous-delivery/cd-advanced/cd-helm-category/deploy-helm-charts.md
  docs/continuous-delivery/cd-advanced/cd-helm-category/use-a-local-helm-chart.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/add-a-kubernetes-sidecar-container.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/add-and-override-values-yaml-files.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/add-artifacts-for-kubernetes-deployments.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/kubernetes-deployments-overview.md
  docs/continuous-delivery/cd-advanced/kustomize-howtos/use-kustomize-for-kubernetes-deployments.md
  docs/continuous-delivery/cd-services/k8s-services/kubernetes-services.md
  docs/continuous-delivery/onboard-cd/cd-concepts/cd-pipeline-basics.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
  docs/platform/2_Delegates/advanced-installation/install-a-kubernetes-delegate.md
  docs/platform/2_Delegates/advanced-installation/non-root-delegate-installation.md
  docs/platform/2_Delegates/advanced-installation/static/install-a-kubernetes-delegate-12.png
  docs/platform/2_Delegates/advanced-installation/static/install-a-kubernetes-delegate-13.png
  docs/platform/2_Delegates/advanced-installation/static/install-a-kubernetes-delegate-14.png
  docs/platform/2_Delegates/configure-delegates/delegate-auto-update.md
  docs/platform/2_Delegates/configure-delegates/run-scripts-on-delegates.md
  docs/platform/2_Delegates/configure-delegates/support-for-delegate-docker-images.md
  docs/platform/2_Delegates/customize-delegates/build-custom-delegate-images-with-third-party-tools.md
  docs/platform/2_Delegates/customize-delegates/custom-delegate.md
  docs/platform/2_Delegates/customize-delegates/enable-root-user-privileges-to-add-custom-binaries.md
  docs/platform/2_Delegates/customize-delegates/install-delegates-with-third-party-tools.md
  docs/platform/2_Delegates/customize-delegates/static/build-custom-delegate-images-with-third-party-tools-07.png
  docs/platform/2_Delegates/customize-delegates/static/build-custom-delegate-images-with-third-party-tools-08.png
  docs/platform/2_Delegates/customize-delegates/static/build-custom-delegate-images-with-third-party-tools-09.png
  docs/platform/2_Delegates/customize-delegates/static/enable-root-user-privileges-to-add-custom-binaries-10.png
  docs/platform/2_Delegates/customize-delegates/static/enable-root-user-privileges-to-add-custom-binaries-11.png
  docs/platform/2_Delegates/delegate-reference/YAML/example-harness-delegate-yaml.md
  docs/platform/2_Delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
  docs/platform/2_Delegates/delegate-reference/YAML/sample-create-a-permanent-volume-nfs-server.md
  docs/platform/2_Delegates/delegate-reference/YAML/sample-harness-delegate-yaml-with-nfs-volume-mounted.md
  docs/platform/2_Delegates/delegate-reference/YAML/sample-kubernetes-manifest-nfs-volume.md
  docs/platform/2_Delegates/delegate-reference/common-delegate-profile-scripts.md
  docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
  docs/platform/2_Delegates/delegate-reference/example-kubernetes-manifest-harness-delegate.md
  docs/platform/2_Delegates/get-started-with-delegates/delegate-image-types.md
  docs/platform/2_Delegates/get-started-with-delegates/delegate-installation-overview.md
  docs/platform/2_Delegates/get-started-with-delegates/delegate-registration.md
  docs/platform/2_Delegates/get-started-with-delegates/delegates-overview.md
  docs/platform/2_Delegates/install-delegates/docker-delegates/install-a-docker-delegate.md
  docs/platform/2_Delegates/install-delegates/kubernetes-delegates/install-harness-delegate-on-kubernetes.md
  docs/platform/2_Delegates/install-delegates/kubernetes-delegates/install-harness-delegate-using-helm.md
  docs/platform/2_Delegates/secure-delegates/trust-store-override-for-delegates.md
  docs/platform/7_Connectors/add-a-microsoft-azure-connector.md
  docs/platform/7_Connectors/connect-to-a-cloud-provider.md
  docs/platform/7_Connectors/ref-cloud-providers/aws-connector-settings-reference.md
  docs/platform/7_Connectors/ref-cloud-providers/kubernetes-cluster-connector-settings-reference.md
Labels: documentation

#428 chore(chaos): Adds glossary page
  docs/chaos-engineering/chaos-faults/_category_.json
  docs/chaos-engineering/glossary.md
  docs/chaos-engineering/static/glossary/component-relationship.png
  docs/chaos-engineering/static/glossary/experiment-sequence.png
  yarn.lock
Labels: documentation

#469 Update delegate-environment-variables.md
  docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
Labels: documentation, escalated issue

#462 Update delegate-auto-update.md
  docs/platform/2_Delegates/configure-delegates/delegate-auto-update.md
Labels: documentation

#463 Update install-harness-delegate-on-kubernetes.md
  docs/platform/2_Delegates/install-delegates/kubernetes-delegates/install-harness-delegate-on-kubernetes.md
Labels: documentation

#450 New topic for pipeline chaining
  docs/platform/8_Pipelines/add-a-custom-stage.md
  docs/platform/8_Pipelines/add-a-stage.md
  docs/platform/8_Pipelines/define-a-failure-strategy-on-stages-and-steps.md
  docs/platform/8_Pipelines/harness-yaml-quickstart.md
  docs/platform/8_Pipelines/input-sets.md
  docs/platform/8_Pipelines/pipeline-chaining.md
  docs/platform/8_Pipelines/run-a-stage-or-step-multiple-times-using-a-matrix.md
  docs/platform/8_Pipelines/run-pipelines-using-input-sets-and-overlays.md
  docs/platform/8_Pipelines/run-specific-stage-in-pipeline.md
  docs/platform/8_Pipelines/searching-the-console-view.md
  docs/platform/8_Pipelines/static/pipeline-chain-list.png
  docs/platform/8_Pipelines/static/pipeline-chain-option.png
  docs/platform/8_Pipelines/view-and-compare-pipeline-executions.md
Labels: draft

#484 Create deploy-delegate-to-ECS
  docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
Labels: documentation

#511 Update install-delegate.md
  tutorials/platform/install-delegate.md
  tutorials/platform/provision-azure-infrastructure.md
Labels: bug

#517 Supported platforms page update - CCM
  docs/getting-started/supported-platforms-and-technologies.md
Labels: edit

#525 Merge deploy-delegate-to-ECS
  docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
Labels: documentation

#532 Update upgrade-nextgen-cd.md
  docs/continuous-delivery/onboard-cd/upgrading/upgrade-nextgen-cd.md
Labels: documentation

#534 Create docker-delegate-to-ecs-fargate
  docs/platform/2_Delegates/advanced-installation/docker-delegate-to-ecs-fargate
Labels: documentation

#471 secret cache update
  docs/platform/6_Security/1-harness-secret-manager-overview.md
Labels: draft
