Repository harness/developer-hub, pull requests merged in 2023-06, with the labels that each got.

#1950 srm release notes 794
  release-notes/service-reliability-management.md
  release-notes/whats-new.md
Labels: peer review

#1941 RN draft
  docs/platform/10_Git-Experience/manage-a-harness-pipeline-repo-using-git-experience.md
  docs/platform/10_Git-Experience/static/78f49fd6d5d64ecd1b877cf3f76767ae04cce53bffccbb67b20447c64ccca5cf.png
  release-notes/continuous-delivery.md
  release-notes/static/0e40fbf0db025ce3330a7b4e7352a8203acb51d5a06653b1b010a279e2f42cc5.png
  release-notes/static/314bbcf2b284a4756aeacce74e9dd73be4523363a8fdd302a2eb919f350a37ff.png
  release-notes/static/64a3aee31250b15c98b4978994ca1ff14e720b2d739c8feec72fdee12d6220a7.png
  release-notes/static/87cae6dd20947c866629d225293d41ad83be7848061537e28efd2def8e14ea48.png
  release-notes/static/abb924b38a23ab57c26b3703d7c38e096eb60005625a6dfcd42793d503553a6e.png
  release-notes/static/cdb3734c4ce0d74bac785e20e71e148ec9c67ca4b6eba9164fc3e16c76d78e20.png
  release-notes/static/d3ae175d36c932027045989f3c6d5b8b35ff3f50d7dec64195f1e1a264b4f577.png
  release-notes/static/ee0f296b5c9ed5249f409415b8a1dbb6b901ceed5e3b7118ee1ad40a6f93b77d.png
  release-notes/static/fa61423c00604c9a2d1dcf3cd2e8c040d71992791e34abf983eb5befe8640159.png
  release-notes/whats-new.md
Labels: documentation, draft, DO NOT MERGE

#1913 PL release notes for 794xx
  release-notes/platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#1951 fix bugbash findings - cet
  docs/continuous-error-tracking/getting-started/cet-overview.md
  docs/continuous-error-tracking/getting-started/cet-setup.md
Labels: peer review

#1940 [DOC-3197] Update topic title, add intro details
  docs/self-managed-enterprise-edition/back-up-and-recover/use-an-external-database.md
Labels: peer review

#753 CHAOS-1245: Adds missing probe fields and minor fixes
  docs/chaos-engineering/technical-reference/probes/cmd-probe.md
  docs/chaos-engineering/technical-reference/probes/prom-probe.md
Labels: documentation

#1962 [DOC-3206] Update SMP patch release description
  release-notes/self-managed-enterprise-edition.md
Labels: peer review

#1964 [DOC-3207] Delegate release notes page - Add note and links to release notes
  release-notes/delegate.md
Labels: peer review

#1567 Add new module - Internal Developer Portal (Beta)
  docs/internal-developer-portal.md
  docs/internal-developer-portal/_category_.json
  docs/internal-developer-portal/intro.md
  docs/internal-developer-portal/static/catalog-screenshot.png
  docs/internal-developer-portal/static/docs-screenshot.png
  docs/internal-developer-portal/static/pipelines-screenshot.png
  docs/internal-developer-portal/static/plugins-screenshot.png
  docs/internal-developer-portal/static/search-screenshot.png
  docusaurus.config.js
  sidebars.js
  src/components/Docs/InternalDeveloperPortal.tsx
  src/components/Docs/data/internalDeveloperPortal.ts
  static/img/icon_idp.svg
Labels: DO NOT MERGE, docs-team-review-pending

#1780 FFM-7740: updates env/flag input fields - some rewriting for clarity
  docs/feature-flags/ff-build-pipeline/build-feature-flag-pipeline.md
  docs/feature-flags/ff-build-pipeline/static/1-build-feature-flag-pipeline-05.png
  docs/feature-flags/ff-build-pipeline/static/pipeline-add-step.png
  docs/feature-flags/ff-build-pipeline/static/pipeline-flag-config.png
  docs/feature-flags/ff-build-pipeline/static/pipeline-flagchange-actions.png
Labels: Waiting for Release

#1993 [DOC-3083] Add matrix labels by name option
  docs/platform/8_Pipelines/looping-strategies-matrix-repeat-and-parallelism.md
Labels: tech review

#1976 [PL-39215] Update screens in delegate concepts
  docs/platform/2_Delegates/delegate-concepts/delegate-requirements.md
  docs/platform/2_Delegates/delegate-concepts/static/delegate-requirements-and-limitations-00.png
  docs/platform/2_Delegates/delegate-concepts/static/delegates-overview-02.png
  docs/platform/2_Delegates/delegate-concepts/static/delegates-overview-03.png
  docs/platform/2_Delegates/delegate-concepts/static/view-delegate-task-logs.png
Labels: peer review

#1917 [DOC-3153] Add currentStatus strategy node expressions
  docs/platform/12_Variables-and-Expressions/harness-variables.md
  docs/platform/8_Pipelines/run-a-stage-or-step-multiple-times-using-a-matrix.md
Labels: peer review

#2024 SRM RN - added hotfix tab
  release-notes/service-reliability-management.md
Labels: peer review

#1933 Update upgrade-nextgen-cd.md
  docs/continuous-delivery/get-started/upgrading/upgrade-nextgen-cd.md
Labels: documentation, DO NOT MERGE

#2035 FFM-8135: adds nodejs 1.2.17 relnote
  docs/feature-flags/ff-sdks/server-sdks/node-js-sdk-reference.md
  release-notes/feature-flags.md
Labels: tech review

#2048 Cds 56094 bg scale down step
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/static/bg-scale-down-step.png
Labels: documentation, tech review, DO NOT MERGE

#2026 PL release notes for 795xx
  release-notes/platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#2047 CDS-54294-HPA and PDB support for K8s Blue Green and Canary deployments
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/what-can-i-deploy-in-kubernetes.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-canary-deployment.md
Labels: documentation, tech review, DO NOT MERGE

#1992 795xx Release Notes - CI
  release-notes/continuous-integration.md
Labels: DO NOT MERGE

#2006 FFM-8124: adds ff release notes for 795xx
  release-notes/feature-flags.md
Labels: Waiting for Release

#2060 [DOC-1594], [DOC-2556] - Code repo connector docs
  client-redirects.js
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/add-config-files.md
  docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
  docs/continuous-delivery/gitops/add-harness-git-ops-repository-credentials-template.md
  docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
  docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
  docs/continuous-integration/migration-guides/migrating-from-githubactions.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/platform/7_Connectors/Code-Repositories/add-a-git-hub-connector.md
  docs/platform/7_Connectors/Code-Repositories/connect-to-a-azure-repo.md
  docs/platform/7_Connectors/Code-Repositories/connect-to-code-repo.md
  docs/platform/7_Connectors/Code-Repositories/git-hub-app-support.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/bitbucket-connector-settings-reference.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-connector-settings-reference.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-lab-connector-settings-reference.md
  docs/platform/Governance/14_Policy-as-code/add-a-governance-policy-step-to-a-connector.md
  docs/platform/Resource-Development/19_Terraform/advanced-terraform-onboarding.md
  src/components/Certifications/data/ci-certification-admin-review-guide.md
  src/components/Certifications/data/ci-certification-developer-review-guide.md
  tutorials/cd-pipelines/continuous-verification/prometheus.md
  tutorials/ci-pipelines/ci-kubernetes-build-farm.md
  tutorials/ci-pipelines/ci-tutorial-tfc-notification-trigger.md
  tutorials/ci-pipelines/test/ci-allure-report.md
  tutorials/shared/java-backup.md
  tutorials/shared/node-backup.md
Labels: peer review

#2069 [DOC-3242] Update note on Delegate release note page
  release-notes/delegate.md
Labels: peer review

#2076 added video to the service hook section
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/cd-helm-category/deploy-helm-charts.md
Labels: documentation, DO NOT MERGE

#2067 New topic - Request-based SLO
  docs/service-reliability-management/slo/request-based-slo.md
  docs/service-reliability-management/slo/slo-as-code.md
  docs/service-reliability-management/slo/static/create-request-sli.png
  docs/service-reliability-management/slo/static/request-based-sli-configurtion.png
Labels: peer review

#2078 Update triggers-reference.md
  docs/platform/8_Pipelines/w_pipeline-steps-reference/triggers-reference.md
Labels: tech review

#2014 [DOC-2550] - Code coverage and artifact tab plugin
  client-redirects.js
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/code-coverage.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/run-tests-in-ci.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/static/codecoverage_coveralls_env_var_visual.png
  docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/viewing-tests.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
  docs/continuous-integration/use-ci/viewing-builds.md
  src/components/LandingPage/data/allTutorialsData.tsx
  src/components/LandingPage/data/continuousIntegrationData.tsx
  src/components/Tutorials/ContinuousIntegrationPublishData.ts
  src/components/Tutorials/ContinuousIntegrationTestData.ts
  tutorials/ci-pipelines/publish/ci-allure-report.md
  tutorials/ci-pipelines/test/ci-localstack-background-step.md
  tutorials/ci-pipelines/test/ci-saucelabs-background-step.md
  tutorials/shared/java-backup.md
  tutorials/shared/node-backup.md
Labels: peer review

#2053 CET release notes for 5.23.0 and 5.23.1
  release-notes/continuous-error-tracking.md
Labels: peer review

#2086 Added CDS-68030 to CD RN
  release-notes/continuous-delivery.md
  release-notes/whats-new.md
Labels: documentation, DO NOT MERGE

#2087 DOC-3253
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
Labels: documentation, DO NOT MERGE

#2065 [DOC-3201] GitX settings
  docs/platform/10_Git-Experience/git-settings.md
  docs/platform/10_Git-Experience/static/default-connector-gitx.png
Labels: draft

#2098 Cd rn 79518 hotfix
  release-notes/continuous-delivery.md
Labels: documentation

#1982 [DOC-3185] Add in-cluster monitoring instructions to SMP monitoring options
  docs/self-managed-enterprise-edition/monitor-harness-on-prem.md
  docs/self-managed-enterprise-edition/static/monitor-harness-on-prem-2.png
  docs/self-managed-enterprise-edition/static/monitor-harness-on-prem.png
Labels: tech review

#2092 [DOC-3254] Helm 2 deprecation notice partial file
  release-notes/shared/helm-2-deprecation-notice.md
Labels: tech review

#2075 New topic: Add annotations
  docs/service-reliability-management/change-impact-analysis/_category_.json
  docs/service-reliability-management/slo-annoations.md
  docs/service-reliability-management/static/add-annotation.png
  docs/service-reliability-management/static/annotation-details.png
Labels: peer review

#2057 [DOC-3239] Update immutable delegate references
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/cd-helm-category/use-a-local-helm-chart.md
  docs/platform/2_Delegates/manage-delegates/delegate-metrics.md
  docs/platform/2_Delegates/secure-delegates/install-delegates-with-custom-certs.md
  docs/platform/7_Connectors/Cloud-providers/add-a-microsoft-azure-connector.md
  docs/platform/7_Connectors/Cloud-providers/connect-to-google-cloud-platform-gcp.md
  docs/platform/7_Connectors/Cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
Labels: tech review

#2100 [DEL-3257] Update delegate cross reference
  docs/platform/2_Delegates/delegate-concepts/delegate-overview.md
Labels: tech review

#2109 DOC-2593 Remove service dependency from yaml examples
  docs/continuous-delivery/deploy-srv-diff-platforms/community-ed/harness-community-edition-quickstart.md
  docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/add-a-governance-policy-step-to-a-pipeline.md
  docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/harness-governance-quickstart.md
  docs/continuous-integration/migration-guides/migrating-from-circleci.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
  docs/platform/13_Templates/template.md
  docs/platform/Governance/14_Policy-as-code/add-a-governance-policy-step-to-a-pipeline.md
  docs/platform/Governance/14_Policy-as-code/harness-governance-quickstart.md
  docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/ingest-scan-results-into-an-sto-pipeline.md
  tutorials/ci-pipelines/publish/ci-allure-report.md
  tutorials/security-tests/cicd-integrated-pipeline.md
Labels: peer review

#2111 doc-2596
  docs/platform/7_Connectors/Cloud-providers/add-a-kubernetes-cluster-connector.md
  docs/platform/7_Connectors/Cloud-providers/ref-cloud-providers/kubernetes-cluster-connector-settings-reference.md
Labels: peer review

#2115 partial for supported platforms and technologies
  docs/continuous-integration/ci-quickstarts/_category_.json
  docs/continuous-integration/ci-supported-platforms.md
  docs/continuous-integration/migration-guides/_category_.json
  docs/continuous-integration/shared/ci-supported-platforms.md
  docs/continuous-integration/troubleshooting-ci.md
  docs/continuous-integration/use-ci/_category_.json
  docs/getting-started/supported-platforms-and-technologies.md
Labels: peer review

#2128 CI - Remove punctuation from titles and slight topic reorg
  docs/continuous-integration/ci-quickstarts/ci-pipeline-basics.md
  docs/continuous-integration/ci-quickstarts/hosted-builds-on-virtual-machines-quickstart.md
  docs/continuous-integration/ci-supported-platforms.md
  docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
Labels: peer review

#2126 [DOC-3278] Fix cross references
  docs/platform/2_Delegates/install-delegates/overview.md
Labels: peer review

#2037 DOC-2703 - Ruby guide
  src/components/LandingPage/data/continuousIntegrationData.tsx
  src/components/Tutorials/ContinuousIntegrationBuildData.ts
  tutorials/ci-pipelines/build/ci-golang.md
  tutorials/ci-pipelines/build/ci-java-http-server.md
  tutorials/ci-pipelines/build/ci-node-docker-quickstart.md
  tutorials/ci-pipelines/build/ci-python.md
  tutorials/ci-pipelines/build/ci-ruby.md
Labels: peer review

#2120 CV - whats supported topic
  docs/continuous-delivery/verify/configure-cv/_category_.json
  docs/continuous-delivery/verify/cv-concepts/_category_.json
  docs/continuous-delivery/verify/cv-results/_category_.json
  docs/continuous-delivery/verify/cv-whats-supported.md
  docs/continuous-delivery/verify/verify-deployments-with-the-verify-step.md
Labels: tech review

#2079 [DOC-2595] - CI iOS and macOS guide
  src/components/LandingPage/ContinuousIntegration.tsx
  src/components/LandingPage/data/continuousIntegrationData.tsx
  src/components/Tutorials/ContinuousIntegrationBuildData.ts
  tutorials/ci-pipelines/build/ci-ios.md
  tutorials/ci-pipelines/build/ci-python.md
Labels: peer review

#2056 [PL-39145] Update Harness SaaS IP allowlist
  docs/first-gen/firstgen-platform/techref-category/account-ref/delegate-ref/whitelist-harness-domains-and-ips.md
  docs/platform/20_References/allowlist-harness-domains-and-ips.md
Labels: tech review

#2132 [DOC-3280] Add SMP what's supported topic
  docs/getting-started/supported-platforms-and-technologies.md
  docs/self-managed-enterprise-edition/introduction/getting-started-with-self-managed-enterprise-edition.md
  docs/self-managed-enterprise-edition/introduction/harness-self-managed-enterprise-edition-overview.md
  docs/self-managed-enterprise-edition/introduction/supported-features-and-integrations.md
  docs/self-managed-enterprise-edition/shared/smp-supported-platforms.md
  docs/self-managed-enterprise-edition/smp-supported-platforms.md
  release-notes/self-managed-enterprise-edition.md
Labels: tech review

#2145 DOC-1505 DOC-1633 - small CI backlog items
  docs/continuous-integration/ci-supported-platforms.md
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
  docs/platform/8_Pipelines/w_pipeline-steps-reference/triggers-reference.md
Labels: peer review

#2144 [DOC-3285] Add docker build architecture requirement
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md
Labels: tech review

#2135 [WIP] draft of CD RN for June 15-2023 - do not pub
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  docs/platform/10_Git-Experience/git-experience-overview.md
  docs/platform/10_Git-Experience/static/86a197e9afb88cb6816cea527bd7b8cee41d7d3d39f7c5104ebeedc00d6f050f.png
  docs/platform/12_Variables-and-Expressions/add-a-variable.md
  docs/platform/12_Variables-and-Expressions/static/807ab89c31339b661d773c5622579ee361c66fdd2fdc05bf49bb1898532af047.png
  docs/platform/12_Variables-and-Expressions/static/99cd1ed8807b8c424b8bf1f06d6db36f540c599bae65beb5e4da19bd21e4b0e3.png
  release-notes/continuous-delivery.md
  release-notes/early-access.md
  release-notes/static/058d3e80cc8f95965e51010541d0c28f77865e484f8a84beea205b49172c658d.png
  release-notes/static/0bf162c7149b298e69fb52a15588e994357d3b0cf283c9146b6a0f0dac0deccd.png
  release-notes/static/153beccc9216340c35b3e2ca53ad81a35ec15e8b4621cd0402f0adc8372acc45.png
  release-notes/static/47ce888b8bd290e2d68db294eae373c08dc6185f1e66f6aad00b65f136dda1df.png
  release-notes/whats-new.md
Labels: release notes

#2127 CI RN 796xx
  docs/continuous-integration/shared/output-var.md
  docs/continuous-integration/shared/subscription-view-usage.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/debug-mode.md
  docs/continuous-integration/use-ci/optimize-and-more/optimizing-ci-build-times.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/configure-run-tests-step-settings.md
  docs/platform/8_Pipelines/add-a-stage.md
  release-notes/continuous-integration.md
  release-notes/early-access.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#2137 PL-38935-JIT-user-provisioning
  docs/platform/3_User-Management/provision-use-jit.md
  docs/platform/3_User-Management/static/jit-user-provisioning.png
Labels: draft

#2163 CHAOS-1907: adds new free plan topic
  docs/chaos-engineering/get-started/_category_.json
  docs/chaos-engineering/get-started/introduction-to-chaos-module.md
  docs/chaos-engineering/get-started/learn-more-free-plan.md
Labels: peer review

#2193 FFM-8123: adds java sdk known issue
  docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md
Labels: tech review, peer review

#2177 Cds 67121 cds 71172 post prod rollback
  docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/_category_.json
  docs/continuous-delivery/x-platform-cd-features/advanced/rollback-deployments.md
  docs/continuous-delivery/x-platform-cd-features/advanced/static/rollback-deployment-3.png
  docs/continuous-delivery/x-platform-cd-features/advanced/static/rollback-deployments-1.png
  docs/continuous-delivery/x-platform-cd-features/advanced/static/rollback-deployments.png
  docs/continuous-delivery/x-platform-cd-features/advanced/static/rolling-deployments-2.png
Labels: documentation, DO NOT MERGE, peer review

#2039 [DOC-3231] - CI debug assistant
  client-redirects.js
  docs/continuous-integration/shared/aida-intro.md
  docs/continuous-integration/shared/aida-legal.md
  docs/continuous-integration/shared/aida-use.md
  docs/continuous-integration/troubleshoot-ci/_category_.json
  docs/continuous-integration/troubleshoot-ci/aida.md
  docs/continuous-integration/troubleshoot-ci/debug-mode.md
  docs/continuous-integration/troubleshoot-ci/static/aida-dialog-example.png
  docs/continuous-integration/troubleshoot-ci/static/aida-launch-button.png
  docs/continuous-integration/troubleshoot-ci/static/ci-rerun-build-in-debug-mode.png
  docs/continuous-integration/troubleshoot-ci/static/debug-remote-build-links.png
  docs/continuous-integration/troubleshoot-ci/troubleshooting-ci.md
  docs/continuous-integration/use-ci/optimize-and-more/_category_.json
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/viewing-builds.md
  docs/troubleshooting/troubleshooting-nextgen.md
  release-notes/continuous-integration.md
  release-notes/early-access.md
  src/components/Certifications/data/ci-certification-admin-review-guide.md
  src/components/Certifications/data/ci-certification-developer-review-guide.md
  src/components/Docs/data/continuousIntegrationData.ts
Labels: DO NOT MERGE

#2117 [DOC-3263] Overview topic
  docs/platform/Harness-AIDA/_category_.json
  docs/platform/Harness-AIDA/aida-overview.md
Labels: draft

#2187 [PL-37215] Add OpenShift note
  docs/platform/2_Delegates/install-delegates/build-custom-delegate-images-with-third-party-tools.md
Labels: peer review

#2168 [SMP-1418] Add minio.yaml details to SMP self-signed certificates topic
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/how-to-use-self-signed-certificates-with-self-managed.md
Labels: peer review

#2200 replace image with video
  docs/continuous-integration/troubleshoot-ci/aida.md
Labels: peer review

#2202 [DOC-2961] Add required role permission to SMP Helm install
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Labels: peer review

#1832 [DOC-2188] Add PCF details
  docs/platform/2_Delegates/delegate-reference/common-delegate-profile-scripts.md
  docs/platform/2_Delegates/install-delegates/install-a-delegate-with-3-rd-party-tool-custom-binaries.md
Labels: peer review

#1628 [DOC-2751] Manage SMP feature flags
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/manage-feature-flags.md
Labels: peer review

#2214 grab bag small fixes
  docs/continuous-integration/ci-quickstarts/ci-concepts.md
  docs/continuous-integration/migration-guides/migrating-from-circleci.md
  docs/continuous-integration/migration-guides/migrating-from-githubactions.md
  docs/continuous-integration/migration-guides/migrating-from-gitlab.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-a-script-in-a-ci-stage.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
  docs/platform/8_Pipelines/run-a-stage-or-step-multiple-times-using-a-matrix.md
  docs/platform/8_Pipelines/view-and-compare-pipeline-executions.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
  docs/troubleshooting/troubleshooting-nextgen.md
  src/components/Certifications/data/ci-certification-admin-review-guide.md
  src/components/Certifications/data/ci-certification-developer-review-guide.md
Labels: peer review

#2234 Grafana Loki connector
  docs/platform/7_Connectors/Monitoring-and-Logging-Systems/connect-to-monitoring-and-logging-systems.md
Labels: peer review

#2240 SRM - Grafana Loki health source
  docs/service-reliability-management/monitored-service/health-source/loki.md
  docs/service-reliability-management/monitored-service/health-source/new-relic.md
  docs/service-reliability-management/monitored-service/health-source/prometheus.md
  docs/service-reliability-management/monitored-service/health-source/splunk.md
  docs/service-reliability-management/monitored-service/health-source/static/cv-loki-log-query.png
  docs/service-reliability-management/monitored-service/health-source/sumologic.md
Labels: peer review

#2261 [DOC-3322] Add Podman info to delegate install
  docs/platform/2_Delegates/install-delegates/overview.md
Labels: peer review

#2273 [DOC-3332] SMP - Remove download the helm chart section from the Install using Helm topic
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Labels: peer review

#2237 [DOC-3315] Update revoke tokens info
  docs/platform/2_Delegates/secure-delegates/secure-delegates-with-tokens.md
Labels: peer review

#2009 Cds 57016 expression engine
  docs/platform/12_Variables-and-Expressions/add-a-variable.md
  docs/platform/12_Variables-and-Expressions/expression-v2.md
  docs/platform/12_Variables-and-Expressions/extracting-characters-from-harness-variable-expressions.md
  docs/platform/12_Variables-and-Expressions/harness-variables.md
  docs/platform/12_Variables-and-Expressions/static/execution-json.png
Labels: documentation, draft, DO NOT MERGE

#2227 PL release notes for 797xx
  release-notes/platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#2239 FFM-8304: adds 797xx FM relnotes (STAGED)
  release-notes/feature-flags.md
Labels: DO NOT MERGE

#2256 DOC-3317 cd rn 79700
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  docs/first-gen/firstgen-release-notes/shared/cd-79700-fixed-issues.md
  release-notes/continuous-delivery.md
  release-notes/early-access.md
  release-notes/shared/cd-79700-early-access.md
  release-notes/shared/cd-79700-fixed-issues.md
  release-notes/static/payload-input.png
  release-notes/whats-new.md
Labels: documentation, draft, DO NOT MERGE

#2236 CHAOS-1928: adds chaos 0.14.1 release notes
  client-redirects.js
  docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
  docs/chaos-engineering/integrations/static/srm/apply-fault-to-service.png
  docs/chaos-engineering/integrations/static/srm/slo-details-performance.png
  docs/chaos-engineering/integrations/static/srm/srm-changes-dashboard.png
  docs/chaos-engineering/integrations/static/srm/srm-slo-dashboard.png
  docs/chaos-engineering/integrations/static/srm/srm-slo-filters.png
  docs/chaos-engineering/integrations/use-chaos-with-srm.md
  release-notes/chaos-engineering.md
Labels: Waiting for Release

#2279 fix jira ticket number in fixed issues for 79411 CD release notes
  release-notes/continuous-delivery.md
Labels: peer review

#2253 SRM release notes for version 797xx
  release-notes/service-reliability-management.md
Labels: release notes, peer review

#2219 Ci rn 797xx
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/bitbucket-connector-settings-reference.md
  release-notes/continuous-integration.md
Labels: DO NOT MERGE

#2302 Cds 72750 cd aida
  docs/continuous-delivery/static/aida-launch-button.png
  docs/continuous-delivery/static/aida-troubleshooting-k8s-1.png
  docs/continuous-delivery/static/aida-troubleshooting-k8s-2.png
  docs/continuous-delivery/static/aida-troubleshooting-k8s-3.png
  docs/continuous-delivery/static/aida-troubleshooting-k8s-4.png
  docs/continuous-delivery/static/aida-troubleshooting-k8s.png
  docs/continuous-delivery/troubleshoot-cd-with-aida.md
Labels: documentation, DO NOT MERGE

#2217 [DOC-3308] - Output variables with secrets
  docs/continuous-integration/shared/output-var.md
Labels: peer review

#2275 CHAOS-1896: adds draft what's supported section
  docs/chaos-engineering/get-started/introduction-to-chaos-module.md
  docs/chaos-engineering/get-started/learn-more-free-plan.md
  docs/chaos-engineering/get-started/powered-by-litmus.md
  docs/chaos-engineering/get-started/terminologies.md
  docs/chaos-engineering/get-started/whats-supported.md
Labels: draft

#2295 Prepping CD Admin for GA Launch
  src/components/Certifications/CertificationsCD.tsx
  src/components/Certifications/LandingPage.tsx
  src/components/Certifications/data/cd-certification-admin-exam-details.md
  src/components/Certifications/data/cd-certification-developer-exam-details.md
  src/components/Certifications/data/certificationsData.ts
  src/components/Certifications/data/ci-certification-developer-exam-details.md
Labels: draft

#2289 CHAOS-1635: Adds chaos prerequisites, moves topic
  client-redirects.js
  docs/chaos-engineering/configure-chaos-experiments/prerequisites.md
  docs/chaos-engineering/configure-chaos-experiments/prerequisites/_category_.json
  docs/chaos-engineering/configure-chaos-experiments/prerequisites/add-a-new-user-to-a-project.md
  docs/chaos-engineering/configure-chaos-experiments/prerequisites/static/add-a-user-to-a-project/project-access-control.png
  docs/chaos-engineering/configure-chaos-experiments/static/add-new-user.png
  docs/chaos-engineering/technical-reference/security/introduction.md
Labels: peer review

#2280 [DOC-3331] SMP 0.7.0 79421 release notes
  docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
  release-notes/self-managed-enterprise-edition.md
Labels: tech review, DO NOT MERGE
