Repository harness/developer-hub, pull requests merged in 2023-03, with the labels that each got.

#575 Create graceful-delegate-shutdown-process.md
  docs/platform/2_Delegates/get-started-with-delegates/graceful-delegate-shutdown-process.md
Labels: documentation

#843 [DOC-2554] Update security FAQ
  docs/frequently-asked-questions/harness-faqs/chaos-engineering-faq.md
Labels: documentation

#828 [CI-7143] [DOC-2640] - Bitbucket connector settings reference
  docs/platform/7_Connectors/ref-source-repo-provider/bitbucket-connector-settings-reference.md
  docs/platform/7_Connectors/ref-source-repo-provider/git-connector-settings-reference.md
  docs/platform/7_Connectors/ref-source-repo-provider/git-hub-connector-settings-reference.md
  docs/platform/7_Connectors/ref-source-repo-provider/git-lab-connector-settings-reference.md
  docs/platform/7_Connectors/ref-source-repo-provider/http-helm-repo-connector-settings-reference.md
  docs/platform/7_Connectors/ref-source-repo-provider/source-code-manager-settings.md
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-account-cloud-testrepo.png
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-account-http-cloud-url.png
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-account-http-onprem-url.png
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-account-onprem-testrepo.png
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-account-ssh-cloud-url.png
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-connector-settings-reference-ssh-with-port.png
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-repo-http-onprem-url.png
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-repo-ssh-cloud-url.png
  docs/platform/7_Connectors/ref-source-repo-provider/static/bitbucket-username-in-acct-settings.png
Labels: peer review

#849 Updated openshift md
  docs/chaos-engineering/overview/Security/security-templates/openshift-scc.md
Labels: bug

#824 Chaos(aws-fault): Add docs for CLB and ALB az down chaos faults
  docs/chaos-engineering/chaos-faults/aws/alb-az-down.md
  docs/chaos-engineering/chaos-faults/aws/aws.md
  docs/chaos-engineering/chaos-faults/aws/clb-az-down.md
  docs/chaos-engineering/chaos-faults/aws/elb-az-down.md
  docs/chaos-engineering/chaos-faults/aws/experiments.ts
  docs/chaos-engineering/chaos-faults/aws/static/images/alb-az-down.png
  docs/chaos-engineering/chaos-faults/aws/static/images/clb-az-down.png
  docs/chaos-engineering/chaos-faults/aws/static/images/elb-az-down.png
  docs/chaos-engineering/chaos-faults/aws/static/manifests/alb-az-down/target-zones.yaml
  docs/chaos-engineering/chaos-faults/aws/static/manifests/clb-az-down/target-zones.yaml
Labels: documentation

#857 Change note format
  docs/chaos-engineering/chaos-faults/gcp/gcp-vm-disk-loss-by-label.md
  docs/chaos-engineering/chaos-faults/gcp/gcp-vm-disk-loss.md
  docs/chaos-engineering/chaos-faults/gcp/gcp-vm-instance-stop-by-label.md
  docs/chaos-engineering/chaos-faults/gcp/gcp-vm-instance-stop.md
  docs/chaos-engineering/chaos-faults/kube-resilience/kubelet-density.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-cpu-hog.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-disk-loss.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-dns-chaos.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-host-reboot.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-http-latency.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-http-modify-response.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-http-reset-peer.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-io-stress.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-memory-hog.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-network-latency.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-network-loss.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-process-kill.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-service-stop.md
  docs/chaos-engineering/chaos-faults/vmware/vmware-vm-poweroff.md
Labels: documentation

#847 DOC-2685-Deployment freeze not supported for GitOps pipelines
  docs/continuous-delivery/cd-deployments-category/deployment-freeze.md
Labels: tech review, DO NOT MERGE

#830 [DOC-2242] Queue Intelligence
  docs/continuous-integration/troubleshoot/_category_.json
  docs/continuous-integration/troubleshoot/queue-intelligence.md
Labels: peer review

#864 [DOC-2146] CI - glob, regex not supported for Source Path
  docs/continuous-integration/ci-technical-reference/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/ci-technical-reference/upload-artifacts-to-jfrog-artifactory-step-settings.md
  docs/continuous-integration/ci-technical-reference/upload-artifacts-to-s-3-step-settings.md
Labels: peer review

#748 RBAC for Perspectives and Budgets
  docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/manage-access-control-perspective-folders.md
  docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/static/add-folders.png
  docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/static/create-new-resource-group.png
  docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/static/create-new-role.png
  docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/static/custom-role-permissions-1.png
  docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/static/custom-role-permissions-2.png
  docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/static/manage-role-bindings.png
  docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/static/select-resources.png
Labels: enhancement

#859 Added a section for cost categories in dashboards
  docs/cloud-cost-management/2-use-cloud-cost-management/3-ccm-cost-categories/static/cost-categories-dashboards.png
  docs/cloud-cost-management/2-use-cloud-cost-management/3-ccm-cost-categories/use-ccm-cost-categories.md
Labels: documentation

#876 [DOC-2606] - Update Background step Port Binding description
  docs/continuous-integration/ci-technical-reference/background-step-settings.md
  docs/continuous-integration/ci-technical-reference/configure-service-dependency-step-settings.md
Labels: peer review

#730 CDS-52164-Custom Webhook Trigger for Non-Harness CI System
  docs/platform/11_Triggers/static/custom-webhook-trigger-conditions.png
  docs/platform/11_Triggers/static/custom-webhook-trigger-configuration.png
  docs/platform/11_Triggers/static/custom-webhook-trigger-piepline-input.png
  docs/platform/11_Triggers/static/edit-artifact-details.png
  docs/platform/11_Triggers/static/edit-artifacts.png
  docs/platform/11_Triggers/static/pipeline-trigger.png
  docs/platform/11_Triggers/static/webhook-trigger-copy-curl-command.png
  docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
Labels: DO NOT MERGE, peer review

#792 [DOC-2313] [DOC-2019] [DOC-2478] - Parallelism for TI
  docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
  docs/platform/8_Pipelines/speed-up-ci-test-pipelines-using-parallelism.md
Labels: peer review

#852 [DOC-2681] [DOC-2740] - CI build infra task updates for new delegate flow
  docs/continuous-integration/ci-quickstarts/ci-pipeline-quickstart.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
Labels: peer review

#893 [DOC-2727] Custom cache paths, clarify storage
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
Labels: peer review

#866 [DOC-2721] Update architecture.md
  docs/chaos-engineering/technical-reference/architecture.md
Labels: documentation, tech review, peer review

#802 CDS-40448-run-stages-in-parallel
  docs/platform/8_Pipelines/add-a-stage.md
  docs/platform/8_Pipelines/run-stages-in-parallel.md
  docs/platform/8_Pipelines/static/run-stages-in-parallel.png
Labels: tech review, DO NOT MERGE

#809 CDS-34265-skip-label-selector-tracking-for-k8s-deployments
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/skip-harness-label-selector-tracking-on-kubernetes-deployments.md
Labels: DO NOT MERGE, peer review

#899 [DOC-2720] Fixed error in the probePollingInterval field
  docs/chaos-engineering/technical-reference/probes/cmd-probe.md
  docs/chaos-engineering/technical-reference/probes/http-probe.md
  docs/chaos-engineering/technical-reference/probes/k8s-probe.md
  docs/chaos-engineering/technical-reference/probes/prom-probe.md
Labels: bug, documentation

#903 Updated the version number in the CD NG release notes. Had missed doi…
  release-notes/continuous-delivery.md
Labels: release notes

#900 SRM relese notes 78619
  release-notes/service-reliability-management.md
Labels: release notes, edit

#731 [DOC-2495] Docs: Enforcement Limits. Received additional inputs fro…
  docs/platform/17_Settings/pipeline-settings/pipeline-settings.md
Labels: tech review, peer review

#917 [DOC-2752] Removed CDS-53849 and added a description for CDS-52846. T…
  release-notes/continuous-delivery.md
  release-notes/early-access.md
  release-notes/whats-new.md
Labels: draft, release notes

#916 [DOC-2602] - New topic - CI Builds list and Build details page
  docs/continuous-integration/use-ci/view-your-builds/static/ci-build-details-page.png
  docs/continuous-integration/use-ci/view-your-builds/static/ci-builds-gh-pr-link.png
  docs/continuous-integration/use-ci/view-your-builds/static/ci-builds-list-sc-link.png
  docs/continuous-integration/use-ci/view-your-builds/static/ci-builds-list.png
  docs/continuous-integration/use-ci/view-your-builds/viewing-builds.md
  docs/continuous-integration/use-ci/view-your-builds/viewing-tests.md
  release-notes/continuous-integration.md
  release-notes/whats-new.md
Labels: peer review

#919 Update release notes markdown
  release-notes/chaos-engineering.md
Labels: documentation

#848 CDS-47304-default-delegate-proxy-support
  docs/continuous-delivery/cd-technical-reference/cd-gen-ref-category/http-step.md
Labels: tech review, DO NOT MERGE

#961 [PL-31433] Updated image
  docs/platform/20_References/entity-deletion-reference.md
  docs/platform/20_References/static/force-delete-new.png
Labels: edit

#964 [DOC-2760] Updated images for Windows faults
  docs/chaos-engineering/chaos-faults/aws/static/images/windows-ec2-blackhole-chaos.png
  docs/chaos-engineering/chaos-faults/aws/static/images/windows-ec2-blackhole.png
  docs/chaos-engineering/chaos-faults/aws/static/images/windows-ec2-cpu-hog.png
  docs/chaos-engineering/chaos-faults/aws/static/images/windows-ec2-memory-hog.png
  docs/chaos-engineering/chaos-faults/aws/windows-ec2-blackhole-chaos.md
Labels: documentation

#898 [DOC-2499] & related - CI build infrastructure refresh + more Hosted content
  docs/continuous-integration/ci-quickstarts/ci-concepts.md
  docs/continuous-integration/ci-quickstarts/ci-pipeline-basics.md
  docs/continuous-integration/ci-quickstarts/hosted-builds-on-virtual-machines-quickstart.md
  docs/continuous-integration/ci-technical-reference/ci-stage-settings.md
  docs/continuous-integration/troubleshoot/troubleshooting-ci.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/_category_.json
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
  docs/platform/8_Pipelines/w_pipeline-steps-reference/yaml-reference-cd-pipeline.md
Labels: peer review

#974 [DOC-2752] Fixed the indentation issues in the March 8 delegate relea…
  release-notes/delegate.md
Labels: release notes

#975 [DOC-2752] Fixed the indentation issues in the March 8 delegate relea…
  release-notes/whats-new.md
Labels: release notes

#973 DOC-2767: Adds docs for launching an experiment from the chaoshub
  docs/chaos-engineering/user-guides/construct-and-run-custom-chaos-experiments.md
  docs/chaos-engineering/user-guides/static/construct-and-run-custom-chaos-experiments/access-chaoshub.png
  docs/chaos-engineering/user-guides/static/construct-and-run-custom-chaos-experiments/configure-fault.png
Labels: documentation

#968 [DOC-2763] Update connect-chaos-infra.md
  docs/chaos-engineering/user-guides/connect-chaos-infrastructures.md
Labels: documentation

#978 DOC-2702
  docs/first-gen/continuous-delivery/pcf-deployments/pcf-built-in-variables.md
Labels: DO NOT MERGE

#981 DOC-2743-jenkins-job-limitations
  docs/continuous-delivery/cd-execution/cd-general-steps/run-jenkins-jobs-in-cd-pipelines.md
Labels: tech review, DO NOT MERGE

#979 CDS-50645-commitID
  docs/platform/12_Variables-and-Expressions/harness-variables.md
  docs/platform/12_Variables-and-Expressions/static/rolloutdeployment3.png
Labels: tech review, DO NOT MERGE

#994 [DOC-2781] Change ChaosHub to chaos hub
  docs/chaos-engineering/overview/Security/introduction.md
  docs/chaos-engineering/overview/Security/security-templates/kyverno-policies.md
  docs/chaos-engineering/overview/glossary.md
  docs/chaos-engineering/technical-reference/architecture.md
  docs/chaos-engineering/user-guides/manage-chaos-experiment-execution/export-chaos-experiments.md
  docs/frequently-asked-questions/harness-faqs/chaos-engineering-faq.md
  release-notes/chaos-engineering.md
  release-notes/whats-new.md
Labels: documentation

#1005 [DOC-2111] [DOC-2352] [DOC-1911] [DOC-2098] - Several small updates
  docs/continuous-integration/troubleshoot/troubleshooting-ci.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
Labels: peer review

#995 srm release notes for release 787
  release-notes/service-reliability-management.md
  release-notes/static/srm-rn-787-metricgraph.png
  release-notes/whats-new.md
Labels: release notes, peer review

#570 Best practices for templates
  docs/platform/13_Templates/templates-best-practices.md
Labels: work in progress

#982 PL release notes for 787xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/early-access.md
  release-notes/harness-platform.md
  release-notes/whats-new.md
Labels: release notes

#1001 CDS-45178-Create services and environments at account and org level
  docs/continuous-delivery/onboard-cd/cd-concepts/services-and-environments-overview.md
  docs/continuous-delivery/onboard-cd/cd-concepts/static/create-environments-from-account-level.png
  docs/continuous-delivery/onboard-cd/cd-concepts/static/create-services-from-account-level.png
  docs/platform/organizations-and-projects/projects-and-organizations.md
Labels: tech review, DO NOT MERGE

#971 Cds 49992 dora metrics
  docs/continuous-delivery/cd-dashboards/dora-metrics-dashboard.md
  docs/continuous-delivery/cd-dashboards/static/change-failure-rate.png
  docs/continuous-delivery/cd-dashboards/static/deployment-frequency.png
  docs/continuous-delivery/cd-dashboards/static/dora-dashboard.png
  docs/continuous-delivery/cd-dashboards/static/mean-time-to-restore.png
Labels: DO NOT MERGE, peer review

#1028 Add more rows to feature matrix
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
Labels: peer review

#976 Docs - added new topic "SumoLogic health source"
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-autocreate-monitoredservice.png
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-pipeline-fail.png
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-pipeline-pass.png
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-select-log-query-chart-records.png
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-select-metric-query-memory-chart-records.png
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-select-metric-query-memory.png
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-verify-console-view.png
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-verify-summary-view.png
  docs/continuous-delivery/cd-execution/cv-category/static/cv-sumologic-verify-view-anamalous-data.png
  docs/continuous-delivery/cd-execution/cv-category/verify-deployments-with-sumologic.md
Labels: tech review

#933 [PL-31424] New topic for audit streaming.
  docs/platform/15_Audit-Trail/audit-streaming.md
  docs/platform/15_Audit-Trail/audit-trail.md
  docs/platform/15_Audit-Trail/static/audit-stream-overview.png
  docs/platform/15_Audit-Trail/static/audit-streaming.png
  docs/platform/15_Audit-Trail/static/edit-delete.png
  docs/platform/15_Audit-Trail/static/streaming-connector.png
Labels: draft

#1026 FFM-6607, FFM-6172: Catch-up relnotes for Go and Java sdks
  docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md
  release-notes/feature-flags.md
Labels: peer review

#1027 FFM-5868: Adds missed relnotes for .NET sdk
  release-notes/feature-flags.md
Labels: peer review

#1037 Updated the Use Cost Category section
  docs/cloud-cost-management/2-use-cloud-cost-management/3-ccm-cost-categories/static/cost-category-group-by-csp.png
  docs/cloud-cost-management/2-use-cloud-cost-management/3-ccm-cost-categories/static/use-ccm-cost-categories-07.png
  docs/cloud-cost-management/2-use-cloud-cost-management/3-ccm-cost-categories/use-ccm-cost-categories.md
Labels: documentation, tech review

#1038 CDS-45162-Helm subcharts
  docs/continuous-delivery/cd-advanced/cd-helm-category/deploy-helm-chart-with-dependencies-and-subcharts.md
  docs/continuous-delivery/cd-advanced/cd-helm-category/static/helm-dependency.png
  docs/continuous-delivery/cd-advanced/cd-helm-category/static/helm-subchart-fetch.png
Labels: tech review, DO NOT MERGE

#1023 [DOC-2733] Additional matrix examples
  docs/platform/8_Pipelines/w_pipeline-steps-reference/additional-matrix-examples.md
Labels: draft

#1021 [CI-7416] - Update Save and Restore Cache from GCS topic
  docs/continuous-integration/ci-technical-reference/restore-cache-from-gcs-settings.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
  docs/platform/7_Connectors/ref-cloud-providers/gcs-connector-settings-reference.md
Labels: peer review

#1063 Update glossary
  docs/chaos-engineering/overview/glossary.md
Labels: documentation

#1040 CHAOS-931: Adds Linux Chaos Infrastructure Architecture Docs
  docs/chaos-engineering/technical-reference/architecture.md
  docs/chaos-engineering/technical-reference/architecture/_category_.json
  docs/chaos-engineering/technical-reference/architecture/architecture.md
  docs/chaos-engineering/technical-reference/architecture/kubernetes.md
  docs/chaos-engineering/technical-reference/architecture/linux.md
  docs/chaos-engineering/technical-reference/architecture/static/architecture/HCE-architecture.png
  docs/chaos-engineering/technical-reference/architecture/static/architecture/architecture.png
  docs/chaos-engineering/technical-reference/architecture/static/architecture/overview.png
  docs/chaos-engineering/technical-reference/static/architecture/HCE-architecture.png
Labels: documentation

#1082 bug bash for CD module
  docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
  docs/continuous-delivery/cd-advanced/cd-helm-category/deploy-helm-charts.md
  docs/continuous-delivery/cd-advanced/cd-helm-category/use-a-local-helm-chart.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/add-a-custom-remote-script-and-manifests.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/add-a-kubernetes-sidecar-container.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/add-artifacts-for-kubernetes-deployments.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/define-kubernetes-manifests.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/harness-community-edition-overview.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/ignore-a-manifest-file-during-deployment.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/kubernetes-deployments-overview.md
  docs/continuous-delivery/cd-advanced/cd-kubernetes-category/prune-kubernetes-resources.md
  docs/continuous-delivery/cd-advanced/cd-notifications/notify-users-of-pipeline-events.md
  docs/continuous-delivery/cd-advanced/cloudformation-howto/provision-with-the-cloud-formation-create-stack-step.md
  docs/continuous-delivery/cd-advanced/kustomize-howtos/use-kustomize-for-kubernetes-deployments.md
  docs/continuous-delivery/cd-advanced/terraform-category/run-a-terraform-plan-with-the-terraform-apply-step.md
  docs/continuous-delivery/cd-advanced/terraform-category/run-a-terraform-plan-with-the-terraform-plan-step.md
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/create-service-now-tickets-in-cd-stages.md
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/update-jira-issues-in-cd-stages.md
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/update-service-now-tickets-in-cd-stages.md
  docs/continuous-delivery/cd-gitops/add-a-harness-git-ops-repository.md
  docs/continuous-delivery/cd-gitops/add-harness-git-ops-repository-credentials-template.md
  docs/continuous-delivery/cd-gitops/harness-cd-git-ops-quickstart.md
  docs/continuous-delivery/cd-gitops/harness-git-ops-application-set-tutorial.md
  docs/continuous-delivery/cd-technical-reference/cd-gen-ref-category/email_step.md
  docs/continuous-delivery/cd-technical-reference/cd-gen-ref-category/http-step.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/canary-deployment-step.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/example-kubernetes-manifests-using-go-templating.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/kubernetes-annotations-and-labels.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/kubernetes-rollback.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/kubernetes-rollout-step.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/kubernetes-steps-timeouts-and-deadline-parameters.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/using-open-shift-with-harness-kubernetes.md
  docs/continuous-delivery/cd-technical-reference/cd-k8s-ref/what-can-i-deploy-in-kubernetes.md
Labels: documentation, DO NOT MERGE

#1086 update chaos-engineering.md
  tutorials/run-chaos-experiments/first-chaos-engineering.md
Labels: documentation

#874 CDS-45268-tas-swimlane
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/artifactory-repo-connector.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/basic-deployment.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/bg-deployment.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/canary-deployment.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/config-file.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/create-tas-pipeline.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/delegate-logs-cf-cli.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/delegate-wizard.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/deploy-tas-service.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/manifest-yaml.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/rolling-deployment.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/successful-bg-deployment.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/tas-infra-details.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/tas-manifest-type.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/static/vars-yaml.png
  docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
Labels: tech review, DO NOT MERGE

#1098 [DOC-2809] CI docs - Bug Bash
  docs/continuous-integration/ci-quickstarts/ci-concepts.md
  docs/continuous-integration/ci-quickstarts/ci-pipeline-basics.md
  docs/continuous-integration/ci-quickstarts/ci-pipeline-quickstart.md
  docs/continuous-integration/ci-quickstarts/drone-and-harness.md
  docs/continuous-integration/ci-technical-reference/built-in-cie-codebase-variables-reference.md
  docs/continuous-integration/ci-technical-reference/ci-build-image-updates.md
  docs/continuous-integration/ci-technical-reference/ci-cluster-requirement.md
  docs/continuous-integration/ci-technical-reference/ci-git-clone-step.md
  docs/continuous-integration/ci-technical-reference/ci-github-action-step.md
  docs/continuous-integration/ci-technical-reference/ci-stage-settings.md
  docs/continuous-integration/ci-technical-reference/configure-run-tests-step-settings.md
  docs/continuous-integration/ci-technical-reference/group-ci-steps-using-step-groups.md
  docs/continuous-integration/ci-technical-reference/restore-cache-from-s-3-step-settings.md
  docs/continuous-integration/ci-technical-reference/run-step-settings.md
  docs/continuous-integration/ci-technical-reference/save-cache-to-s-3-step-settings.md
  docs/continuous-integration/ci-technical-reference/upload-artifacts-to-s-3-step-settings.md
  docs/continuous-integration/migration-guides/migrating-from-circleci.md
  docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
  docs/continuous-integration/troubleshoot/troubleshooting-ci.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/caching-ci-data/share-ci-data-across-steps-and-stages.md
  docs/continuous-integration/use-ci/run-ci-scripts/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-a-script-in-a-ci-stage.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
  docs/frequently-asked-questions/harness-faqs/continuous-integration-ci-faqs.md
Labels: peer review

#1078 PL Release Notes 788xx
  release-notes/early-access.md
  release-notes/harness-platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#1101 [DOC-2841] Update FAQ
  docs/frequently-asked-questions/harness-faqs/chaos-engineering-faq.md
Labels: bug, documentation

#1010 CCM-11622-Updated the currency preferences page
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/currency-preferences.md
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/static/budget-currency-preference-2.png
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/static/budget-screen-alert-currency-preference.png
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/static/currency-preference-banner.png
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/static/currency-preference-budget-1.png
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/static/currency-preference-budget.png
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/static/currency-preference-locale.png
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/static/currency-preference-recommendations.png
  docs/cloud-cost-management/2-use-cloud-cost-management/ccm-currency-preferences/static/currency-preference-settings.png
Labels: tech review

#1081 SRM release notes for release 788
  release-notes/service-reliability-management.md
  release-notes/whats-new.md
Labels: release notes, edit

#1084 Release Notes - CD, March 23, 788xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/continuous-delivery.md
  release-notes/static/auto-suggestion.png
  release-notes/static/connector-credentials.png
  release-notes/static/tag-regex.png
Labels: DO NOT MERGE, peer review

#1059 CI release notes 788xx
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
  release-notes/continuous-integration.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#1093 Elasticsearch health source - new UI
  docs/continuous-delivery/cd-execution/cv-category/verify-deployments-with-elastic-search.md
Labels: edit

#1123 Update deploy-helm-charts.md
  docs/continuous-delivery/cd-advanced/cd-helm-category/deploy-helm-charts.md
  docs/continuous-delivery/cd-advanced/cd-helm-category/static/update-helm-dependencies-nativek8s.png
  docs/continuous-delivery/cd-advanced/cd-helm-category/static/update-helm-dependency-k8s.png
Labels: documentation

#1127 FFM-7232: adds requirement for proxy config
  docs/feature-flags/ff-using-flags/relay-proxy/deploy-relay-proxy.md
Labels: peer review

#1128 FFM-7321: adds Erlang 1.0.0 relnotes
  docs/feature-flags/ff-sdks/sdk-overview/client-side-and-server-side-sdks.md
  release-notes/feature-flags.md
Labels: peer review

#1036 DOC-2773-CG/NG-transition
  docs/continuous-delivery/onboard-cd/upgrading/static/launch-harness-next-gen.png
  docs/continuous-delivery/onboard-cd/upgrading/upgrade-nextgen-cd.md
Labels: tech review, DO NOT MERGE

#1100 [CI-7494] Add mount cert command and break into tabs
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
Labels: tech review

#1129 Fixed typo
  docs/platform/13_Templates/create-a-stepgroup-template.md
Labels: bug

#1125 CHAOS-931: Add user guide for LCI advanced management
  docs/chaos-engineering/technical-reference/architecture/linux.md
  docs/chaos-engineering/user-guides/linux-chaos-infrastructure-advanced-management.md
  docs/chaos-engineering/user-guides/static/linux-chaos-infrastructure-advanced-management/terminal.png
Labels: documentation

#1140 [DOC-2845] Remove absolute links
  docs/chaos-engineering/overview/Security/introduction.md
  docs/chaos-engineering/overview/Security/namespace-considerations.md
  docs/chaos-engineering/user-guides/construct-and-run-custom-chaos-experiments.md
Labels: documentation

#1155 Removed IaCM and SCM
  docs/getting-started/harness-ui-overview.md
  docs/getting-started/static/drag-drop-modules1.png
  docs/getting-started/static/module-info1.png
Labels: bug

#1160 [DOC-2864] Remove irrelevant descriptions
  docs/chaos-engineering/chaos-faults/categories.tsx
  docs/chaos-engineering/chaos-faults/chaos-faults.md
Labels: documentation

#1166 [DOC-2869] Update images
  docs/chaos-engineering/technical-reference/architecture.md
  docs/chaos-engineering/technical-reference/static/architecture/HCE-architecture.png
  docs/chaos-engineering/technical-reference/static/architecture/overview.png
Labels: documentation

#1180 Updated supported Helm Registry URL types
  docs/platform/7_Connectors/connect-to-an-artifact-repo.md
Labels: documentation, DO NOT MERGE

#1144 PL Release Notes 789xx
  release-notes/harness-platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#1170 FFM-7341: Updates release notes for GO 0.1.7 sdk, corrects java version num
  docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md
  docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md
  release-notes/feature-flags.md
Labels: peer review

#1171 FFM-7348: GO 0.1.8 relnotes
  docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md
  release-notes/feature-flags.md
Labels: peer review

#1149 CI RN 789xx
  docs/continuous-integration/ci-technical-reference/built-in-cie-codebase-variables-reference.md
  release-notes/continuous-integration.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#1188 minor updates to RN
  release-notes/continuous-delivery.md
  release-notes/whats-new.md
Labels: documentation, DO NOT MERGE

#1186 [DOC-2851] Doc: Update content of services overview and deployment ov…
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
Labels: release notes

#1183 [DOC-2851] Doc: Update content of services overview and deployment ov…
  docs/first-gen/firstgen-platform/fg-monitoring/main-and-services-dashboards.md
Labels: enhancement
