Repository harness/developer-hub, pull requests merged in 2023-12, with the labels that each got.

#4422 [CDS-85903] Documentation for CDS-82272: Add new type for Freeze noti…
  docs/continuous-delivery/manage-deployments/deployment-freeze.md
Labels: documentation, enhancement

#4375 [CDS-85651] CDS 817xx release notes
  release-notes/continuous-delivery.md
Labels: release notes

#4429 [CDS-85930] Documentation for CDS-74294 - CG Git Sync parity in GitX …
  docs/platform/git-experience/gitexp-bidir-sync-setup.md
Labels: documentation, enhancement

#4425 [CDS-85760] Document permissions for Overrides V2
  docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
Labels: documentation, gap in docs

#4420 DOC-3914 ECS task scale docs
  docs/chaos-engineering/technical-reference/chaos-faults/aws/aws.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-task-scale.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/experiments.ts
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/ecs-task-scale.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/manifests/ecs-task-scale/task-replicas.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/manifests/ecs-task-scale/task-service-name.yaml
Labels: documentation, work in progress, tech review

#4470 Add ecs-task-scale link to docs
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-and-serverless-faults.md
Labels: documentation

#4349 Release notes
  release-notes/chaos-engineering.md
Labels: release notes

#4417 Update run-a-terraform-plan-with-the-terraform-apply-step.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/optional-tf-var-files.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/remove-provisioned-infra-with-terraform-destroy.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md
Labels: documentation, enhancement, draft, tech review, DO NOT MERGE, pm review

#4483 [SMP-2348] SMP 0.11.2 patch release notes
  release-notes/self-managed-enterprise-edition.md
Labels: tech review, DO NOT MERGE

#4500 Chaos 3048 docs review smriti
  docs/chaos-engineering/chaos-infrastructure/linux-chaos-infrastructure-advanced-management.md
Labels: documentation

#4541 Sto tutorial refactor semgrep sto 6723 v3
  docs/security-testing-orchestration/get-started/onboarding-guide.md
  docs/security-testing-orchestration/get-started/overview.md
  docs/security-testing-orchestration/get-started/tutorials.md
  docs/security-testing-orchestration/sto-techref-category/aqua-trivy-scanner-reference.md
  src/components/Certifications/data/sto-certification-admin-review-guide.md
  src/components/LandingPage/data/securityTestingOrchestrationData.tsx
  tutorials/security-tests/container-scan-aqua-trivy.md
  tutorials/security-tests/gitlab-ci-integration.md
  tutorials/security-tests/nodejs-owasp.txt
  tutorials/security-tests/sast-scan-semgrep.md
  tutorials/security-tests/static/container-scan-trivy/execution-snyk-labs.png
  tutorials/security-tests/static/container-scan-trivy/pipeline-editor-stage.png
  tutorials/security-tests/static/container-scan-trivy/scan-results-snyklabs-goof.png
  tutorials/security-tests/static/container-scan-trivy/snyklabs-goof-baseline-set.png
  tutorials/security-tests/static/sast-semgrep-tutorial/about_your_stage.png
  tutorials/security-tests/static/sast-semgrep-tutorial/baseline-set.png
  tutorials/security-tests/static/sast-semgrep-tutorial/codebase-repo-type-input.png
  tutorials/security-tests/static/sast-semgrep-tutorial/ingestion-only-workflow.png
  tutorials/security-tests/static/sast-semgrep-tutorial/pipeline-failed-critical-issues-found.png
  tutorials/security-tests/static/sast-semgrep-tutorial/security-tests-results.png
  tutorials/security-tests/static/sast-semgrep-tutorial/set-value-type.png
  tutorials/security-tests/static/sast-semgrep-tutorial/stage-var-git-token.png
  tutorials/security-tests/static/sto-integrated-workflows-10-snyk-with-remediation-steps.png
  tutorials/security-tests/static/sto-integrated-workflows-40-compare-results.png
  tutorials/security-tests/static/sto-standalone-workflows-10.png
  tutorials/security-tests/static/sto-standalone-workflows-11.png
  tutorials/security-tests/static/sto-standalone-workflows-12.png
  tutorials/security-tests/static/sto-standalone-workflows-13.png
  tutorials/security-tests/static/sto-standalone-workflows-14.png
  tutorials/security-tests/static/sto-standalone-workflows-15.png
  tutorials/security-tests/static/sto-standalone-workflows-16-indiv-issue-details.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-00-create-pipeline.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-01-create-sto-stage.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-02-set-up-sto-stage.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-04-select-trigger.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-05-trigger-config.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-06-trigger-condition.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-07-copy-url-webhook.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-08-pipeline-input.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-09-security-tests.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-09-triggered-build.png
  tutorials/security-tests/static/trigger-tutorial/trigger-tutorial-10-security-tests.png
  tutorials/security-tests/your-first-sto-pipeline.md
Labels: DO NOT MERGE

#4501 [SMP-2350] SMP increase PV size for StatefulSets
  docs/self-managed-enterprise-edition/advanced-configurations/increase-pv-size-statefulsets.md
Labels: tech review, DO NOT MERGE

#4552 [PL-43488] PL NG release notes - important feature change notice
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#4314 DOCS 3911 Update href links in the tunables section of faults
  docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-disk-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-io-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-memory-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-instance-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-web-app-access-restrict.md
  docs/chaos-engineering/technical-reference/chaos-faults/azure/azure-web-app-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-disk-loss-by-label.md
  docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-disk-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-instance-stop-by-label.md
  docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp-vm-instance-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/kube-resilience/kubelet-density.md
  docs/chaos-engineering/technical-reference/chaos-faults/load/locust-loadgen.md
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/kube-security-cis.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-disk-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-dns-chaos.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-host-reboot.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-http-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-http-modify-response.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-http-reset-peer.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-io-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-memory-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-network-rate-limit.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-process-kill.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-service-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-vm-poweroff.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-blackhole-chaos.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-disk-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-memory-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-corruption.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-duplication.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-network-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-process-kill.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-service-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware-windows-time-chaos.md
Labels: documentation, work in progress, DO NOT MERGE

#4418 Update ecs-deployment-tutorial.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
Labels: documentation, enhancement, tech review, DO NOT MERGE, Waiting for Release, pm review

#4549 [CDS-86363] Documentation for CDS-69442, Part 1 - Release Name Genera…
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/define-your-kubernetes-target-infrastructure.md
  docs/continuous-delivery/get-started/services-and-environments-overview.md
  docs/continuous-delivery/get-started/upgrading/upgrade-cd-v2.md
  docs/continuous-delivery/x-platform-cd-features/environments/create-environments.md
  docs/platform/automation/api/api-quickstart.md
  docs/platform/automation/terraform/advanced-terraform-onboarding.md
  docs/platform/automation/terraform/automate-harness-onboarding.md
  docs/platform/templates/template.md
  docs/platform/variables-and-expressions/harness-variables.md
Labels: documentation, enhancement, draft, tech review, DO NOT MERGE, pm review

#4521 [CDS-86041] CDS 818xx release notes
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/continuous-delivery.md
  release-notes/early-access.md
Labels: release notes, DO NOT MERGE, Waiting for Release

#4563 [CDS-86041] Corrected the version numbers in the CDS 818xx release notes
  release-notes/continuous-delivery.md
Labels: release notes

#4482 [PL-43392] Platform NG 81820, FG 81812, delegate 23.12.81803 release notes
  docs/first-gen/firstgen-release-notes/fg-delegate.md
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/delegate.md
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#4576 [DOC-3933] Helm delegate custom certs
  docs/platform/delegates/secure-delegates/install-delegates-with-custom-certs.md
Labels: tech review, DO NOT MERGE

#4566 [CDS-86161] Documentation Improvement for template Reconciliation
  docs/platform/templates/reconcile-pipeline-templates.md
Labels: documentation, draft, tech review, DO NOT MERGE, gap in docs

#4546 CDS-67354 deployment data retention
  docs/platform/references/data-retention.md
Labels: bug, question, draft, DO NOT MERGE, pm review

#3656 [CDS-54343] ServiceNow tickets in CD stages updates
  docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-service-now-tickets-in-cd-stages.md
Labels: tech review, DO NOT MERGE

#4589 DOC-3937 Image registry
  docs/chaos-engineering/configure-chaos-experiments/image-registry.md
  docs/chaos-engineering/configure-chaos-experiments/static/image-registry/click-save.png
  docs/chaos-engineering/configure-chaos-experiments/static/image-registry/private-registry.png
  docs/chaos-engineering/configure-chaos-experiments/static/image-registry/public-registry.png
  docs/chaos-engineering/configure-chaos-experiments/static/image-registry/select-custom.png
  docs/chaos-engineering/configure-chaos-experiments/static/image-registry/select-default.png
Labels: documentation, enhancement, tech review

#4511 release notes for 1.26.0
  release-notes/chaos-engineering.md
Labels: work in progress, release notes, peer review, Waiting for Release

#4562 DOC-3930 Chaos dashboard documentation
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/_category_.json
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/create-a-new-dashboard.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/overview.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/add-visualization.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/click-continue.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/click-dashboard.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/click-run.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/edit-dashboard.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/save-visual.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/select-fields.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/select-type.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/create-a-new-dashboard/specify-params.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/overview/analysis-1.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/overview/analysis-2.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/overview/analysis-3.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/overview/chaos-dashboard-intro.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/overview/download-data.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/overview/go-to-dashboard.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-dashboard/static/overview/select-chaos.png
Labels: documentation, enhancement, work in progress, peer review

#4580 [PL-43557] PL 1.16.6 release notes
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#4627 [DOC-2261] Update delegate auto upgrade status info, add delegate list page doc
  docs/platform/delegates/delegate-concepts/delegate-overview.md
  docs/platform/delegates/delegate-concepts/static/delegates-list-page.png
  docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
  docs/platform/delegates/install-delegates/static/auto-upgrade-on.png
Labels: tech review, DO NOT MERGE

#4594 Ci rn 818xx
  release-notes/continuous-integration.md
Labels: DO NOT MERGE

#4611 CD release notes Dec 2023 81904
  release-notes/continuous-delivery.md
Labels: release notes, DO NOT MERGE

#4569 [PL-43530] [CDS-86689] Delegate 23.12.81804 hotfix release notes
  release-notes/delegate.md
Labels: tech review, DO NOT MERGE

#4671 STO tutorial tweaks STO-6833
  docs/security-testing-orchestration/get-started/key-concepts/_category_.json
  docs/security-testing-orchestration/get-started/onboarding-guide.md
  docs/security-testing-orchestration/get-started/static/set-up-harness-for-sto-22.png
  docs/security-testing-orchestration/get-started/static/set_up_harness_20_NEW.png
  docs/security-testing-orchestration/get-started/static/setup-tutorial-create-base-pipeline-select-module.png
  docs/security-testing-orchestration/get-started/tutorials.md
  src/components/LandingPage/data/securityTestingOrchestrationData.tsx
  tutorials/security-tests/build-scan-push-sto-ci.md
  tutorials/security-tests/build-scan-push-sto-only.md
  tutorials/security-tests/container-scan-aqua-trivy.md
  tutorials/security-tests/your-first-sto-pipeline.md
Labels: DO NOT MERGE

#4638 CI 819xx / 1.5.x release notes
  release-notes/continuous-integration.md
Labels: DO NOT MERGE

#4683 [CDB-1392] Manage dashboard RBAC
  docs/platform/role-based-access-control/manage-dashboards.md
  docs/platform/role-based-access-control/static/manage-access-control-for-dashboards-01.png
  docs/platform/role-based-access-control/static/manage-access-control-for-dashboards-02.png
Labels: tech review, DO NOT MERGE

#4685 [PL-43722] Update PL 813xx, 815xx, 816xx, 817xx RN
  release-notes/early-access.md
  release-notes/platform.md
Labels: tech review

#4717 [PL-43780] [CDS-87415] Delegate HF 81808 release notes
  release-notes/delegate.md
Labels: tech review, DO NOT MERGE

#4722 [CDB-1267] Dashboard intelligence by AIDA
  docs/platform/dashboards/static/create-a-widget-AIDA-01.png
  docs/platform/dashboards/static/create-a-widget-AIDA-02.png
  docs/platform/dashboards/static/create-a-widget-AIDA-03.png
  docs/platform/dashboards/static/create-a-widget-AIDA-04.png
  docs/platform/dashboards/static/create-a-widget-AIDA-05.png
  docs/platform/dashboards/static/ff-table-example.png
  docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
Labels: tech review, DO NOT MERGE
