Repository harness/developer-hub, pull requests merged in 2023-07, with the labels that each got.

#2233 [DOC-3283] Add replica pod deletion
  docs/platform/2_Delegates/delegate-concepts/graceful-delegate-shutdown-process.md
  docs/platform/2_Delegates/manage-delegates/delete-a-delegate.md
Labels: tech review

#2354 CDS-73578
  docs/platform/11_Triggers/trigger-deployments-using-custom-triggers.md
  docs/platform/17_Settings/default-settings.md
  docs/platform/20_References/entity-deletion-reference.md
  docs/platform/Resource-Development/16_APIs/jwt-token-auth.md
Labels: documentation, DO NOT MERGE

#2352 PL release notes for 798xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#2345 SRM Release Notes for 798
  release-notes/service-reliability-management.md
Labels: peer review

#2327 CD RN 798xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/continuous-delivery.md
Labels: DO NOT MERGE

#2315 CI-798xx Release Notes
  release-notes/continuous-integration.md
Labels: peer review

#2205 [CDS-66789] Add sample pipeline with output expression
  docs/platform/8_Pipelines/pipeline-chaining.md
Labels: tech review

#2361 [SMP-1584] Update air gap docs with module file info
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md
Labels: peer review

#2373 [DOC-3370] Add helm chart version note
  tutorials/platform/install-delegate.md
Labels: tech review

#1569 CHAOS-1213: Add docs for pod io chaos faults
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/experiments.ts
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/kubernetes.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-io-attribute-override.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-io-error.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-io-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/shared/io-faults-caution.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/images/pod-io-attribute-override.png
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/images/pod-io-error.png
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/images/pod-io-latency.png
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-attribute-override/advanced-fault-tunables.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-attribute-override/attributes.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-attribute-override/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-attribute-override/mount-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-error/advanced-fault-tunables.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-error/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-error/io-error.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-error/mount-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-latency/advanced-fault-tunables.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-latency/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-latency/io-latency.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-io-latency/mount-path.yaml
Labels: documentation, DO NOT MERGE

#2384 [SMP-1614] SMP v79421 patch release notes
  docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
  release-notes/self-managed-enterprise-edition.md
Labels: tech review, DO NOT MERGE

#2405 fix broken link in Getting Started
  docs/getting-started/learn-harness-key-concepts.md
Labels: peer review

#2408 [PL-39781] Add a note to install delegate with custom cert installation topic
  docs/platform/2_Delegates/secure-delegates/install-delegates-with-custom-certs.md
Labels: tech review

#2399 CDS-58666-added diagrams to GitOps docs
  docs/continuous-delivery/gitops/harness-git-ops-basics.md
  docs/continuous-delivery/gitops/static/agent.png
  docs/continuous-delivery/gitops/static/cluster-agent-delegate.png
  docs/continuous-delivery/gitops/static/deploy-cluster.png
  docs/continuous-delivery/gitops/static/gitops-archcitecture.png
Labels: documentation, DO NOT MERGE

#2395 [PL-38164] Add delegate selector details
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/add-a-custom-remote-script-and-manifests.md
  docs/continuous-delivery/x-platform-cd-features/executions/cd-general-steps/using-shell-scripts.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/first-gen/firstgen-platform/account/manage-delegates/select-delegates-for-specific-tasks-with-selectors.md
  docs/frequently-asked-questions/harness-faqs/harness-delegate-faqs.md
  docs/platform/2_Delegates/delegate-concepts/delegate-overview.md
  docs/platform/2_Delegates/manage-delegates/select-delegates-with-selectors.md
  docs/platform/2_Delegates/shared/selector-infrastructure.md
  tutorials/platform/install-delegate.md
Labels: peer review

#1896 CCM-12624-Added ccm-smp docs
  docs/cloud-cost-management/2-getting-started-ccm/ccm-smp/1-smp-ccm-roadmap.md
  docs/cloud-cost-management/2-getting-started-ccm/ccm-smp/_category_.json
  docs/cloud-cost-management/2-getting-started-ccm/ccm-smp/aws-smp.md
  docs/cloud-cost-management/2-getting-started-ccm/ccm-smp/static/aws-smp-arch.png
  docs/cloud-cost-management/2-getting-started-ccm/ccm-smp/static/aws-upload-cf-tempalte.png
  docs/cloud-cost-management/2-getting-started-ccm/ccm-smp/static/gcp-roles-condition.png
  docs/cloud-cost-management/2-getting-started-ccm/ccm-smp/static/gcp-smp-role.png
  docs/cloud-cost-management/shared/gcp-smp.md
  docs/cloud-cost-management/shared/static/gcp-roles-condition.png
  docs/cloud-cost-management/shared/static/gcp-smp-role.png
Labels: tech review, peer review

#2418 DOC-3269-Added a note for K8s SA token
  docs/first-gen/firstgen-platform/account/manage-connectors/add-kubernetes-cluster-cloud-provider.md
Labels: documentation, DO NOT MERGE

#2329 [DOC-3118] Fav Framework
  docs/platform/Favourites/_category_.json
  docs/platform/Favourites/set-favourites.md
  docs/platform/Favourites/static/filter-fav.png
  docs/platform/Favourites/static/set-proj-fav.png
  docs/platform/Favourites/static/set_connector_fav.png
Labels: draft

#2378 CHAOS-2012: adds 0.14.5/6 relnotes
  release-notes/chaos-engineering.md
Labels: Waiting for Release

#2431 [DOC-3396] Fix broken xref
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Labels: peer review

#2434 Fix broken links cd
  client-redirects.js
  docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-provisioning-with-harness.md
  docs/first-gen/first-gen-quickstarts/aws-ecs-deployments.md
  tutorials/cd-pipelines/continuous-verification/prometheus.md
Labels: documentation

#2424 Doc-3386
  client-redirects.js
  docs/continuous-integration/shared/docker-hub-rate-limiting-trbs.md
  docs/continuous-integration/shared/k8s-pod-eviction-trbs.md
  docs/continuous-integration/troubleshoot-ci/troubleshooting-ci.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-build-image-updates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/resource-limits.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/parallel-debug-steps.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/resource-limit-calc1.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/resource-limit-calc2.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/resource-limit-calc3.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/resource-limit-calc4.png
  docs/platform/7_Connectors/Artifact-Repositories/connect-to-harness-container-image-registry-using-docker-connector.md
Labels: peer review

#2462 Cds 56499 override v2
  docs/continuous-delivery/x-platform-cd-features/advanced/_category_.json
  docs/continuous-delivery/x-platform-cd-features/cd-steps/_category_.json
  docs/continuous-delivery/x-platform-cd-features/executions/_category_.json
  docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
  docs/continuous-delivery/x-platform-cd-features/static/f3298b583d8308e026c05f7dd544195756bb080b43438c0a83ab389c97af794a.png
  docs/continuous-delivery/x-platform-cd-features/static/override-priority.png
  docs/continuous-delivery/x-platform-cd-features/static/overrides-v2-1.png
  docs/continuous-delivery/x-platform-cd-features/static/overrides-v2.png
  docs/continuous-delivery/x-platform-cd-features/static/service-override.png
  docs/continuous-delivery/x-platform-cd-features/static/service-override2.png
  docs/continuous-delivery/x-platform-cd-features/static/services-and-environments-overview-17.png
  docs/continuous-delivery/x-platform-cd-features/templates/_category_.json
Labels: documentation, draft, DO NOT MERGE

#2312 [DOC-3339] write new topic about non root build and push
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-nonroot.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-docker-hub-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/static/sonatype-nexus-plugin-visual-settings.png
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-sonatype-nexus.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/use-drone-plugins/explore-ci-plugins.md
  docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
  docs/continuous-integration/use-ci/use-drone-plugins/static/plugin-marketplace-readme-link.png
  release-notes/continuous-integration.md
Labels: peer review

#2477 Platform release notes for 799xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: release notes, DO NOT MERGE

#2511 CDS-73127
  docs/continuous-delivery/manage-deployments/deployment-freeze.md
Labels: documentation, DO NOT MERGE

#2516 CDS-74295-Helm 2 deprecation notice
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
Labels: documentation, DO NOT MERGE

#2524 [DOC-3423] Add helm chart section back into the Install using Helm topic
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Labels: tech review

#2463 CDS-73133-limitation for service overrides on multi env set up
  docs/continuous-delivery/get-started/services-and-environments-overview.md
  docs/continuous-delivery/x-platform-cd-features/environments/service-overrides.md
Labels: documentation, DO NOT MERGE

#2528 [DOC-3424] Add delegate task capacity to overview
  docs/platform/2_Delegates/delegate-concepts/delegate-overview.md
Labels: tech review

#2541 Update cache-intelligence.md
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
Labels: peer review

#2531 Create Trimming-parent-folder-name-while-uploading-files-to-S3.md
  kb/continuous-integration/articles/Trimming-parent-folder-name-while-uploading-files-to-S3.md
  kb/platform/articles/Unable-to-Install-Custom-Tools-on-Delegate-via-Init-Script.md
Labels: KB

#2482 Create Triggered pipeline fails
  kb/continuous-delivery/articles/Triggered pipeline fails
Labels: KB

#2328 CDS-70134-Post prod rollback support for ECS deployments
  docs/continuous-delivery/x-platform-cd-features/advanced/rollback-deployments.md
Labels: documentation, DO NOT MERGE

#2548 DOC-3269-Create SA for K8s 1.24 or later
  docs/platform/7_Connectors/Cloud-providers/add-a-kubernetes-cluster-connector.md
Labels: documentation, DO NOT MERGE

#2562 [PL-40190] Add API rate limit topic
  docs/platform/Resource-Development/16_APIs/api-quickstart.md
  docs/platform/Resource-Development/16_APIs/default-settings-for-jwt-token.md
  docs/platform/Resource-Development/16_APIs/harness-rest-api-reference.md
  docs/platform/Resource-Development/16_APIs/jwt-token-auth.md
  docs/platform/Resource-Development/16_APIs/rate-limits.md
Labels: peer review

#2555 [DOC-3433] Delegate hotfix 79906
  release-notes/delegate.md
Labels: DO NOT MERGE

#2578 [PL-40204] Application rate limits, API rate limits update
  docs/platform/Resource-Development/16_APIs/api-quickstart.md
  docs/platform/Resource-Development/16_APIs/rate-limits.md
  docs/platform/Security/add-manage-ip-allowlist.md
  docs/platform/Security/rate-limits.md
Labels: tech review

#2579 Update ability-to-view:filter-pipeline-execution-by-inputs.md
  kb/continuous-delivery/articles/ability-to-view:filter-pipeline-execution-by-inputs.md
Labels: KB

#2596 Added CV 79922 HF
  release-notes/continuous-delivery.md
Labels: documentation, DO NOT MERGE

#2593 Created a PR for FG delegate hotfix 79908, with content identical in …
  docs/first-gen/firstgen-release-notes/fg-delegate.md
Labels: release notes, DO NOT MERGE

#2605 fixed cd broken links
  docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-how-tos.md
  release-notes/early-access.md
Labels: documentation

#2610 Update early-access.md
  release-notes/early-access.md
Labels: peer review

#2417 New Tutorial on Triggers using Git Events
  tutorials/cd-pipelines/static/triggers/custom-trigger.png
  tutorials/cd-pipelines/static/triggers/github-trigger.png
  tutorials/cd-pipelines/static/triggers/gitlab-trigger.png
  tutorials/cd-pipelines/trigger.md
Labels: tutorial

#2609 Helm V2 deprecation notice
  docs/continuous-delivery/deploy-srv-diff-platforms/native-helm-quickstart.md
Labels: documentation

#2587 CDS-74891-whitelist AWS endpoints
  docs/platform/7_Connectors/Cloud-providers/add-aws-connector.md
Labels: documentation, DO NOT MERGE

#2576 CI-8092 - Can't use GHA that start DinD in stages with DinD Background steps
  docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
Labels: peer review

#2584 DOC-3376 git lfs in CI
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/gitlfs.md
Labels: peer review

#2517 AWS and Azure VM Tutorials
  tutorials/cd-pipelines/vm/aws.md
Labels: tutorial

#2646 Fastapi tutorial
  src/components/LandingPage/data/continuousIntegrationData.tsx
  src/components/Tutorials/ContinuousIntegrationBuildData.ts
  src/components/Tutorials/ContinuousIntegrationTestData.ts
  tutorials/ci-pipelines/test/ci-fastapi-test.md
  tutorials/ci-pipelines/test/ci-localstack-background-step.md
Labels: peer review

#2657 [DOC-3488] Move rate limits, delete api rate limits
  client-redirects.js
  docs/platform/10_Git-Experience/_category_.json
  docs/platform/11_Triggers/_category_.json
  docs/platform/12_Variables-and-Expressions/_category_.json
  docs/platform/13_Templates/_category_.json
  docs/platform/17_Settings/_category_.json
  docs/platform/18_Dashboards/_category_.json
  docs/platform/1_Get-started/_category_.json
  docs/platform/20_References/_category_.json
  docs/platform/2_Delegates/_category_.json
  docs/platform/3_Authentication/_category_.json
  docs/platform/3_User-Management/_category_.json
  docs/platform/4_Role-Based-Access-Control/_category_.json
  docs/platform/5_Notifications/_category_.json
  docs/platform/7_Connectors/_category_.json
  docs/platform/8_Pipelines/_category_.json
  docs/platform/9_Approvals/_category_.json
  docs/platform/Favourites/_category_.json
  docs/platform/Governance/_category_.json
  docs/platform/Harness-AIDA/_category_.json
  docs/platform/Resource-Development/16_APIs/api-quickstart.md
  docs/platform/Resource-Development/16_APIs/rate-limits.md
  docs/platform/Resource-Development/_category_.json
  docs/platform/Secrets/_category_.json
  docs/platform/Security/_category_.json
  docs/platform/organizations-and-projects/_category_.json
  docs/platform/rate-limits.md
Labels: tech review

#2616 [DOC-3458] Move external mongodb topic
  client-redirects.js
  docs/self-managed-enterprise-edition/back-up-and-recover/_category_.json
  docs/self-managed-enterprise-edition/back-up-and-restore-helm.md
  docusaurus.config.js
  sidebars-tutorials.js
  src/components/LandingPage/AllTutorials.tsx
  src/components/LandingPage/SMP.tsx
  src/components/LandingPage/TutorialCard.module.scss
  src/components/LandingPage/data/smpData.tsx
  src/constants.ts
  tutorials/self-managed-enterprise-edition.md
  tutorials/self-managed-enterprise-edition/use-an-external-mongodb-database.md
Labels: tech review, DO NOT MERGE

#2606 doc-3446
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md
Labels: peer review

#2570 Release notes for Platform release 800xx
  release-notes/platform.md
  release-notes/whats-new.md
Labels: release notes, DO NOT MERGE, peer review

#2661 Doc-3487 revise artifact tab tutorial
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  tutorials/ci-pipelines/publish/ci-allure-report.md
Labels: tech review, peer review

#2693 DOC-2930: Add doc for GCP Secret Manager support "Use credentials of a specific Harness delegate"
  docs/platform/Secrets/Secrets-Management/11-add-a-google-cloud-secret-manager.md
Labels: tech review, DO NOT MERGE

#2613 Doc-3374 public images
  docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/background-step.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/containerized-step-groups.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/run-step.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-nonroot.md
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/public-docker-images.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/resource-limits.md
  docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
  docs/feature-flags/subscribe-ff/add-a-billing-admin.md
  tutorials/security-tests/gitlab-ci-integration.md
Labels: tech review

#2448 Pushing CD FAQs
  kb/continuous-delivery/continuous-delivery-faqs.md
Labels: KB

#2540 [DOC-3028] - C# .NET Core guide
  src/components/LandingPage/data/allTutorialsData.tsx
  src/components/LandingPage/data/continuousIntegrationData.tsx
  src/components/Tutorials/ContinuousIntegrationBuildData.ts
  tutorials/ci-pipelines/build/ci-dotnet.md
  tutorials/ci-pipelines/build/ci-golang.md
  tutorials/ci-pipelines/build/ci-ios.md
  tutorials/ci-pipelines/build/ci-java-http-server.md
  tutorials/ci-pipelines/build/ci-node-docker-quickstart.md
  tutorials/ci-pipelines/build/ci-python.md
  tutorials/ci-pipelines/build/ci-ruby.md
  tutorials/ci-pipelines/ci-getting-started.md
Labels: tech review

#2707 [DOC-3501] Add SMP advanced configurations section, new external db overview topic
  docs/self-managed-enterprise-edition/advanced-configurations/_category_.json
  docs/self-managed-enterprise-edition/advanced-configurations/configure-external-databases.md
  src/components/LandingPage/data/smpData.tsx
  tutorials/self-managed-enterprise-edition/use-an-external-mongodb-database.md
  tutorials/self-managed-enterprise-edition/use-an-external-postgres-database.md
  tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
  tutorials/self-managed-enterprise-edition/use-an-external-self-managed-mongodb.md
  tutorials/self-managed-enterprise-edition/use-an-external-sm-timescaledb.md
Labels: tech review, DO NOT MERGE
