Repository harness/developer-hub, pull requests merged in 2023-05, with the labels that each got.

#1561 Update self-managed-enterprise-edition-architecture.md
  docs/self-managed-enterprise-edition/introduction/self-managed-enterprise-edition-architecture.md
Labels: tech review

#1562 remove image pramit-patch-2
  docs/self-managed-enterprise-edition/introduction/static/gcp_architecture_smpOverview.png
Labels: tech review

#1551 [DOC-3044] Combine CCM-11798 and CCM-11228 in SMP release notes
  release-notes/self-managed-enterprise-edition.md
Labels: peer review

#1570 [DOC-3058] Delete monitoring images
  docs/self-managed-enterprise-edition/monitor-self-managed-enterprise-edition/static/monitor-harness-on-prem-07.png
  docs/self-managed-enterprise-edition/monitor-self-managed-enterprise-edition/static/monitor-harness-on-prem-08.png
  docs/self-managed-enterprise-edition/monitor-self-managed-enterprise-edition/static/monitor-harness-on-prem-09.png
  docs/self-managed-enterprise-edition/monitor-self-managed-enterprise-edition/static/monitor-harness-on-prem-10.png
Labels: peer review

#1563 Update delegate-mtls-support.md
  docs/platform/2_Delegates/secure-delegates/delegate-mtls-support.md
Labels: tech review

#1571 [DOC-3056] Update SMP monitoring topic
  docs/self-managed-enterprise-edition/monitor-self-managed-enterprise-edition/monitor-harness-on-prem.md
Labels: peer review

#1564 PL release notes for 792xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#1426 CDS-56920-TAS config files
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/add-config-files.md
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/static/config-file-git.png
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/static/config-file-harness.png
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md
Labels: tech review, DO NOT MERGE

#1537 CD release notes 792xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/continuous-delivery.md
  release-notes/static/run-pipeline-form.png
  release-notes/static/select-stage-to-execute.png
  release-notes/static/selective-stage-execution.png
Labels: documentation, tech review, DO NOT MERGE

#1595 [CDS-51341] Filter support for templates
  docs/platform/13_Templates/static/template-filter-config.png
  docs/platform/13_Templates/static/template-filter-icon.png
  docs/platform/13_Templates/static/template-new-filter-settings.png
  docs/platform/13_Templates/template.md
Labels: draft

#1513 Doc 2963 tas manifest override
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/override-tanzu-manifest-and-config-files.md
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/static/config-file-override.png
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/static/manifest-override.png
Labels: tech review, DO NOT MERGE

#1584 FFM-1758: adds ff dashboard topic
  docs/feature-flags/ff-data/anonymous-users-maus.md
  docs/feature-flags/ff-data/dashboard.md
  docs/feature-flags/ff-data/static/dashboard-actions-icon.png
  docs/feature-flags/ff-data/static/dashboard-alert-icon.png
  docs/feature-flags/ff-data/static/dashboard-clone.png
  docs/feature-flags/ff-data/static/dashboard-download-chart.png
  docs/feature-flags/ff-data/static/dashboard-download-data-top1.png
  docs/feature-flags/ff-data/static/dashboard-edit.png
  docs/feature-flags/ff-data/static/dashboard-filters.png
  docs/feature-flags/ff-data/static/dashboard-flag-type-status.png
  docs/feature-flags/ff-data/static/dashboard-flags-by-user.png
  docs/feature-flags/ff-data/static/dashboard-flags-targets-by-env.png
  docs/feature-flags/ff-data/static/dashboard-flags-targets-time.png
  docs/feature-flags/ff-data/static/dashboard-sched-delivery.png
  docs/feature-flags/ff-data/static/dashboard-top.png
  docs/feature-flags/ff-data/view-activities-of-a-feature-flag.md
  docs/feature-flags/ff-data/view-metrics.md
Labels: tech review

#1596 CDS-50561-EKS infra support
  docs/platform/7_Connectors/Cloud-providers/add-a-kubernetes-cluster-connector.md
  docs/platform/7_Connectors/Cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
Labels: tech review, DO NOT MERGE

#1601 [DOC-3072] Update Delegate overview topic
  docs/platform/2_Delegates/delegate-concepts/delegate-overview.md
Labels: peer review

#1535 srm rn for 792xx
  release-notes/service-reliability-management.md
  release-notes/whats-new.md
Labels: release notes

#1603 chore: remove trailingSlash [HDH-125]
  docusaurus.config.js
Labels: DO NOT MERGE

#1602 CDS-68629-forward reference of variables
  docs/platform/12_Variables-and-Expressions/harness-variables.md
Labels: documentation, DO NOT MERGE

#1600 Cds 48450 tag infra and gitops clusters
  docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv.md
  docs/continuous-delivery/x-platform-cd-features/advanced/static/deploy-to-clusters-filter.png
  docs/continuous-delivery/x-platform-cd-features/advanced/static/deploy-to-infra-filter.png
  docs/continuous-delivery/x-platform-cd-features/advanced/static/tag-environments.png
Labels: documentation, tech review, DO NOT MERGE

#1568 CDS-56851-selective-stage=execution-using-triggers
  docs/platform/11_Triggers/selective-stage-execution-using-triggers.md
  docs/platform/11_Triggers/static/select-stage-to-execute.png
  docs/platform/11_Triggers/static/selective-stage-execution.png
  docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
Labels: tech review, DO NOT MERGE

#1232 [DOC-1235] GameDay documentation
  docs/chaos-engineering/configure-chaos-experiments/gameday/_category_.json
  docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/1-landing-page.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/10-gameday-created.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/11-start-gameday.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/12-gameday-in-progress.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/13-gameday-details.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/14-run-experiment.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/15-summary-at-exp-level.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/17-run-complete.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/2-create-new-gameday.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/3-add-experiments-to-gameday.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/4-list-experiments-from-chaoshub.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/6-add-experiments-to-gameday.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/7-add-multiple-experiments.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/8-view-exp.png
  docs/chaos-engineering/configure-chaos-experiments/gameday/static/run-gameday/9-save-experiment.png
Labels: documentation, DO NOT MERGE

#1588 Restructured 11 faults
  docs/chaos-engineering/technical-reference/chaos-faults/aws/lambda-delete-event-source-mapping.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/lambda-delete-function-concurrency.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/lambda-toggle-event-mapping-state.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/lambda-update-function-memory.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/lambda-update-function-timeout.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/lambda-update-role-permission.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/rds-instance-delete.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/rds-instance-reboot.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/lambda-delete-event-source-mapping.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/lambda-delete-function-concurrency.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/lambda-toggle-event-mapping-state.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/lambda-update-function-memory.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/lambda-update-function-timeout.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/lambda-update-role-permission.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/rds-instance-delete.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/rds-instance-reboot.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/windows-ec2-blackhole.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/windows-ec2-cpu-hog.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/windows-ec2-memory-hog.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/windows-ec2-blackhole-chaos.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/windows-ec2-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/windows-ec2-memory-hog.md
Labels: documentation

#1633 DOC-3080 TAS connector
  docs/platform/7_Connectors/Cloud-providers/add-tas-connector.md
Labels: DO NOT MERGE, peer review

#1649 CI Grab Bag - DOC-1725 , DOC-1823, DOC-2215, DOC-2401, DOC-1971, CI-4760, DOC-1732, CI-5124, DOC-1762
  docs/continuous-integration/ci-quickstarts/ci-concepts.md
  docs/continuous-integration/ci-quickstarts/ci-pipeline-basics.md
  docs/continuous-integration/migration-guides/migrating-from-circleci.md
  docs/continuous-integration/migration-guides/migrating-from-githubactions.md
  docs/continuous-integration/migration-guides/migrating-from-gitlab.md
  docs/continuous-integration/troubleshooting-ci.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-docker-hub-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
  docs/continuous-integration/use-ci/manage-dependencies/configure-service-dependency-step-settings.md
  docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/configure-run-tests-step-settings.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/viewing-tests.md
  docs/continuous-integration/use-ci/static/ci-builds-et-arc.png
  docs/continuous-integration/use-ci/static/ci-builds-et.png
  docs/continuous-integration/use-ci/use-drone-plugins/ci-jira-int-plugin.md
  docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
  docs/continuous-integration/use-ci/viewing-builds.md
  docs/getting-started/supported-platforms-and-technologies.md
  docs/platform/11_Triggers/static/trigger-pipelines-using-custom-payload-conditions-30.png
  docs/platform/11_Triggers/static/trigger-pipelines-using-custom-payload-conditions-31.png
  docs/platform/11_Triggers/trigger-pipelines-using-custom-payload-conditions.md
  docs/platform/11_Triggers/triggering-pipelines.md
  docs/platform/7_Connectors/Artifact-Repositories/connect-to-harness-container-image-registry-using-docker-connector.md
  docs/platform/7_Connectors/Cloud-providers/ref-cloud-providers/docker-registry-connector-settings-reference.md
  docs/platform/7_Connectors/create-a-connector-using-yaml.md
  docs/platform/8_Pipelines/w_pipeline-steps-reference/triggers-reference.md
  docs/platform/Resource-Development/16_APIs/api-quickstart.md
  release-notes/continuous-integration.md
  release-notes/self-managed-enterprise-edition.md
  release-notes/whats-new.md
  src/components/Certifications/data/ci-certification-developer-exam-details.md
  src/components/Certifications/data/ci-certification-developer-review-guide.md
  tutorials/cd-pipelines/unified-cicd.md
  tutorials/ci-pipelines/build/ci-container-signing.md
  tutorials/ci-pipelines/build/ci-go-containers.md
  tutorials/ci-pipelines/build/ci-java-http-server.md
  tutorials/ci-pipelines/build/ci-kubernetes-build-farm.md
  tutorials/ci-pipelines/build/ci-node-docker-quickstart.md
  tutorials/ci-pipelines/build/ci-rust-container.md
  tutorials/ci-pipelines/build/ci-tutorial-tfc-notification-trigger.md
  tutorials/security-tests/standalone-pipeline.md
  tutorials/shared/dockerhub-connector-includes.md
Labels: peer review

#1637 [PL-38229] Add auto scale using replicas topic - delegate
  docs/platform/2_Delegates/manage-delegates/auto-scale-using-replicas.md
Labels: tech review

#1673 added links to connectors
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md
Labels: documentation, DO NOT MERGE

#1677 [CI-4876] [CI-4603] [DOC-1623] [DOC-1624] [DOC-2487] Git event triggers
  client-redirects.js
  docs/continuous-integration/migration-guides/migrating-from-githubactions.md
  docs/platform/10_Git-Experience/manage-a-harness-pipeline-repo-using-git-experience.md
  docs/platform/10_Git-Experience/manage-input-sets-in-simplified-git-experience.md
  docs/platform/11_Triggers/trigger-deployments-using-custom-triggers.md
  docs/platform/11_Triggers/trigger-pipelines-using-custom-payload-conditions.md
  docs/platform/11_Triggers/triggering-pipelines.md
  docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
  docs/platform/8_Pipelines/w_pipeline-steps-reference/static/177d72e7c78be248475dbdaf4a4faa2519415049151ed88451f1be00390cd90f.png
  docs/platform/8_Pipelines/w_pipeline-steps-reference/static/752891ea2d0d9bcee2511ad039994271c20f002eb525570b5bc8038915b85da1.png
  docs/platform/8_Pipelines/w_pipeline-steps-reference/triggers-reference.md
  docs/platform/Resource-Development/19_Terraform/automate-harness-onboarding.md
  src/components/Certifications/data/cd-certification-admin-review-guide.md
  src/components/Certifications/data/cd-certification-developer-review-guide.md
  src/components/Certifications/data/ci-certification-developer-review-guide.md
  tutorials/ci-pipelines/build/ci-java-http-server.md
  tutorials/ci-pipelines/build/ci-kubernetes-build-farm.md
  tutorials/ci-pipelines/build/ci-node-docker-quickstart.md
Labels: peer review

#1695 Fixed broken links in PL topics
  docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
  docs/platform/Governance/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
Labels: bug

#1696 [CDS-69278] Moved points from top
  docs/platform/7_Connectors/Ticketing-Systems/connect-to-service-now.md
Labels: edit

#1684 DOC-2823-execution time inputs
  docs/platform/20_References/runtime-inputs.md
Labels: documentation, DO NOT MERGE

#1697 Update add-aws-connector.md
  docs/platform/7_Connectors/Cloud-providers/add-aws-connector.md
Labels: tech review

#1718 [DOC-3089] Deleted topic for CyberArk Secret Manager
  docs/first-gen/firstgen-fa-qs/harness-security-faq.md
  docs/first-gen/firstgen-platform/security/secrets-management/add-a-cyber-ark-secrets-manager.md
Labels: feature deprecated

#1700 FFM-7811: adds ff server relnotes 1.1054.0
  release-notes/feature-flags.md
Labels: DO NOT MERGE

#1703 FFM-7833: Clarify FF git sync - warn not to use old 'git management' flow
  docs/feature-flags/manage-featureflags-in-git-repos.md
  docs/feature-flags/static/gitex-connector-enable-api-access.png
  docs/feature-flags/static/gitex-setup-featureflags-01.png
  docs/feature-flags/static/gitex-setup-git-connection.png
Labels: peer review

#1672 CHAOS-1660: new topic HCE/SRM integration
  docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/create-complex-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/delete-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/edit-chaos-experiment.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/experiment-execution.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/export-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/halt-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/srm/apply-fault-to-service.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/srm/slo-details-performance.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/srm/srm-changes-dashboard.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/srm/srm-slo-dashboard.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/srm/srm-slo-filters.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
Labels: peer review

#1743 [DOC-3107] Update SMP titles for SEO
  docs/self-managed-enterprise-edition/back-up-and-recover/back-up-and-restore-helm.md
  docs/self-managed-enterprise-edition/introduction/getting-started-with-self-managed-enterprise-edition.md
  docs/self-managed-enterprise-edition/introduction/harness-self-managed-enterprise-edition-overview.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/harness-helm-chart.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/how-to-use-self-signed-certificates-with-self-managed.md
Labels: peer review

#1716 [DOC-3069] Mark as failure
  docs/platform/8_Pipelines/mark-as-failed.md
  docs/platform/8_Pipelines/static/error-summary.png
  docs/platform/8_Pipelines/static/failure strategy.png
  docs/platform/8_Pipelines/static/mark-as-failed-option.png
Labels: work in progress

#1726 [DOC-3104] - CI tutorial reorg
  client-redirects.js
  docs/continuous-integration/ci-quickstarts/ci-concepts.md
  docs/continuous-integration/ci-quickstarts/ci-pipeline-quickstart.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
  docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
  docs/platform/12_Variables-and-Expressions/harness-variables.md
  src/components/Docs/data/continuousIntegrationData.ts
  src/components/Docs/data/gettingStartedData.ts
  src/components/Docs/data/selfManagedEnterpriseEditionData.ts
  src/components/Docs/data/serviceReliabilityManagementData.ts
  src/components/LandingPage/data/allTutorialsData.tsx
  src/components/LandingPage/data/continuousIntegrationData.tsx
  src/components/Tutorials/ContinuousIntegrationBuildData.ts
  tutorials/ci-pipelines/build/ci-java-http-server.md
  tutorials/ci-pipelines/build/ci-node-docker-quickstart.md
  tutorials/ci-pipelines/build/index.md
  tutorials/ci-pipelines/ci-kubernetes-build-farm.md
  tutorials/ci-pipelines/ci-tutorial-tfc-notification-trigger.md
  tutorials/ci-pipelines/publish/index.md
  tutorials/ci-pipelines/test/ci-codecov-test.md
  tutorials/ci-pipelines/test/index.md
  tutorials/shared/ci-react-quickstart.md
  tutorials/shared/ci-rust-container.md
Labels: tech review

#1668 FFM-7741: Adds git reset procedure
  docs/feature-flags/manage-featureflags-in-git-repos.md
  docs/feature-flags/static/5-manage-featureflags-in-git-repos-04.png
  docs/feature-flags/static/5-manage-featureflags-in-git-repos-07.png
  docs/feature-flags/static/5-manage-featureflags-in-git-repos-09.png
  docs/feature-flags/static/gitex-reset-button.png
Labels: tech review

#1742 [PL-38452] Add build custom images using delegate Dockerfile topic
  docs/platform/2_Delegates/manage-delegates/build-custom-images-delegate-dockerfile.md
Labels: tech review

#1757 [PL-38837] Add rotate tokens content to secure delegates topic
  docs/platform/2_Delegates/secure-delegates/secure-delegates-with-tokens.md
  docs/platform/2_Delegates/secure-delegates/static/secure-delegates-with-tokens-02.png
  docs/platform/2_Delegates/secure-delegates/static/secure-delegates-with-tokens-03.png
Labels: peer review

#1688 CHAOS-1676: New dashboard topic
  docs/chaos-engineering/configure-chaos-experiments/experiments/dashboards.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/chaos-dashboards.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dash-actions-menu-top.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dash-alert-icon.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dash-clone-menu.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dash-exp-run-by-user.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dash-infra-by-user.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dash-tile-actions-icon.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dashboard-actions-icon.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dashboard-download-data-top1.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dashboard-edit.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/dashboards/dashboard-sched-delivery.png
Labels: DO NOT MERGE

#1777 CDS-58038-command step env variable syntax note
  docs/continuous-delivery/x-platform-cd-features/executions/cd-general-steps/download-and-copy-artifacts-using-the-command-step.md
Labels: documentation, DO NOT MERGE

#1682 Update http-step.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
Labels: documentation

#1702 CDS-46002-Spot Elastigroup deployment
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/_category_.json
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/spot-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/88aa5c64d8375bea18c47e77b218c94fae1d06e6652c984c912d795132e84e63.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/aws-elb.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/ea87f58fb9e638f26d1c0a7cefde20158f4ad3c88496b3de827121992dd0ba0a.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/spot-artifacts-ami.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/spot-basic-execution.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/spot-basic.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/spot-bg.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/spot-canary-execution.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot/static/spot-canary.png
  docs/platform/7_Connectors/Cloud-providers/add-a-spot-connector.md
Labels: documentation, tech review, DO NOT MERGE

#1762 [CDB-505] Destination options
  docs/platform/18_Dashboards/share-dashboards.md
Labels: draft

#1653 CHAOS-1657: Adds fault unit changes, updates fault interop matrix
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-cpu-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-disk-fill.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-disk-io-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-dns-error.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-dns-spoof.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-memory-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-corruption.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-duplication.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-process-kill.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-service-restart.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-time-chaos.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/shared/note-supported-os.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/images/linux-disk-fill.png
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/images/linux-disk-io-stress.png
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/images/linux-memory-stress.png
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/data-block-size.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/fill-storage-mebibytes.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/fill-storage.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-io-stress/file-system-percentage.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-io-stress/file-system-utilisation.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-io-stress/volume-mount-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-io-stress/workers.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-memory-stress/memory-percentage.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-memory-stress/memory.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-memory-stress/workers.yaml
Labels: peer review

#1827 FFM-7949: adds ruby sdk 1.1.1 relnotes
  release-notes/feature-flags.md
Labels: tech review

#1811 [PL-38899] Clarify upgrader token
  docs/platform/2_Delegates/secure-delegates/secure-delegates-with-tokens.md
Labels: tech review

#1805 [PL-38916] Update screens in Install delegates section
  docs/platform/2_Delegates/install-delegates/build-custom-delegate-images-with-third-party-tools.md
  docs/platform/2_Delegates/install-delegates/docker-delegate-to-ecs-fargate.md
  docs/platform/2_Delegates/install-delegates/enable-root-user-privileges-to-add-custom-binaries.md
  docs/platform/2_Delegates/install-delegates/static/build-custom-delegate-images-with-third-party-tools-07.png
  docs/platform/2_Delegates/install-delegates/static/build-custom-delegate-images-with-third-party-tools-08.png
Labels: tech review

#1784 CDS-58185-https-polling
  docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/static/http-polling.png
Labels: documentation, DO NOT MERGE

#1822 SRM release notes for 793xx
  release-notes/service-reliability-management.md
  release-notes/whats-new.md
Labels: edit

#1793 PL release notes 793xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#1819 Cd release notes 789xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/continuous-delivery.md
Labels: documentation, DO NOT MERGE

#1845 CD what's new and early access
  release-notes/early-access.md
  release-notes/whats-new.md
Labels: documentation

#1843 CDS-56983-added secret manager connector variables syntax
  docs/continuous-delivery/deploy-srv-diff-platforms/custom-deployments/custom-deployment-tutorial.md
Labels: documentation, DO NOT MERGE

#1685 CHAOS-1658: 0.12.x release notes
  release-notes/chaos-engineering.md
Labels: tech review

#1728 [DOC-3105] - remote debugging
  docs/continuous-integration/troubleshooting-ci.md
  docs/continuous-integration/use-ci/debug-mode.md
  docs/continuous-integration/use-ci/optimize-and-more/_category_.json
  docs/continuous-integration/use-ci/static/ci-rerun-build-in-debug-mode.png
  docs/continuous-integration/use-ci/static/debug-remote-build-links.png
  release-notes/whats-new.md
Labels: DO NOT MERGE, peer review

#1863 Cds 59511 webhook token cd rn
  release-notes/continuous-delivery.md
  release-notes/whats-new.md
Labels: documentation, DO NOT MERGE

#1839 [DOC-3143] Add cross reference to install in an air-gapped environment
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Labels: peer review

#1868 [DOC-3149] Update required delegate version number in SaaS rls notes
  release-notes/continuous-delivery.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: peer review

#1873 [PL-38538] Update delegate release notes notes, add ticket number, cross ref, fix typo
  docs/platform/2_Delegates/manage-delegates/delegate-metrics.md
  release-notes/delegate.md
Labels: peer review

#1825 FFM-7995, FFM-7961 Port Proxy docs to HDH
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/linux-chaos-infrastructure-advanced-management.md
  docs/feature-flags/relay-proxy/cache_options.md
  docs/feature-flags/relay-proxy/configuration.md
  docs/feature-flags/relay-proxy/debugging.md
  docs/feature-flags/relay-proxy/deploy-relay-proxy.md
  docs/feature-flags/relay-proxy/endpoints.md
  docs/feature-flags/relay-proxy/images/TLS.png
  docs/feature-flags/relay-proxy/images/call_flow.png
  docs/feature-flags/relay-proxy/images/load_balance.png
  docs/feature-flags/relay-proxy/images/native_tls.png
  docs/feature-flags/relay-proxy/load_balancing.md
  docs/feature-flags/relay-proxy/offline.md
  docs/feature-flags/relay-proxy/relay-proxy.md
  docs/feature-flags/relay-proxy/sample_curl_requests.md
  docs/feature-flags/relay-proxy/tls.md
  docs/feature-flags/relay-proxy/windows.md
Labels: tech review

#1887 [DOC-3155] Update arch overview diagram in delegate overview
  docs/platform/2_Delegates/delegate-concepts/delegate-overview.md
  docs/platform/2_Delegates/delegate-concepts/static/delegates-overview-00.png
  docs/platform/2_Delegates/delegate-concepts/static/harness-platform-architecture-00.png
Labels: peer review

#1853 DOC-3128 ecr gcr using docker reg
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/_category_.json
  docs/continuous-delivery/cd-infrastructure/kubernetes-infra/_category_.json
  docs/continuous-delivery/cd-infrastructure/kubernetes-infra/static/define-your-kubernetes-target-infrastructure-00.png
  docs/continuous-delivery/cd-infrastructure/terraform-infra/_category_.json
  docs/continuous-delivery/cd-infrastructure/terragrunt/_category_.json
  docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
Labels: documentation

#1844 CHAOS-1739, CHAOS-1738: Adds LCI result update retries as a new flag
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/linux-chaos-infrastructure-advanced-management.md
Labels: documentation

#1738 Pl 38504 multiple idp
  docs/platform/3_Authentication/multiple-identity-providers.md
  docs/platform/3_Authentication/static/multiple-idp-list-saml.png
  docs/platform/3_Authentication/static/multiple-idp-login.png
Labels: draft

#1908 CDS-57217-account level support for srv and env
  docs/continuous-delivery/gitops/harness-git-ops-basics.md
Labels: documentation, DO NOT MERGE

#1876 [DOC-3152] Update delegate release notes with all delegate dependent changes
  docs/first-gen/firstgen-release-notes/fg-delegate.md
  release-notes/delegate.md
Labels: peer review

#1909 CDS-54875-escaping characters
  docs/continuous-delivery/x-platform-cd-features/executions/cd-general-steps/using-shell-scripts.md
Labels: documentation, DO NOT MERGE

#1931 India bug bash
  docs/continuous-delivery/deploy-srv-diff-platforms/community-ed/harness-community-edition-overview.md
  docs/continuous-delivery/deploy-srv-diff-platforms/community-ed/harness-community-edition-quickstart.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-cd-quickstart.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-canary-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-rolling-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-infra/define-your-kubernetes-target-infrastructure.md
  docs/continuous-delivery/get-started/cd-pipeline-basics.md
  docs/continuous-delivery/get-started/cd-pipeline-modeling-overview.md
  docs/continuous-delivery/get-started/service-licensing-for-cd.md
  docs/continuous-delivery/get-started/services-and-environments-overview.md
  docs/platform/11_Triggers/trigger-on-a-new-artifact.md
Labels: documentation, DO NOT MERGE

#1901 cv verification result topics
  client-redirects.js
  docs/continuous-delivery/verify/cv-concepts/cv_ml.md
  docs/continuous-delivery/verify/cv-concepts/cv_results.md
  docs/continuous-delivery/verify/cv-results/_category_.json
  docs/continuous-delivery/verify/cv-results/apm-logs.md
  docs/continuous-delivery/verify/cv-results/interpret-log-results.md
  docs/continuous-delivery/verify/cv-results/interpret-metric-results.md
  docs/continuous-delivery/verify/cv-results/log-feedback.md
  docs/continuous-delivery/verify/cv-results/static/add-event-preference.png
  docs/continuous-delivery/verify/cv-results/static/canary-node.png
  docs/continuous-delivery/verify/cv-results/static/cv_nodes.png
  docs/continuous-delivery/verify/cv-results/static/event-details.png
  docs/continuous-delivery/verify/cv-results/static/event-preference-history.png
  docs/continuous-delivery/verify/cv-results/static/filters.png
  docs/continuous-delivery/verify/cv-results/static/last-event-preference-history.png
  docs/continuous-delivery/verify/cv-results/static/log-verification.png
  docs/continuous-delivery/verify/cv-results/static/log_cluster.png
  docs/continuous-delivery/verify/cv-results/static/metric-detailed-view.png
  docs/continuous-delivery/verify/cv-results/static/metric-failure.png
  docs/continuous-delivery/verify/cv-results/static/metrics.png
  docs/continuous-delivery/verify/cv-results/static/radar-chart.png
  docs/continuous-delivery/verify/cv-results/static/rolling-bg-node.png
  docs/continuous-delivery/verify/cv-results/static/verification-result-appd.png
  docs/continuous-delivery/verify/cv-results/static/verification_result_appd.jpg
Labels: peer review

#1922 DOC-3164 - Background step in step group
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings.md
  tutorials/ci-pipelines/test/ci-localstack-background-step.md
  tutorials/shared/java-backup.md
Labels: peer review
