Repository harness/developer-hub, pull requests merged in 2023-08, with the labels that each got.

#2713 KB Article
  kb/continuous-delivery/articles/Harness order to apply manifest resorces.md
  kb/platform/articles/API to run a pipeline with runtime inputs.md
  kb/platform/articles/Mount custom cert with delegate.md
  kb/platform/static/curl.png
  kb/platform/static/webhook.png
Labels: KB

#2712 Added Drone Faq page under CI
  kb/continuous-integration/drone-faqs.md
Labels: KB

#2692 Ci ti refresh multiple tickets - DOC-3344, DOC-3343, DOC-3444, CI-8980
  client-redirects.js
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/provision-target-deployment-infra-dynamically-with-cloud-formation.md
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/remove-provisioned-infra-with-the-cloud-formation-delete-step.md
  docs/continuous-integration/ci-quickstarts/ci-concepts.md
  docs/continuous-integration/ci-quickstarts/ci-pipeline-basics.md
  docs/continuous-integration/ci-quickstarts/hosted-builds-on-virtual-machines-quickstart.md
  docs/continuous-integration/ci-quickstarts/test-intelligence-concepts.md
  docs/continuous-integration/migration-guides/migrating-from-circleci.md
  docs/continuous-integration/migration-guides/migrating-from-githubactions.md
  docs/continuous-integration/migration-guides/migrating-from-gitlab.md
  docs/continuous-integration/shared/output-var.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/continuous-integration/use-ci/codebase-configuration/gitlfs.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-a-script-in-a-ci-stage.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/hosted-builds-on-virtual-machines-quickstart-11.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/configure-run-tests-step-settings.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/modify-and-override-build-settings-before-a-build.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/run-tests-in-ci.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/static/modify-and-override-build-settings-before-a-build-08.png
  docs/continuous-integration/use-ci/set-up-test-intelligence/static/modify-and-override-build-settings-before-a-build-09.png
  docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/viewing-tests.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
  docs/continuous-integration/use-ci/viewing-builds.md
  docs/first-gen/continuous-delivery/aws-deployments/ami-deployments/ami-canary.md
  docs/first-gen/continuous-delivery/concepts-cd/deployment-types/pivotal-cloud-foundry-deployments-overview.md
  docs/frequently-asked-questions/harness-faqs/security-testing-orchestration.md
  docs/platform/7_Connectors/Artifact-Repositories/connect-to-harness-container-image-registry-using-docker-connector.md
  docs/platform/7_Connectors/Artifact-Repositories/using-ibm-registry-to-create-a-docker-connector.md
  docs/platform/8_Pipelines/speed-up-ci-test-pipelines-using-parallelism.md
  docs/platform/Governance/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
  docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/ingest-sarif-data.md
  release-notes/continuous-integration.md
  release-notes/security-testing-orchestration.md
  release-notes/self-managed-enterprise-edition.md
  release-notes/whats-new.md
  src/components/Certifications/data/ci-certification-developer-review-guide.md
  src/components/Docs/data/continuousIntegrationData.ts
  tutorials/ci-pipelines/build/ci-java-http-server.md
  tutorials/ci-pipelines/ci-kubernetes-build-farm.md
  tutorials/ci-pipelines/publish/ci-allure-report.md
  tutorials/ci-pipelines/publish/ci-push-to-gar.md
  tutorials/ci-pipelines/test/ci-codecov-test.md
  tutorials/ci-pipelines/test/ci-fastapi-test.md
  tutorials/shared/ci-rust-container.md
  tutorials/shared/java-backup.md
  tutorials/shared/node-backup.md
Labels: peer review

#2723 CHAOS-2108: rewrites connect chaos infra
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/connect-chaos-infrastructures.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/connect-chaos-infrastructures/2.select-linux.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/connect-chaos-infrastructures/infrastructure-state.png
Labels: draft

#2695 Cds 72509 Revert PR step
  docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
  docs/continuous-delivery/gitops/static/harness-git-ops-application-set-tutorial-58.png
  docs/continuous-delivery/gitops/static/harness-git-ops-application-set-tutorial-59.png
Labels: documentation

#2577 CI-8553 - GCP, AWS, Azure vms no docker-compose
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/ci-stage-settings-vm-infra.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/define-a-ci-build-infrastructure-in-azure-16.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/define-a-ci-build-infrastructure-in-google-cloud-platform-29.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/static/set-up-an-aws-vm-build-infrastructure-12.png
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
  tutorials/platform/install-delegate.md
Labels: tech review

#2758 Moved the AIDA chatbot feature description (PL-39613) to the early ac…
  release-notes/platform.md
Labels: draft, release notes

#2727 Draft of the release notes for PL 801xx. Some items are WIP. Committi…
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: draft, release notes, DO NOT MERGE

#2703 [DOC-3497] Delegate 80104 release notes
  docs/first-gen/firstgen-release-notes/fg-delegate.md
  release-notes/delegate.md
  release-notes/early-access.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#2778 CCM - What's supported page refresh
  docs/cloud-cost-management/shared/ccm-supported-platforms.md
Labels: tech review

#2338 CV - Set baseline for load testing
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-app-dynamics.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-cloudwatch.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-custom-health-metrics.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-datadog.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-dynatrace.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-elastic-search.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-google-cloud-operations.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-loki.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-new-relic.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-prometheus.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-signalfx.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-splunk.md
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-sumologic.md
Labels: peer review

#2792 couple of small changes - CI-9087 & slack discussion
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
Labels: tech review

#2675 Ccm 13562 and ccm 13453
  docs/cloud-cost-management/3-use-ccm-cost-reporting/2-ccm-cost-categories/2-cost-categories-usage.md
  docs/frequently-asked-questions/harness-faqs/cloud-cost-management-faqs.md
  docs/frequently-asked-questions/harness-faqs/static/dashboard-time-filters.png
Labels: tech review

#2673 CloudFormation Provisioning Tutorial.
  tutorials/cd-pipelines/Provisioning/cloudformation.md
Labels: tutorial

#2843 CHAOS-2269: adds relnotes for hotfix 1.16.6 release
  release-notes/chaos-engineering.md
Labels: Waiting for Release

#2850 [DOC-3561] Delegate release notes - move deprecation notices above latest
  docs/first-gen/firstgen-release-notes/fg-delegate.md
  release-notes/delegate.md
Labels: peer review

#2851 Revert CI-8370
  client-redirects.js
  docs/platform/7_Connectors/Code-Repositories/git-hub-app-support.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md
  release-notes/continuous-integration.md
  release-notes/self-managed-enterprise-edition.md
Labels: peer review

#2416 Added the Tutorials for Approvals
  src/components/LandingPage/data/continuousDeliveryData.tsx
  tutorials/cd-pipelines/approvals.md
  tutorials/cd-pipelines/static/harness-cicd-tutorial/manualapprovalstage.png
  tutorials/cd-pipelines/static/harness-cicd-tutorial/manualapprovalstep.png
Labels: tutorial

#2806 CI RN 802xx/CI manager 53xx
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
  docs/continuous-integration/use-ci/caching-ci-data/static/cache_int_custom_key.png
  docs/continuous-integration/use-ci/caching-ci-data/static/cache_int_paths.png
  docs/continuous-integration/use-ci/caching-ci-data/static/cache_int_shared_paths.png
  docs/continuous-integration/use-ci/codebase-configuration/built-in-cie-codebase-variables-reference.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
  docs/platform/12_Variables-and-Expressions/harness-variables.md
  release-notes/continuous-integration.md
  release-notes/early-access.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#2847 CHAOS-2189: Adds chaos advanced options docs
  docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/construct-and-run-custom-chaos-experiments/advanced-options.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/construct-and-run-custom-chaos-experiments/annotations.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/construct-and-run-custom-chaos-experiments/node-selector.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/construct-and-run-custom-chaos-experiments/run-as-group.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/construct-and-run-custom-chaos-experiments/run-as-user.png
  docs/chaos-engineering/configure-chaos-experiments/experiments/static/construct-and-run-custom-chaos-experiments/toleration.png
Labels: ready to merge

#2883 DOC-3566 multiple pgsql databases topic
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
  docs/continuous-integration/use-ci/manage-dependencies/configure-service-dependency-step-settings.md
  docs/continuous-integration/use-ci/manage-dependencies/dependency-mgmt-strategies.md
  docs/continuous-integration/use-ci/manage-dependencies/multiple-postgres.md
  docs/continuous-integration/use-ci/manage-dependencies/static/background_in_parallel.png
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings.md
  docs/platform/role-based-access-control/add-manage-roles.md
  docs/platform/role-based-access-control/rbac-in-harness.md
Labels: tech review

#2900 Minor dir and filename changes
  tutorials/cd-pipelines/serverless/gcp-cloud-func.md
Labels: tutorial

#2893 [DOC-3569] Consolidate SMP what's supported
  client-redirects.js
  docs/self-managed-enterprise-edition/introduction/supported-features-and-integrations.md
  docs/self-managed-enterprise-edition/shared/smp-supported-platforms.md
  docs/self-managed-enterprise-edition/smp-supported-platforms.md
Labels: peer review

#2905 [DOC-3570] Reorg delegate yaml reference
  client-redirects.js
  docs/platform/2_Delegates/delegate-reference/YAML/_category_.json
  docs/platform/2_Delegates/delegate-reference/YAML/example-harness-delegate-yaml.md
  docs/platform/2_Delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
  docs/platform/2_Delegates/delegate-reference/YAML/sample-create-a-permanent-volume-nfs-server.md
  docs/platform/2_Delegates/delegate-reference/YAML/sample-harness-delegate-yaml-with-nfs-volume-mounted.md
  docs/platform/2_Delegates/delegate-reference/YAML/sample-kubernetes-manifest-nfs-volume.md
Labels: peer review

#2930 DOC-3574: Adding documentation for limitation related to nested json
  docs/platform/20_References/runtime-inputs.md
Labels: tech review

#2891 ci-9196 docker daemon error
  docs/continuous-integration/shared/dind-bg-gha-trbs.md
  docs/continuous-integration/troubleshoot-ci/troubleshooting-ci.md
  docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
Labels: peer review

#2330 FFM-8095: FF archiving
  docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
  docs/feature-flags/ff-creating-flag/static/archive-flag.png
  docs/feature-flags/ff-creating-flag/static/potentially-stale-flag-filter.png
Labels: Waiting for Release

#2976 DOC-3371
  .gitleaksignore
  docs/platform/8_Pipelines/searching-the-console-view.md
  docs/platform/8_Pipelines/static/console-view-preferences1.png
  docs/platform/8_Pipelines/static/console-view-preferences2.png
Labels: peer review

#2819 Added the template tutorial
  tutorials/cd-pipelines/templates.md
Labels: tutorial

#2969 Added relatable Faqs to CI
  kb/continuous-integration/continuous-integration-faqs.md
Labels: KB

#2932 PL 803xx release notes
  release-notes/platform.md
  release-notes/whats-new.md
Labels: draft, release notes, DO NOT MERGE

#2916 [DOC-2457] Add auto-population details to enable API access
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md
Labels: peer review

#2993 [DOC-1559] Add "on-prem" to SMP topic descriptions for SEO
  docs/self-managed-enterprise-edition/advanced-configurations/configure-external-databases.md
  docs/self-managed-enterprise-edition/back-up-and-restore-helm.md
  docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-infrastructure-requirements.md
  docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-kubernetes-cluster-setup.md
  docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-self-managed-add-ingress-controller-service-annotations.md
  docs/self-managed-enterprise-edition/introduction/getting-started-with-self-managed-enterprise-edition.md
  docs/self-managed-enterprise-edition/introduction/harness-self-managed-enterprise-edition-overview.md
  docs/self-managed-enterprise-edition/monitor-harness-on-prem.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/harness-helm-chart.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/how-to-use-self-signed-certificates-with-self-managed.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/manage-feature-flags.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/uninstall-helm-chart.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/upgrade-helm-chart.md
  docs/self-managed-enterprise-edition/smp-supported-platforms.md
  docs/self-managed-enterprise-edition/troubleshooting/check-mongodb-health.md
  docs/self-managed-enterprise-edition/troubleshooting/helm-install-failure.md
  docs/self-managed-enterprise-edition/troubleshooting/helm-upgrade-failure.md
  docs/self-managed-enterprise-edition/troubleshooting/license-issues.md
  docs/self-managed-enterprise-edition/troubleshooting/network-issues.md
  docs/self-managed-enterprise-edition/troubleshooting/quick-reference-to-commands.md
Labels: peer review

#2965 Updated FAQ
  kb/continuous-delivery/continuous-delivery-faqs.md
Labels: KB

#3000 file name and link change
  tutorials/cd-pipelines/kubernetes/helm-chart.md
Labels: tutorial

#2867 FFM-8982: adds ffserver 1.1079.0 relnote
  release-notes/feature-flags.md
Labels: Waiting for Release

#2990 [DOC-3600] SMP 0.8.2 patch release notes
  release-notes/self-managed-enterprise-edition.md
Labels: peer review

#3005 DOC-3607
  docs/platform/8_Pipelines/w_pipeline-steps-reference/triggers-reference.md
Labels: peer review

#2564 Doc-3245 Android guide
  src/components/LandingPage/data/continuousIntegrationData.tsx
  src/components/Tutorials/ContinuousIntegrationBuildData.ts
  tutorials/ci-pipelines/build/ci-android.md
  tutorials/ci-pipelines/build/ci-ios.md
Labels: peer review

#3017 Delegate 803xx hotfix for CDS-76795, ZD-49005
  release-notes/delegate.md
Labels: tech review

#2984 PLG-2665 Added the CLI tutorial
  tutorials/cd-pipelines/kubernetes/manifest.md
Labels: tutorial

#3066 feat: [CDS-77796]: Add Documentation around concatenation of integers with strings
  docs/platform/12_Variables-and-Expressions/harness-variables.md
Labels: DO NOT MERGE

#3088 [DOC-3619] Migrate existing delegate to mTLS
  docs/platform/2_Delegates/secure-delegates/delegate-mtls-support.md
Labels: peer review

#3104 Delegate hotfix version 80310 for CDS-75250.
  release-notes/delegate.md
Labels: release notes, DO NOT MERGE

#3133 STO 1.67.1 release notes DOC-3657
  docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
  release-notes/security-testing-orchestration.md
  release-notes/whats-new.md
Labels: DO NOT MERGE, peer review

#3039 Platform 804xx release notes
  release-notes/platform.md
  release-notes/whats-new.md
Labels: release notes, DO NOT MERGE

#3024 Added k8s-rolling deployment section
  tutorials/cd-pipelines/kubernetes/helm-chart.md
Labels: tutorial

#3143 Revert "Platform 804xx release notes"
  release-notes/platform.md
  release-notes/whats-new.md
Labels: release notes

#3148 [DOC-3647] Add HashiCorp Vault Secret Manager video overview
  docs/platform/Secrets/Secrets-Management/12-add-hashicorp-vault.md
Labels: tech review
