Repository harness/developer-hub, pull requests merged in 2023-04, with the labels that each got.

#1158 CDS-54919-Jira-update-step
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/static/add-jira-fields.png
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/static/jira-update-step.png
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/static/modify-issue-type.png
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/static/status-and-transition.png
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/static/update-issue-type.png
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/static/use-expression-in-issue-key.png
  docs/continuous-delivery/cd-advanced/ticketing-systems-category/update-jira-issues-in-cd-stages.md
Labels: documentation, tech review, DO NOT MERGE

#1164 FFM-7248: Updates to jira integration
  docs/feature-flags/ff-using-flags/integrate-feature-flag-with-jira.md
  docs/feature-flags/ff-using-flags/static/jira-add-token-from-service-account.png
  docs/feature-flags/ff-using-flags/static/jira-config1-manage-apps.png
  docs/feature-flags/ff-using-flags/static/jira-config2-config-button.png
  docs/feature-flags/ff-using-flags/static/jira-config3-ff-paste-token.png
  docs/feature-flags/ff-using-flags/static/jira-connectff-in-jira1.png
  docs/feature-flags/ff-using-flags/static/jira-connectff-in-jira2.png
  docs/feature-flags/ff-using-flags/static/jira-ff-with-jira-list.png
  docs/feature-flags/ff-using-flags/static/jira-flag-environment-dropdown.png
  docs/feature-flags/ff-using-flags/static/jira-flag-issues-section.png
  docs/feature-flags/ff-using-flags/static/jira-flag-status-2flags.png
  docs/feature-flags/ff-using-flags/static/jira-generate-token.png
  docs/feature-flags/ff-using-flags/static/jira-newflag-in-jira.png
  docs/feature-flags/ff-using-flags/static/jira-service-account.png
Labels: peer review

#816 Create helm-upgrade-failure.md
  docs/self-managed-enterprise-edition/troubleshooting/check-mongodb-health.md
  docs/self-managed-enterprise-edition/troubleshooting/helm-install-failure.md
  docs/self-managed-enterprise-edition/troubleshooting/helm-upgrade-failure.md
  docs/self-managed-enterprise-edition/troubleshooting/license-issues.md
  docs/self-managed-enterprise-edition/troubleshooting/network-issues.md
  docs/self-managed-enterprise-edition/troubleshooting/quick-reference-to-commands.md
Labels: documentation, tech review

#1214 DOC-2825: reorganizes get started left nav
  docs/feature-flags/ff-onboarding/cf-feature-flag-overview.md
  docs/feature-flags/ff-onboarding/feature-flag-best-practices.md
  docs/feature-flags/ff-onboarding/ff-getting-started/_category_.json
  docs/feature-flags/ff-onboarding/ff-getting-started/getting-started-with-feature-flags.md
  docs/feature-flags/ff-onboarding/ff-security-compliance/_category_.json
  docs/feature-flags/ff-onboarding/getting-started-with-feature-flags.md
  docs/feature-flags/ff-onboarding/java-quickstart.md
  docs/feature-flags/ff-onboarding/static/1-feature-flag-best-practices-02.png
  docs/feature-flags/ff-onboarding/static/1-feature-flag-best-practices-03.png
  docs/feature-flags/ff-onboarding/static/1-feature-flag-best-practices-04.png
  docs/feature-flags/ff-onboarding/static/2-getting-started-with-feature-flags-01.png
  docs/feature-flags/ff-onboarding/static/3-java-quickstart-00.png
  docs/feature-flags/ff-sdks/client-sdks/android-sdk-reference.md
  docs/feature-flags/ff-sdks/client-sdks/flutter-sdk-reference.md
  docs/feature-flags/ff-sdks/client-sdks/ios-sdk-reference.md
  docs/feature-flags/ff-sdks/client-sdks/java-script-sdk-references.md
  docs/feature-flags/ff-sdks/client-sdks/react-client.md
  docs/feature-flags/ff-sdks/client-sdks/react-native-sdk-reference.md
  docs/feature-flags/ff-sdks/client-sdks/xamarin-sdk-reference.md
  docs/feature-flags/ff-sdks/server-sdks/apex-sdk-reference.md
  docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference.md
  docs/feature-flags/ff-sdks/server-sdks/feature-flag-sdks-go-application.md
  docs/feature-flags/ff-sdks/server-sdks/integrate-feature-flag-with-java-sdk.md
  docs/feature-flags/ff-sdks/server-sdks/net-sdk-reference.md
  docs/feature-flags/ff-sdks/server-sdks/node-js-sdk-reference.md
  docs/feature-flags/ff-sdks/server-sdks/php-sdk-reference.md
  docs/feature-flags/ff-sdks/server-sdks/python-sdk-reference.md
  docs/feature-flags/ff-sdks/server-sdks/ruby-sdk-reference.md
  docs/getting-started/quickstarts.md
Labels: peer review

#1223 Changes
  docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/create-complex-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/delete-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/experiment-execution.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/export-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/halt-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/shared/analyze-chaos-experiment.mdx
  docs/chaos-engineering/configure-chaos-experiments/probes/validate-hypothesis-using-probes.md
  docs/chaos-engineering/get-started/static/terminologies/component-relationship.png
  docs/chaos-engineering/get-started/static/terminologies/experiment-sequence.png
  docs/chaos-engineering/get-started/terminologies.md
  docs/chaos-engineering/technical-reference/chaos-faults/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/node/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/_category_.json
  docs/chaos-engineering/technical-reference/security/introduction.md
Labels: documentation

#1245 Update GitLab tutorial
  tutorials/run-chaos-experiments/chaos-experiments-on-gitlab.md
Labels: documentation

#1113 Release notes 0.9.x
  release-notes/chaos-engineering.md
Labels: release notes

#1243 Refactor CI Tutorials
  client-redirects.js
  src/components/LandingPage/data/allTutorialsData.tsx
  src/components/LandingPage/data/continuousDeliveryData.tsx
  src/components/LandingPage/data/continuousIntegrationData.tsx
  src/components/Tutorials/ContinuousDeliveryK8SData.ts
  src/components/Tutorials/ContinuousIntegrationBuildData.ts
  src/components/Tutorials/ContinuousIntegrationPublishData.ts
  src/components/Tutorials/ContinuousIntegrationTestData.ts
  src/components/Tutorials/ContinuousIntegration_Build.tsx
  src/components/Tutorials/ContinuousIntegration_Publish.tsx
  src/components/Tutorials/ContinuousIntegration_Test.tsx
  tutorials/build-code/build/ci-java-http-server.md
  tutorials/build-code/build/ci-node-docker-quickstart.md
  tutorials/build-code/build/ci-react-quickstart.md
  tutorials/build-code/build/ci-tutorial-container-signing.md
  tutorials/build-code/build/ci-tutorial-go-containers.md
  tutorials/build-code/build/ci-tutorial-kubernetes-cluster-build-infra.md
  tutorials/build-code/build/ci-tutorial-rust-container.md
  tutorials/build-code/build/index.md
  tutorials/build-code/ci-getting-started.md
  tutorials/build-code/publish/ci-build-push-to-ecr.md
  tutorials/build-code/publish/ci-tutorial-push-to-gar.md
  tutorials/build-code/publish/index.md
  tutorials/build-code/test/ci-localstack-background-step.md
  tutorials/build-code/test/ci-publish-allure-report.md
  tutorials/build-code/test/ci-saucelabs-background-step.md
  tutorials/build-code/test/ci-tutorial-codecov-test.md
  tutorials/build-code/test/index.md
Labels: work in progress

#1261 SRM release notes for 790
  release-notes/service-reliability-management.md
  release-notes/whats-new.md
Labels: release notes, edit

#1254 CD release notes April 5
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/continuous-delivery.md
  release-notes/early-access.md
  release-notes/static/162273825052b81df3a86e5b649c38bdcf12f9175bd60cb7db872d223c2635c5.png
  release-notes/static/1b5a85ed162b70c2c13e84e1b2b5e19f1a6f1e5f4367168cd920100afde0a93a.png
  release-notes/static/40962ce702cb34f682116d48237a0b3a99d68d840ef0f6e39e4b260b79fba3dc.png
  release-notes/static/683b82e5f21fbbf21dcd1e7747eb5faa55492565b5fd75690c59229f36320324.png
  release-notes/static/6a9869b8714c6ef7316fcdc98fd5bda65f0758f5ed84a4991c4d7f3007dc5372.png
  release-notes/static/73cdc440ba09f067a25838780163b73f1afb34dc16e3fb4c625b6a84d0c295cf.png
  release-notes/static/e467e7de04d6d257e1871fad7181b65a39b7712b68826b84b7c79d849b411f04.png
  release-notes/static/e5e13558c63d546b0e9a597695b9320efe86c6306d8a08fdb052abb7e7e07b7d.png
  release-notes/static/ecc637c511be5850e704bf1db61db5cbda37d8a10ad37eb3490a05570a0b5ece.png
  release-notes/static/f01d849d1372a8d1c67dcd7532d2a3d58562fb72453328008eb617ae5df0b127.png
Labels: release notes

#1280 Remove front matter
  docs/chaos-engineering/configure-chaos-experiments/experiments/shared/analyze-chaos-experiment.md
Labels: documentation

#1103 [DOC-2814] Bugs Bash [WIP]
  docs/chaos-engineering/configure-chaos-experiments/probes/configure-and-add-probe.md
  docs/chaos-engineering/get-started/powered-by-litmus.md
  docs/chaos-engineering/technical-reference/probes/cmd-probe.md
  docs/chaos-engineering/technical-reference/probes/http-probe.md
  docs/chaos-engineering/technical-reference/probes/k8s-probe.md
  docs/chaos-engineering/technical-reference/probes/overview.md
  docs/chaos-engineering/technical-reference/probes/prom-probe.md
Labels: documentation, DO NOT MERGE

#1287 srm redirects
  client-redirects.js
Labels: edit

#1284 Updating Sumologic log configuration
  docs/continuous-delivery/cd-execution/cv-category/verify-deployments-with-sumologic.md
Labels: edit

#1264 [CI-7635] CI Background step - Entry Point field
  docs/continuous-integration/ci-technical-reference/background-step-settings.md
  docs/continuous-integration/ci-technical-reference/static/dind-background-step-entry-point.png
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/run-ci-scripts/static/dind-background-step-entry-point.png
Labels: peer review

#1311 PIE-8855-FQN names in stage-level variables
  docs/platform/12_Variables-and-Expressions/harness-variables.md
Labels: documentation, tech review, DO NOT MERGE

#1288 SPG-2501 clarify multiple paths for Report Paths
  docs/continuous-integration/ci-technical-reference/background-step-settings.md
  docs/continuous-integration/ci-technical-reference/configure-run-tests-step-settings.md
  docs/continuous-integration/ci-technical-reference/run-step-settings.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/viewing-tests.md
Labels: tech review

#1318 CDS-56646-added a new fixed issues to 78914 RN
  release-notes/continuous-delivery.md
Labels: tech review, DO NOT MERGE

#1324 [DOC-1647] - Small troubleshooting article
  docs/continuous-integration/troubleshoot/troubleshooting-ci.md
Labels: peer review

#1314 CCM-11669-cloud asset governance
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/_category_.json
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/asset-governance.md
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/cost-optimization-governance.md
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/asset-gov-enforcement.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/asset-gov-eval.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/asset-governance-rule-creation.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/asset-governance-rule-enforcement.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/asset-governance-test-output-error.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/asset-governance-valid-eval-output.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/aws-edit-json.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/aws-missing-permission-role.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/aws-select-policy.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/create-new-rule-set.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/filter-evalaution-rules.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/rule-enforcements-page.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/select-rules-enforcement.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/set-up-schedule.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/view-rule-set.png
  docs/cloud-cost-management/5-use-ccm-cost-governance/ccm-budgets/_category_.json
Labels: tech review

#1323 [DOC-2707] - CI docs landing page
  docs/continuous-integration.md
  sidebars.js
  src/components/Docs/ContinuousIntegration.tsx
  src/components/Docs/data/continuousIntegrationData.ts
Labels: peer review

#1319 Restructure Kubernetes pod level faults
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/common-tunables-for-pod-faults.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/container-kill.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/disk-fill.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-autoscaler.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-cpu-hog-exec.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-delete.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-dns-error.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-dns-spoof.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-http-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-http-modify-body.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-http-modify-header.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-http-reset-peer.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-http-status-code.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-io-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-memory-hog-exec.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-memory-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-network-corruption.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-network-duplication.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-network-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/pod-network-partition.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-memory-hog/container-runtime-and-socket-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/static/manifests/pod-memory-hog/pumba-lib.yaml
Labels: documentation, peer review

#1337 Redirects for chaos
  client-redirects.js
Labels: documentation, peer review

#1335 [DOC-2949] Add upgrader schedule note, fix typo, update formatting
  docs/platform/2_Delegates/install-delegates/delegate-upgrades-and-expiration.md
Labels: peer review

#1360 [DOC-2148] Add shell script delegate behavior details for JDK 11 changes
  docs/first-gen/firstgen-platform/account/manage-delegates/secure-delegates-with-tokens.md
Labels: peer review

#1371 FFM-7469: adds video to FF tutorial
  tutorials/feature-flags/typescript-react.md
Labels: peer review

#1364 LCI connect and disconnect
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/chaos-infrastructure-on-openshift-cluster.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/connect-chaos-infrastructures.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/connect-disconnect-linux-infrastructure.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/disconnect-chaos-infrastructure.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/linux-chaos-infrastructure-advanced-management.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/1.new-env.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/10.exp-steps.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/11.exp-execution.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/12.delete-infra.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/13.execute-command.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/2.select-linux.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/3.configure-chaos.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/4.deploy-infra.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/5.verify-infra-created.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/6.new-experiment.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/7.add-exp-details.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/8.1.select-faults.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/8.add-exp.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/linux-user-guide/9.tunables.png
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/openshift-installation/cluster-sa.yaml
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/openshift-installation/litmus-scc.yaml
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/static/openshift-installation/namespace-sa.yaml
  docs/chaos-engineering/technical-reference/architecture.md
Labels: documentation, tech review, peer review

#1386 FFM-7502: adds set evals section in JS SDK, style tweaks
  docs/feature-flags/ff-onboarding/getting-started-with-feature-flags.md
  docs/feature-flags/ff-sdks/_category_.json
  docs/feature-flags/ff-sdks/client-sdks/_category_.json
  docs/feature-flags/ff-sdks/client-sdks/java-script-sdk-references.md
  docs/feature-flags/ff-target-management/_category_.json
Labels: peer review

#1359 [DOC-2149] Add note to community edition quickstart guide upgrade
  docs/continuous-delivery/deploy-srv-diff-platforms/community-ed/harness-community-edition-quickstart.md
Labels: tech review

#1347 [DOC-2713] Landing page for Chaos
  docs/chaos-engineering.md
  docs/chaos-engineering/configure-chaos-experiments/_category_.json
  docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/_category_.json
  docs/chaos-engineering/configure-chaos-experiments/chaos-hubs/add-chaos-hub.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/_category_.json
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/connect-chaos-infrastructures.md
  docs/chaos-engineering/configure-chaos-experiments/chaos-infrastructure/disconnect-chaos-infrastructure.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/_category_.json
  docs/chaos-engineering/configure-chaos-experiments/experiments/construct-and-run-custom-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/create-complex-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/delete-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/edit-chaos-experiment.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/experiment-execution.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/export-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/experiments/halt-chaos-experiments.md
  docs/chaos-engineering/configure-chaos-experiments/prerequisites/add-a-new-user-to-a-project.md
  docs/chaos-engineering/configure-chaos-experiments/probes/configure-and-add-probe.md
  docs/chaos-engineering/configure-chaos-experiments/probes/validate-hypothesis-using-probes.md
  docs/chaos-engineering/get-started/_category_.json
  docs/chaos-engineering/get-started/introduction-to-chaos-module.md
  docs/chaos-engineering/get-started/powered-by-litmus.md
  docs/chaos-engineering/technical-reference/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/chaos-faults.md
  docs/chaos-engineering/technical-reference/probes/_category_.json
  docs/chaos-engineering/technical-reference/probes/cmd-probe.md
  docs/chaos-engineering/technical-reference/probes/http-probe.md
  docs/chaos-engineering/technical-reference/probes/k8s-probe.md
  docs/chaos-engineering/technical-reference/probes/prom-probe.md
  docs/chaos-engineering/technical-reference/security/security-templates/_category_.json
  src/components/Docs/ChaosEngineering.tsx
  src/components/Docs/data/chaosEngineeringData.ts
  src/components/Docs/data/chaosEngineeringData_Complex.ts
  src/components/LandingPage/ChaosEngineering.tsx
  tutorials/chaos-experiments/chaos-experiment-from-blank-canvas.md
  tutorials/chaos-experiments/chaos-experiments-on-gitlab.md
  tutorials/chaos-experiments/chaos-experiments-on-jenkins.md
  tutorials/chaos-experiments/first-chaos-engineering.md
Labels: documentation, peer review

#1393 [DOC-2714] PL landing page
  docs/platform.md
  sidebars.js
  src/components/Docs/Platform.tsx
  src/components/Docs/data/platformData.ts
Labels: DO NOT MERGE

#1400 Removed unwanted redirect for PL
  client-redirects.js
Labels: bug

#1383 DOC-2704-CD new landing page
  docs/continuous-delivery.md
  src/components/Docs/ContinuousDelivery.tsx
  src/components/Docs/ContinuousIntegration.tsx
  src/components/Docs/data/continuousDeliveryData.ts
  src/components/Docs/data/continuousIntegrationData.ts
  src/components/Docs/styles.module.scss
  src/components/LandingPage/TutorialCard.module.scss
  src/components/LandingPage/TutorialCard.tsx
  static/img/icon_terraform.png
Labels: documentation, DO NOT MERGE

#1397 Delegate release notes - 791xx
  docs/first-gen/firstgen-release-notes/fg-delegate.md
  release-notes/delegate.md
Labels: tech review, peer review

#1399 PL release notes for 791xx
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#1409 Update sidebar.js
  sidebars.js
Labels: documentation

#1410 update category.json
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/pod/_category_.json
Labels: documentation

#1095 Chaos-218: Added Kube Security CIS experiment documentation
  docs/chaos-engineering/technical-reference/chaos-faults/categories.tsx
  docs/chaos-engineering/technical-reference/chaos-faults/chaos-faults.md
  docs/chaos-engineering/technical-reference/chaos-faults/kube-resilience/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/load/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/experiments.ts
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/kube-security-cis.md
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/security-chaos.md
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/static/images/kube-security-cis.png
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/static/manifests/kube-security-cis/benchmark-platform.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/static/manifests/kube-security-cis/exclude-test-group-individual.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/static/manifests/kube-security-cis/kubernetes-version.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/static/manifests/kube-security-cis/sample-config.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/static/manifests/kube-security-cis/specify-test-group-individual.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/static/manifests/kube-security-cis/targets.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/_category_.json
  src/components/ChaosEngineering/utils/helper.ts
  src/components/ChaosEngineering/utils/types.ts
  static/img/chaos/security-chaos.svg
Labels: documentation

#1422 Update landing page
  docs/chaos-engineering/get-started/powered-by-litmus.md
  src/components/Docs/ChaosEngineering.tsx
  src/components/Docs/data/chaosEngineeringData.ts
  src/components/Docs/data/chaosEngineeringData_Complex.ts
Labels: documentation

#1375 [CI-7786] - Git connector settings reference
  docs/continuous-integration/troubleshoot/troubleshooting-ci.md
  docs/first-gen/firstgen-platform/account/manage-connectors/add-github-repo.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/bitbucket-connector-settings-reference.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-connector-settings-reference.md
  docs/platform/7_Connectors/Code-Repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md
Labels: peer review

#1390 DOC-54404-GitOps Agent Proxy Support
  docs/continuous-delivery/gitops/install-a-harness-git-ops-agent.md
Labels: tech review, DO NOT MERGE

#1384 DOC-2788, DOC-2792, CDS-56974, CDS-56980
  docs/continuous-delivery/manage-deployments/deployment-freeze.md
  docs/continuous-delivery/manage-deployments/static/deployment-freeze-recurrence.png
  docs/continuous-delivery/manage-deployments/static/deployment-freeze-rule.png
  docs/continuous-delivery/manage-deployments/static/deployment-freeze-schedule.png
Labels: tech review, DO NOT MERGE

#1343 [DOC-1498] CI tutorial - Build and test Java
  tutorials/ci-pipelines/build/ci-java-http-server.md
Labels: peer review

#1463 Release notes
  release-notes/chaos-engineering.md
Labels: release notes, DO NOT MERGE, peer review

#1434 srm landing page
  docs/service-reliability-management.md
  sidebars.js
  src/components/Docs/ServiceReliabilityManagement.tsx
  src/components/Docs/data/serviceReliabilityManagementData.ts
Labels: DO NOT MERGE

#1450 CDS-57043-propagate services between stage templates
  docs/continuous-delivery/x-platform-cd-features/services/propagate-and-override-cd-services.md
  docs/continuous-delivery/x-platform-cd-features/services/static/template-stage-propagation1.png
  docs/continuous-delivery/x-platform-cd-features/services/static/template-stage-propagation2.png
Labels: tech review, DO NOT MERGE

#1455 fixed title case for CD left nav
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/cloud-formation-how-tos.md
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/cloud-formation-provisioning-with-harness.md
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/provision-target-deployment-infra-dynamically-with-cloud-formation.md
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/provision-with-the-cloud-formation-create-stack-step.md
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/remove-provisioned-infra-with-the-cloud-formation-delete-step.md
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/rollback-provisioned-infra-with-the-cloud-formation-rollback-step.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/provision-infra-dynamically-with-terraform.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
  docs/continuous-delivery/deploy-srv-diff-platforms/community-ed/harness-community-edition-overview.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-canary-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-rolling-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-infra/define-your-kubernetes-target-infrastructure.md
  docs/continuous-delivery/gitops/harness-cd-git-ops-quickstart.md
  docs/continuous-delivery/gitops/harness-git-ops-basics.md
  docs/continuous-delivery/gitops/multiple-argo-to-single-harness.md
  docs/continuous-delivery/manage-deployments/control-resource-usage-with-queue-steps.md
  docs/continuous-delivery/manage-deployments/controlling-deployments-with-barriers-resource-constraints-and-queue-steps.md
  docs/continuous-delivery/manage-deployments/deployment-logs-and-limitations.md
  docs/continuous-delivery/manage-deployments/deployment-resource-constraints.md
  docs/continuous-delivery/manage-deployments/synchronize-deployments-using-barriers.md
  docs/continuous-delivery/monitor-deployments/monitor-cd-deployments.md
  docs/continuous-delivery/monitor-deployments/view-deployments-current-gen-dashboard.md
  docs/continuous-delivery/monitor-deployments/view-services-current-gen-dashboard.md
  docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/add-a-governance-policy-step-to-a-pipeline.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/flow-control/synchronize-deployments-using-barriers.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/update-service-now-tickets-in-cd-stages.md
  docs/continuous-delivery/x-platform-cd-features/executions/cd-general-steps/_category_.json
  docs/continuous-delivery/x-platform-cd-features/executions/cd-general-steps/using-shell-scripts.md
Labels: peer review

#1474 Removed Continuous Error Tracking info
  docs/service-reliability-management/getting-started/service-reliability-management-basics.md
Labels: edit

#1436 CDS-57577-CDS-54890
  docs/continuous-delivery/gitops/gitops-allowlist.md
  docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
  docs/continuous-delivery/gitops/static/gitopssync-step.png
  docs/continuous-delivery/gitops/static/sync-applications-1.png
  docs/continuous-delivery/gitops/static/sync-applications-2.png
  docs/continuous-delivery/gitops/static/sync-applications-3.png
  docs/continuous-delivery/gitops/static/sync-applications-4.png
  docs/continuous-delivery/gitops/sync-gitops-applications.md
Labels: tech review

#1484 Tech review
  release-notes/chaos-engineering.md
Labels: release notes

#1482 Added a missing video link
  docs/platform/18_Dashboards/create-dashboards.md
Labels: bug

#1435 AWS 10 experiments restructure
  docs/chaos-engineering/technical-reference/chaos-faults/aws/aws.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-http-status-code.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-io-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-memory-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-network-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-process-kill.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-stop-by-id.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-stop-by-tag.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-agent-stop.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ecs-container-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/gcp/gcp.md
  docs/chaos-engineering/technical-reference/chaos-faults/kube-resilience/kube-resilience.md
  docs/chaos-engineering/technical-reference/chaos-faults/kubernetes/kubernetes.md
  docs/chaos-engineering/technical-reference/chaos-faults/security-chaos/kube-security-cis.md
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/vmware.md
Labels: documentation

#1479 [DOC-2906] Added managed identity details for Azure Key Vault
  docs/platform/Secrets/Secrets-Management/8-azure-key-vault.md
  docs/platform/Secrets/static/specify-credentials.png
  docs/platform/Secrets/static/system-assigned-managed-identity.png
  docs/platform/Secrets/static/use-delegate-credentials.png
  docs/platform/Secrets/static/user-assigned-managed-identity.png
Labels: work in progress

#1481 CDS-59027-added inline and Harness file store options in manifest ove…
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/deploy-manifests-using-apply-step.md
Labels: tech review, DO NOT MERGE

#1486 added tutorial card
  src/components/Docs/data/continuousDeliveryData.ts
Labels: documentation, DO NOT MERGE

#1457 Updated Google Functions Gen 2 with another example
  docs/continuous-delivery/deploy-srv-diff-platforms/google/google-functions.md
Labels: documentation

#1492 [DOC-3012] Update redirects file
  client-redirects.js
Labels: bug

#1437 [SMP-1201] Add air-gapped installation topic
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/harness-helm-chart.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/how-to-use-self-signed-certificates-with-self-managed.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/static/air-gapped-environment-workflow.png
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/uninstall-helm-chart.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/upgrade-helm-chart.md
Labels: tech review, DO NOT MERGE

#1502 [DOC-3014] Apply airgap doc updates
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/static/air-gapped-environment-workflow.png
Labels: tech review, peer review

#1475 [CDS-59545] Removed QA instances from docs
  docs/first-gen/continuous-delivery/model-cd-pipeline/triggers/trigger-a-deployment-using-c-url.md
  docs/first-gen/firstgen-platform/techref-category/api/api-encrypted-files.md
  docs/platform/11_Triggers/trigger-deployments-using-custom-triggers.md
  docs/platform/2_Delegates/delegate-reference/YAML/example-harness-delegate-yaml.md
  docs/platform/2_Delegates/delegate-reference/YAML/sample-harness-delegate-yaml-with-nfs-volume-mounted.md
Labels: bug

#1411 CDS-57112-identify freeze windows for failed pipeline execution
  docs/continuous-delivery/manage-deployments/deployment-freeze.md
  docs/continuous-delivery/manage-deployments/static/view-associated-freeze-windows.png
Labels: tech review, DO NOT MERGE

#1504 Added redirects for PL links given by Kim
  client-redirects.js
Labels: bug

#1423 DOC-2583, DOC-2846, CDS-56914
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md
Labels: tech review, DO NOT MERGE

#1507 DOC-3016-runtime input support added
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md
Labels: documentation, DO NOT MERGE

#1447 [OPA-1278] GitEx for OPA
  docs/platform/Governance/14_Policy-as-code/add-a-governance-policy-step-to-a-connector.md
  docs/platform/Governance/14_Policy-as-code/add-a-governance-policy-step-to-a-pipeline.md
  docs/platform/Governance/14_Policy-as-code/add-a-policy-engine-step-to-a-secret.md
  docs/platform/Governance/14_Policy-as-code/configure-gitexperience-for-opa.md
  docs/platform/Governance/14_Policy-as-code/disable-a-policy-set.md
  docs/platform/Governance/14_Policy-as-code/harness-governance-overview.md
  docs/platform/Governance/14_Policy-as-code/harness-governance-quickstart.md
  docs/platform/Governance/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
Labels: draft

#1514 [DOC-3022] SMP release notes: remove non-RC tickets, fix typos
  release-notes/self-managed-enterprise-edition.md
Labels: peer review

#1454 chore: Adds linux disk fill docs
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-cpu-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-disk-fill.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-disk-io-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-dns-error.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-dns-spoof.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-memory-stress.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-corruption.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-duplication.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-network-loss.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-service-restart.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/linux-time-chaos.md
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/images/linux-disk-fill.png
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/data-block-size.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/fill-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/fill-percentage.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/manifests/linux-disk-fill/fill-storage-mebibytes.yaml
Labels: documentation

#1540 update figma diagram
  docs/chaos-engineering/technical-reference/chaos-faults/linux/static/images/linux-disk-fill.png
Labels: documentation

#1541 Updated 10 faults
  docs/chaos-engineering/technical-reference/chaos-faults/aws/alb-az-down.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/clb-az-down.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ebs-loss-by-id.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ebs-loss-by-tag.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-cpu-hog.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-dns-chaos.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-http-latency.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-http-modify-body.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-http-modify-header.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/ec2-http-reset-peer.md
Labels: documentation

#1524 [SMP-1220] SMP monitoring
  docs/self-managed-enterprise-edition/monitor-self-managed-enterprise-edition/monitor-harness-on-prem.md
  docs/self-managed-enterprise-edition/monitor-self-managed-enterprise-edition/static/monitor-harness-on-prem-prom1.png
  docs/self-managed-enterprise-edition/monitor-self-managed-enterprise-edition/static/monitor-harness-on-prem.png
Labels: tech review, peer review

#1539 [DOC-3037] Update SMP release notes upgrade instructions
  docs/self-managed-enterprise-edition/back-up-and-recover/_category_.json
  release-notes/self-managed-enterprise-edition.md
Labels: peer review
