Repository harness/developer-hub, pull requests merged in 2023-09, with the labels that each got.

#3192 Manually brought back the PL 804xx release notes (reverting the rever…
  release-notes/platform.md
  release-notes/whats-new.md
Labels: release notes

#3036 CD 804xx relnotes CDS-7758
  release-notes/continuous-delivery.md
Labels: DO NOT MERGE

#3217 STO release notes 2023-09-06 DOC-3688
  release-notes/security-testing-orchestration.md
Labels: DO NOT MERGE, peer review

#3213 Cds 75075 store manage argo config
  docs/continuous-delivery/gitops/connect-and-manage/_category_.json
  docs/continuous-delivery/gitops/connect-and-manage/manage-argo-configs.md
  docs/continuous-delivery/gitops/connect-and-manage/multiple-argo-to-single-harness.md
  docs/continuous-delivery/gitops/connect-and-manage/static/29bfc8656433c153505e52fd3db231902c0a4a8837b9e7dd49c436349d72aec1.png
  docs/continuous-delivery/gitops/connect-and-manage/static/33cab4c8688ebf13b142bdd87f826916afced3e1fd9120566fa2118eb2e2f43c.png
  docs/continuous-delivery/gitops/connect-and-manage/static/c42483d43b3d2464994cb0085125ba7b3b0ed10f0b5f5b901e9d31a9b66e1157.png
  docs/continuous-delivery/gitops/connect-and-manage/static/f844b3ba739e1acbab93784f9ac33945a0e820a9b15e8c958aeba5bbed9cbe26.png
Labels: documentation

#3242 Update harness-platform-faqs.md
  kb/platform/harness-platform-faqs.md
Labels: KB

#3249 2nd Sept. to 8th Sept. CI, CD faqs
  kb/continuous-delivery/continuous-delivery-faqs.md
  kb/continuous-integration/continuous-integration-faqs.md
Labels: KB

#3207 Platform 805xx release notes
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: release notes, DO NOT MERGE

#3200 update rolling deployment behavior per CDS-75488
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-app-services-quickstart.md
Labels: DO NOT MERGE

#3240 SRM - Analyze Deployment Impact
  docs/service-reliability-management/change-impact-analysis/analyze-deployment-impact.md
  docs/service-reliability-management/change-impact-analysis/static/analyze-deployment-add-step-settings.png
  docs/service-reliability-management/change-impact-analysis/static/analyze-deployment-add-step.png
  docs/service-reliability-management/change-impact-analysis/static/analyze-deployment-change-impact-report-from-ms.png
  docs/service-reliability-management/change-impact-analysis/static/analyze-deployment-change-impact-report.png
  docs/service-reliability-management/change-impact-analysis/static/analyze-deployment-impact-analysis-report.png
  docs/service-reliability-management/change-impact-analysis/static/analyze-deployment-result.png
Labels: tech review

#3315 CDS-78132: Moved troubleshooting content from the GitOps installation…
  docs/continuous-delivery/gitops/gitops-ref/troubleshooting.md
  docs/continuous-delivery/gitops/use-gitops/install-a-harness-git-ops-agent.md
Labels: documentation, draft, tech review, DO NOT MERGE, pm review

#3286 STO Snyk updates doc 2718
  docs/chaos-engineering/configure-chaos-experiments/experiments/create-complex-chaos-experiments.md
  docs/security-testing-orchestration/sto-techref-category/snyk-scanner-reference.md
  docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/snyk-scans.md
  docs/security-testing-orchestration/use-sto/static/snyk-scans-iac-00.png
  docs/security-testing-orchestration/use-sto/static/snyk-scans-iac-run-step-01.png
  docs/security-testing-orchestration/use-sto/static/snyk-scans-image-pipeline-03.png
  docs/security-testing-orchestration/use-sto/static/snyk-scans-pipeline-00.png
  docs/security-testing-orchestration/use-sto/static/snyk-scans-pipeline-orchestration-00.png
  docs/security-testing-orchestration/use-sto/static/snyk-scans-run-step-01.png
  release-notes/feature-flags.md
Labels: DO NOT MERGE, peer review

#3290 CI RN - 58xx (skip 57xx)
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  release-notes/continuous-integration.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#3389 Doc 3681
  docs/continuous-integration/get-started/ci-subscription-mgmt.md
  docs/continuous-integration/get-started/key-concepts.md
  docs/continuous-integration/migration-guides/migrating-from-githubactions.md
  docs/continuous-integration/troubleshoot-ci/debug-mode.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-nonroot.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-docker-hub-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-without-push.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-s-3-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts-to-sonatype-nexus.md
  docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
  docs/continuous-integration/use-ci/caching-ci-data/run-if-no-cache.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
  docs/continuous-integration/use-ci/codebase-configuration/built-in-cie-codebase-variables-reference.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/gitlfs.md
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
  docs/continuous-integration/use-ci/manage-dependencies/multiple-postgres.md
  docs/continuous-integration/use-ci/optimize-and-more/group-ci-steps-using-step-groups.md
  docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-docker-in-docker-in-a-ci-stage.md
  docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/ci-cluster-requirement.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/public-docker-images.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/resource-limits.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/modify-and-override-build-settings-before-a-build.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
  docs/continuous-integration/use-ci/static/harness-yaml-quickstart-21.png
  docs/continuous-integration/use-ci/use-drone-plugins/ci-bitrise-plugin.md
  docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
  docs/continuous-integration/use-ci/use-drone-plugins/custom_plugins.md
  docs/continuous-integration/use-ci/use-drone-plugins/explore-ci-plugins.md
  docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
  docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
  release-notes/continuous-integration.md
  release-notes/early-access.md
  tutorials/ci-pipelines/build/ci-dotnet.md
  tutorials/ci-pipelines/build/ci-java-http-server.md
  tutorials/ci-pipelines/build/ci-python.md
  tutorials/ci-pipelines/build/ci-ruby.md
  tutorials/ci-pipelines/ci-concepts.md
  tutorials/ci-pipelines/publish/ci-push-to-gar.md
  tutorials/ci-pipelines/publish/ci-upload-artifacts.md
Labels: peer review

#3329 FAQ - How to assert an environment variable within JEXL conditions?
  kb/continuous-integration/continuous-integration-faqs.md
Labels: KB

#3408 DOC-3720, CI-9466, CI-9410
  docs/continuous-integration/get-started/ci-subscription-mgmt.md
  docs/continuous-integration/get-started/key-concepts.md
  docs/continuous-integration/get-started/onboarding-guide.md
  docs/continuous-integration/get-started/tutorials.md
  docs/continuous-integration/use-ci/codebase-configuration/built-in-cie-codebase-variables-reference.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-subdirectory.md
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/continuous-integration/use-ci/codebase-configuration/gitlfs.md
  docs/continuous-integration/use-ci/codebase-configuration/static/disable-clone-codebase-visual.png
  docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
Labels: peer review

#3391 [DOC-3591] Note about the SHA256 digest in the value of image in the output of the Kubernetes Rollout step
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-rolling-deployment.md
Labels: bug, tech review, peer review

#3357 PL-40537 (Doc - document the notification functionalities): New content fo…
  docs/continuous-integration/use-ci/optimize-and-more/optimizing-ci-build-times.md
  docs/platform/notifications/notification-settings.md
  docs/platform/pipelines/w_pipeline-steps-reference/pipeline-settings.md
  docs/platform/settings/default-settings.md
  release-notes/platform.md
Labels: documentation, draft, tech review, pm review

#3421 Grab bag - CI & Platform
  docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/cag-aida/gen-ai-use.md
  docs/cloud-cost-management/shared/ccm-aida-overview-partial.md
  docs/continuous-integration/shared/aida-intro.md
  docs/continuous-integration/shared/aida-legal.md
  docs/continuous-integration/shared/aida-use.md
  docs/continuous-integration/troubleshoot-ci/aida.md
  docs/continuous-integration/use-ci/optimize-and-more/optimizing-ci-build-times.md
  docs/continuous-integration/use-ci/optimize-and-more/static/queue-intelligence.md
  docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
  docs/platform/Harness-AIDA/aida-ci.md
  docs/platform/Harness-AIDA/aida-overview.md
  docs/platform/Harness-AIDA/static/aida-launch-button.png
  docs/platform/delegates/install-delegates/overview.md
  docs/security-testing-orchestration/use-sto/shared/sto-aida-notes-partial.md
  docs/security-testing-orchestration/use-sto/shared/sto-aida-overview-partial.md
  docs/software-supply-chain-assurance/get-started/key-concepts.md
  kb/continuous-integration/continuous-integration-faqs.md
  release-notes/early-access.md
  release-notes/security-testing-orchestration.md
  src/components/Certifications/data/ci-certification-architect-review-guide.md
  src/components/Docs/ChaosEngineering.tsx
Labels: peer review

#3436 STO doc :: Download Images from a Private Registry topic needs clarification re scanner templates vs. Security step DOC-3759
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/download-images-from-private-registry.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/static/override-image-connector.png
Labels: DO NOT MERGE, peer review

#3443 5802 hotfix release note
  release-notes/continuous-integration.md
  release-notes/security-testing-orchestration.md
Labels: peer review

#3401 Initial 2.4.3 Release
  package.json
  yarn.lock
Labels: DO NOT MERGE

#3406 Helm chart info in service dashboards cds 73310
  docs/continuous-delivery/monitor-deployments/monitor-cd-deployments.md
  docs/continuous-delivery/monitor-deployments/static/cds-77310-chart-version-tile-callouts.png
  docs/continuous-delivery/monitor-deployments/static/cds-77310-charts-tab-callouts.png
  release-notes/continuous-delivery.md
  release-notes/early-access.md
  release-notes/static/cds-73310-environments-and-groups-tiles-callouts.png
  release-notes/static/cds-77310-chart-tab-panels.png
Labels: DO NOT MERGE, peer review

#3474 DOC-3781 (Step 8 in the CloudWatch topic is merged into step 7, so it…
  docs/continuous-delivery/verify/configure-cv/verify-deployments-with-cloudwatch.md
Labels: bug

#3468 [DOC-3777] [PL-41408] Delegate hotfix 23.09.80511
  release-notes/delegate.md
Labels: peer review

#3501 [PL-41551] Document for docker mTLS delegate
  docs/platform/delegates/secure-delegates/delegate-mtls-support.md
Labels: tech review

#3503 Cds 808xx relnotes doc 3774
  release-notes/continuous-delivery.md
  release-notes/shared/rbac-enhancements-for-opa-users.md
  release-notes/whats-new.md
Labels: DO NOT MERGE

#3512 v1 draft, NG approval variables CDS-74197
  docs/continuous-delivery/shared/jira-approval-steps.md
  docs/continuous-delivery/shared/servicenow-approval-steps.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/approvals/using-harness-approval-steps-in-cd-stages.md
  docs/platform/variables-and-expressions/harness-variables.md
  docs/platform/variables-and-expressions/static/approved-user-pipeline-example.png
Labels: DO NOT MERGE, peer review

#3495 PL 808xx release notes.
  docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
  release-notes/platform.md
  release-notes/whats-new.md
Labels: release notes

#3456 CCM - Update the SMP doc
  docs/cloud-cost-management/get-started/ccm-smp/aws-smp.md
  docs/cloud-cost-management/shared/ccm-supported-platforms.md
Labels: tech review

#3549 Governance FAQs - new topic CDS-75807
  docs/platform/governance/policy-as-code/policy-as-code-faqs.md
Labels: DO NOT MERGE, peer review

#3463 CI 59xx RN
  docs/continuous-integration/shared/aida-use.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
  docs/platform/pipelines/w_pipeline-steps-reference/step-skip-condition-settings.md
  release-notes/continuous-integration.md
  release-notes/early-access.md
  release-notes/software-supply-chain-assurance.md
  release-notes/static/ci-8932.png
  release-notes/whats-new.md
Labels: DO NOT MERGE

#3544 DOC-3763 & CI-9717
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
  docs/continuous-integration/use-ci/optimize-and-more/optimizing-ci-build-times.md
  docs/continuous-integration/use-ci/optimize-and-more/queue-intelligence.md
  docs/platform/delegates/install-delegates/overview.md
  kb/continuous-integration/continuous-integration-faqs.md
Labels: peer review
