Repository harness/developer-hub, pull requests merged in 2024-11, with the labels that each got.

#8406 CHAOS-6976 Windows network latency
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/experiments.ts
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/images/windows-network-latency.png
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/manifests/windows-network-latency/destination-hosts.yaml
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/manifests/windows-network-latency/network-latency.yaml
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/windows-network-latency.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/windows.md
Labels: DO NOT MERGE

#8464 docs: [IAC-2722]: Add STO license requirement to WIZ highlights
  docs/infra-as-code-management/pipelines/iacm-plugins/approval-step.md
  docs/infra-as-code-management/whats-supported.md
Labels: Content - gap / tech debt

#8501 docs: [IAC-2741]: Add workspace template video
  docs/infra-as-code-management/workspaces/workspace-tempates.md
Labels: Content - enhancement

#8567 docs: [IAC-2761]: IaCM PR automation rewrite
  docs/infra-as-code-management/pipelines/operations/pr-automation.md
Labels: Content - chore/cleanup

#8611 docs: [IAC-2786]: Update IaCM security doc
  docs/infra-as-code-management/iacm_security.md
Labels: Content - chore/cleanup

#8617 Add warning for deployment
  docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-web-apps-tutorial.md
Labels: Content - chore/cleanup

#8634 docs: [IAC-2760]: Add IaCM FAQ page
  docs/infra-as-code-management/faq.md
Labels: Content - enhancement

#8647 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Content - enhancement

#8137 Added AR module
  docs/artifact-registry.md
  docs/artifact-registry/_category_.json
  docs/artifact-registry/get-started/_category_.json
  docs/artifact-registry/get-started/overview.md
  docs/artifact-registry/get-started/quickstart.md
  docs/artifact-registry/get-started/static/create-proxy.png
  docs/artifact-registry/get-started/static/generate-token.png
  docs/artifact-registry/get-started/static/module-selector.png
  docs/artifact-registry/get-started/static/select-ar-module.png
  docs/artifact-registry/get-started/static/setup-client.png
  docs/artifact-registry/manage-artifacts/_category_.json
  docs/artifact-registry/manage-artifacts/artifact-details.md
  docs/artifact-registry/manage-artifacts/artifact-management.md
  docs/artifact-registry/manage-artifacts/find-artifacts.md
  docs/artifact-registry/manage-artifacts/static/artifact-overview.png
  docs/artifact-registry/manage-artifacts/static/artifacts-tab.png
  docs/artifact-registry/manage-artifacts/static/generate-token.png
  docs/artifact-registry/manage-artifacts/static/setup-client.png
  docs/artifact-registry/manage-registries/_category_.json
  docs/artifact-registry/manage-registries/configure-registry.md
  docs/artifact-registry/manage-registries/create-registry.md
  docs/artifact-registry/manage-registries/delete-registry.md
  docs/artifact-registry/manage-registries/static/create-proxy.png
  docs/artifact-registry/manage-registries/static/delete-registry-inside.png
  docs/artifact-registry/manage-registries/static/delete-registry.png
  docs/artifact-registry/manage-registries/static/set-upstream-proxy-1.png
  docs/artifact-registry/whats-supported.md
  docs/open-source/registries/whats-supported.md
  docusaurus.config.js
  sidebars.js
  src/components/Docs/ArtifactRegistry.tsx
  src/components/Docs/data/artifactRegistryData.ts
  src/components/HomepageFeatures/data/featureListData.tsx
  src/components/HomepageFeatures/styles.module.scss
  src/components/LandingPage/ArtifactRegistry.tsx
  src/components/LandingPage/TutorialCard.module.scss
  src/components/LandingPage/styles.module.scss
  src/css/custom.css
Labels: Content - enhancement

#8649 Add proper emails
  docs/artifact-registry/get-started/overview.md
  docs/artifact-registry/whats-supported.md
Labels: Content - enhancement, Content - chore/cleanup
