Repository harness/developer-hub, pull requests merged in 2024-05, with the labels that each got.

#6443 POC for an expressions reference page.
  docs/platform/variables-and-expressions/harness-expressions-reference.md
  docs/platform/variables-and-expressions/harness-variables.md
Labels: Content - enhancement

#6494 update CI and CODE codeowners
  .github/CODEOWNERS
Labels: Content - chore/cleanup

#6170 [PL-48697] SMP user profiles
  docs/self-managed-enterprise-edition/user-profiles.md
Labels: Review - SME, DO NOT MERGE

#6402 [PL-49136] SMP 0.16.0 Release Notes
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes, Review - SME

#6539 docs: [IAC-1885]: Update pr-automation doc to highlight OPA support with IACM
  docs/infra-as-code-management/workspaces/pr-automation.md
Labels: Content - gap / tech debt

#6559 Remove unsupport git provider
  docs/platform/governance/policy-as-code/configure-gitexperience-for-opa.md
Labels: Content - chore/cleanup, Content - deprecation / removal

#6505 [PL-49092] Quartz Exp is valid, while Unix Exp is invalid for the Cron
  docs/platform/authentication/single-sign-on-sso-with-ldap.md
Labels: Draft, DO NOT MERGE

#6571 Roadmap q2 update
  src/components/Roadmap/data/cdData.ts
  src/components/Roadmap/data/platformData.ts
Labels: Content - enhancement

#6525 CHAOS-5175 Guided onboarding
  docs/chaos-engineering/get-started/onboarding/guided-onboarding.md
  docs/chaos-engineering/get-started/onboarding/single-click-onboarding.md
  docs/chaos-engineering/get-started/onboarding/static/guided/add-details-discovery.png
  docs/chaos-engineering/get-started/onboarding/static/guided/choose-exp-17.png
  docs/chaos-engineering/get-started/onboarding/static/guided/confirm-2.png
  docs/chaos-engineering/get-started/onboarding/static/guided/create-map-8.png
  docs/chaos-engineering/get-started/onboarding/static/guided/created-nm-15.png
  docs/chaos-engineering/get-started/onboarding/static/guided/creating-9.png
  docs/chaos-engineering/get-started/onboarding/static/guided/delete-1.png
  docs/chaos-engineering/get-started/onboarding/static/guided/discover-services-6.png
  docs/chaos-engineering/get-started/onboarding/static/guided/discovery-complete-7.png
  docs/chaos-engineering/get-started/onboarding/static/guided/discovery.png
  docs/chaos-engineering/get-started/onboarding/static/guided/done-creating-19.png
  docs/chaos-engineering/get-started/onboarding/static/guided/edit-details-discovery.png
  docs/chaos-engineering/get-started/onboarding/static/guided/edit-dis-agent-1.png
  docs/chaos-engineering/get-started/onboarding/static/guided/list-map-10.png
  docs/chaos-engineering/get-started/onboarding/static/guided/network-map-11.png
  docs/chaos-engineering/get-started/onboarding/static/guided/new-map-12.png
  docs/chaos-engineering/get-started/onboarding/static/guided/res-score-22.png
  docs/chaos-engineering/get-started/onboarding/static/guided/run-checks-4.png
  docs/chaos-engineering/get-started/onboarding/static/guided/sample-exp-20.png
  docs/chaos-engineering/get-started/onboarding/static/guided/save-map-14.png
  docs/chaos-engineering/get-started/onboarding/static/guided/select-1.png
  docs/chaos-engineering/get-started/onboarding/static/guided/select-cluster-0.png
  docs/chaos-engineering/get-started/onboarding/static/guided/select-env-2.png
  docs/chaos-engineering/get-started/onboarding/static/guided/select-infra-3.png
  docs/chaos-engineering/get-started/onboarding/static/guided/summary-21.png
  docs/chaos-engineering/get-started/onboarding/static/guided/update-2.png
  docs/chaos-engineering/get-started/onboarding/static/guided/view-cluster-res-24.png
  docs/chaos-engineering/get-started/onboarding/static/guided/view-progress-23.png
Labels: Content - enhancement, Review - SME, Review - PM

#6544 CD 1.36.x Release Notes
  release-notes/continuous-delivery.md
Labels: Release notes, DO NOT MERGE

#6542 [PL-50606] PL 1.36.5 Release Notes
  release-notes/platform.md
Labels: Release notes, DO NOT MERGE

#6247 Cds 89396
  kb/continuous-delivery/articles/servicenow-api-permission.md
  kb/continuous-delivery/static/debug-approval-step.png
Labels: DO NOT MERGE

#6570 docs: [IAC-1920]: Add inital IaCM supported matrix page
  docs/infra-as-code-management/whats-supported.md
  docs/platform/platform-whats-supported.md
Labels: Content - gap / tech debt

#6543 [PL-50674] DEL 82900 Release Notes
  release-notes/delegate.md
Labels: Release notes

#6620 [PL-50905] SMP patch RN 0.15.3, 0.16.1
  release-notes/self-managed-enterprise-edition.md
Labels: DO NOT MERGE, Review - Editorial

#6593 Updated old images in docs
  docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
Labels: Content - chore/cleanup

#6642 fixed typo
  docs/platform/delegates/manage-delegates/hide-logs-using-regex.md
Labels: Content - chore/cleanup

#6472 [PL-46816] Update Single Sign-On (SSO) with SAML SCIM API settings details
  docs/platform/authentication/single-sign-on-saml.md
Labels: Review - SME, DO NOT MERGE

#6655 [PL-51075] SMP 0.14.8 patch RN
  release-notes/self-managed-enterprise-edition.md
Labels: Review - SME, DO NOT MERGE, Review - Editorial

#6661 Updated old docs
  docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
Labels: Content - deprecation / removal

#6680 added clarification on what the permissions are for.
  docs/platform/secrets/secrets-management/custom-secret-manager.md
Labels: Content - chore/cleanup

#6627 CD 1.37.x Release Notes
  release-notes/continuous-delivery.md
Labels: DO NOT MERGE

#6682 [PL-51141] Remove 0.14.8, add 0.14.10 patch RN
  release-notes/self-managed-enterprise-edition.md
Labels: Review - SME, DO NOT MERGE

#6628 [PL-50980] PL 1.37.6 Release Notes
  release-notes/platform.md
Labels: Release notes

#6445 editing configurations and editing rules in feature flags
  docs/feature-flags/ff-creating-flag/create-a-feature-flag.md
  docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
  docs/feature-flags/ff-creating-flag/editing-rules-and-config.md
  docs/feature-flags/ff-creating-flag/enable-or-disable-a-feature-flag.md
  docs/feature-flags/ff-creating-flag/filtering-flags-by-state.md
  docs/feature-flags/ff-creating-flag/manage-stale-flags.md
  docs/feature-flags/ff-creating-flag/manage-variations.md
  docs/feature-flags/ff-creating-flag/static/ff-editing-rules-1.png
  docs/feature-flags/ff-creating-flag/tag_management.md
  docs/feature-flags/ff-creating-flag/using-ff-ccm.md
Labels: Ready to merge

#6700 Cds 92419
  docs/platform/git-experience/configure-git-experience-for-harness-entities.md
  docs/platform/git-experience/git-experience-overview.md
  docs/platform/git-experience/gitexp-bidir-sync-setup.md
  docs/platform/git-experience/import-a-pipeline.md
  docs/platform/git-experience/import-a-template-from-git.md
  docs/platform/git-experience/import-input-sets.md
  docs/platform/git-experience/static/configure-git-experience-for-harness-entities-38.png
  docs/platform/git-experience/static/configure-git-experience-for-harness-entities-39.png
  docs/platform/git-experience/static/create-pipeline-remote-git-experience.png
  docs/platform/git-experience/static/enable-bidirectional-sync.png
  docs/platform/git-experience/static/import-inputset-from-git-menu.png
  docs/platform/git-experience/static/import-pipeline-from-git-menu.png
  docs/platform/git-experience/static/import-pipeline-from-git.png
  docs/platform/git-experience/static/import-template-from-git-menu.png
Labels: Content - enhancement

#6519 CI RN 1.26.x
  docs/continuous-integration/ci-supported-platforms.md
  release-notes/continuous-integration.md
Labels: Release notes, DO NOT MERGE

#6731 docs: [IAC-1955]: Update IaCM Pipeline Category slug
  docs/infra-as-code-management/pipelines/_category_.json
Labels: Content - gap / tech debt

#6727 docs: [IAC-1862]: IaCM Onboarding guide
  docs/infra-as-code-management/get-started/onboarding-guide.md
  docs/infra-as-code-management/get-started/static/AddApprovalStep.png
Labels: Content - gap / tech debt

#6787 feat: [CDS-97030]: update release notes for delegate hotfix 82904
  docs/platform/delegates/delegate-reference/delegate-image-version-status.md
  release-notes/delegate.md
Labels: Release notes

#6760 [PL-51352] Delegate 83001 Release Notes
  docs/platform/delegates/delegate-reference/delegate-image-version-status.md
  release-notes/delegate.md
Labels: Release notes, DO NOT MERGE

#6795 ARN role clarification
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
Labels: Content - gap / tech debt

#6794 Added new expression to expressions reference "getParentStepGroup"
  docs/platform/variables-and-expressions/harness-expressions-reference.md
Labels: Content - enhancement

#6815 docs: [IAC-1999]: Add connectors steps
  docs/infra-as-code-management/get-started/onboarding-guide.md
Labels: Content - gap / tech debt

#6839 Updated settings instructions for new UI
  docs/continuous-delivery/manage-deployments/deployment-freeze.md
Labels: Content - enhancement

#6689 [PL-46871] Account Admin: Custom resource group
  docs/platform/role-based-access-control/add-manage-roles.md
Labels: DO NOT MERGE

#6831 [PL-51473] PL 1.39.x Release Notes
  release-notes/platform.md
Labels: Draft, DO NOT MERGE

#6850 docs: [IAC-2005]: Update IaCM onboarding
  docs/infra-as-code-management/get-started/onboarding-guide.md
Labels: Content - gap / tech debt

#6825 CDS-91723
  docs/continuous-delivery/verify/cv-results/static/verification_dashboard_1.png
  docs/continuous-delivery/verify/cv-results/static/verification_dashboard_2.png
  docs/continuous-delivery/verify/cv-results/static/verification_dashboard_3.png
  docs/continuous-delivery/verify/cv-results/static/verification_dashboard_4.png
  docs/continuous-delivery/verify/cv-results/static/verification_dashboard_5.png
  docs/continuous-delivery/verify/cv-results/static/verification_dashboard_6.png
  docs/continuous-delivery/verify/cv-results/verification-dashboard.md
Labels: Content - enhancement

#6856 Pl authentication cleanup
  docs/platform/authentication/authentication-overview.md
  docs/platform/authentication/multiple-identity-providers.md
  docs/platform/authentication/single-sign-on-saml.md
  docs/platform/authentication/single-sign-on-sso-with-ldap.md
  docs/platform/authentication/single-sign-on-sso-with-oauth.md
  docs/platform/authentication/switch-account.md
  docs/platform/authentication/two-factor-authentication.md
Labels: Content - chore/cleanup

#6859 Added FAQ for GitopS RBAC permission
  docs/continuous-delivery/gitops/gitops-faqs.md
Labels: Content - gap / tech debt, Content - FAQ

#6858 Fixed broken links, removed tinyurls
  docs/continuous-delivery/deploy-srv-diff-platforms/custom/custom-deployment-tutorial.md
  docs/continuous-delivery/deploy-srv-diff-platforms/integrations/cd-integrations.md
  docs/software-engineering-insights/sei-integrations/automated-integrations/sei-github-integration.md
  docs/software-engineering-insights/sei-integrations/automated-integrations/sei-jira-integration.md
Labels: Content - chore/cleanup

#6867 rollback 1.39.4 release
  release-notes/continuous-delivery.md
Labels: Release notes
