Repository harness/developer-hub, pull requests merged in 2024-03, with the labels that each got.

#5657 (CDS-91534, ZD-54319) Delegate hotfix 24.02.82404
  release-notes/delegate.md
Labels: tech review, DO NOT MERGE

#5655 Added a new execution history reference sheet
  docs/continuous-delivery/x-platform-cd-features/executions/execution-history.md
  docs/continuous-delivery/x-platform-cd-features/executions/static/leftnav-executions-tab.png
  docs/continuous-delivery/x-platform-cd-features/executions/static/pipelinestudio-execution-history.png
  docs/continuous-delivery/x-platform-cd-features/executions/static/pipelinetab-executions.png
Labels: documentation, enhancement

#5513 Version 1.85 with new OPA policies STO-6934
  docs/platform/governance/policy-as-code/sample-policy-use-case.md
  docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/static/sto-6927-override-popup-for-snyk.png
  docs/security-testing-orchestration/use-sto/shared/security-tests-policy-samples.md
  docs/security-testing-orchestration/use-sto/static/notif-opa-policy-add-policy-set.png
  docs/security-testing-orchestration/use-sto/static/notif-opa-policy-set-enforced-yes.png
  docs/security-testing-orchestration/use-sto/static/notif-opa-select-policy.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-01-select-policy-sample.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-02-use-this-sample.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-03-configure-policy.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-04-test-terminal.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-05-test-policy-search-for-id.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-06-test-policy-succeeded.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-07-edit-test-data-for-matching-cwe.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-08-test-failed.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-09-add-policy-to-policy-set.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-10-enable-enforced.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-11-add-policy-set-to-scan-step.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/opa-go-to-account-settings.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/stop-pipelines-using-opa.md
  release-notes/early-access.md
  release-notes/security-testing-orchestration.md
Labels: tech review, DO NOT MERGE, pm review

#5437 [PL-47565] PL SMP 0.14.1 Release Notes
  release-notes/self-managed-enterprise-edition.md
Labels: work in progress, DO NOT MERGE

#5644 [PL-47879] PL 1.27.10 Release Note
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#5688 STO doc :: incorrect heading :: STO-7229
  docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
  release-notes/security-testing-orchestration.md
Labels: tech review, DO NOT MERGE

#5621 CD RN 1.27.x
  release-notes/continuous-delivery.md
Labels: documentation, draft, DO NOT MERGE

#5700 [PL-47879] Uncomment 1.27.10 PL RN
  release-notes/platform.md
Labels: DO NOT MERGE

#5697 [PL-46739] Add important change info to delegate RN
  docs/platform/shared/delegate-legacy-eos.md
  release-notes/delegate.md
  release-notes/static/old-delegate-install-exp.png
  release-notes/static/switch-to-old-delegate-install.png
Labels: tech review, DO NOT MERGE

#5702 Added docs on AWS with OIDC.
  docs/continuous-delivery/cd-integrations.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-lambda-deployments.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot-deployment.md
  docs/platform/connectors/cloud-providers/add-aws-connector.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
Labels: documentation, draft, DO NOT MERGE, Feature Flag

#5770 [PL-48063] Update SMP install with Helm client version compat info
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Labels: tech review, DO NOT MERGE

#5783 Update deploy-helm-charts.md
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/deploy-helm-charts.md
Labels: documentation, draft

#5715 App scan integration sto 7052
  docs/security-testing-orchestration/sto-techref-category/hql-appscan-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-ingestion-formats.md
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
Labels: tech review, DO NOT MERGE

#5792 SonarQube branch/PR scans STO-7251
  docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
  release-notes/security-testing-orchestration.md
Labels: tech review, DO NOT MERGE, pm review

#5698 Sysdig integration sto 6981
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-ingestion-formats.md
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
  docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scans.md
  docs/security-testing-orchestration/sto-techref-category/sysdig-scanner-reference.md
Labels: tech review, DO NOT MERGE

#5808 Update example-kubernetes-manifests-using-go-templating.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/example-kubernetes-manifests-using-go-templating.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/add-artifacts-for-kubernetes-deployments.md
  docs/first-gen/continuous-delivery/kubernetes-deployments/use-go-templating-in-kubernetes-manifests.md
Labels: bug, edit

#5835 CDS-91990-supported manifest overrides
  docs/continuous-delivery/shared/cd-integrations-supported.md
Labels: documentation

#5843 Update k8s-dry-run.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/k8s-dry-run.md
Labels: documentation

#5735 CHAOS-4557 release notes 1.32.1
  release-notes/chaos-engineering.md
Labels: release notes, DO NOT MERGE

#5758 CD-RN-1.28.x
  release-notes/continuous-delivery.md
Labels: Waiting for Release

#5752 auto-detect-target-variant doc updates STO-6880
  docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/codeql-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/coverity-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/fossa-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/mend-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/osv-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/semgrep/semgrep-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_app-instance.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_code-repo.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_container-image.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/auto-detect/_note.md
  docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/sysdig-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/trivy/aqua-trivy-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/zap/zap-scanner-reference.md
  release-notes/early-access.md
  release-notes/security-testing-orchestration.md
Labels: DO NOT MERGE, pm review

#5881 Update computing-uptime.md
  docs/harness-cloud-operations/computing-uptime.md
Labels: documentation

#5603 Added Docs for NerdGraph API in New Relic connector
  docs/continuous-delivery/cd-integrations.md
  docs/platform/connectors/monitoring-and-logging-systems/connect-to-monitoring-and-logging-systems.md
Labels: enhancement

#5918 Added Missing feature flag.
  docs/continuous-delivery/cd-integrations.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/canary-deployment-step.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-blue-green-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-canary-deployment.md
Labels: gap in docs

#5781 CDS-76419
  docs/continuous-delivery/x-platform-cd-features/environments/create-environments.md
  docs/continuous-delivery/x-platform-cd-features/environments/static/propagate-env-different-infra.png
Labels: documentation, draft, DO NOT MERGE

#5920 [PL-48336] WIP Splunk audit streaming
  docs/platform/governance/audit-trail/audit-streaming.md
Labels: work in progress, DO NOT MERGE

#5929 added JEXL exp format for custom approval step
  docs/platform/approvals/custom-approvals.md
  docs/platform/approvals/static/jexl-expression-approval-criteria.png
Labels: documentation

#5948 CDS-88825-phased deployment
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/static/asg-phased-deploy.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/static/asg-phased-execution.png
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/static/asg-setup.png
Labels: Waiting for Release

#5973 [PL-48456] SMP 0.14.4 patch release notes
  release-notes/self-managed-enterprise-edition.md
Labels: tech review, DO NOT MERGE

#5602 built-in scanners (EA) STO-6935 and 188.2 release notes STO-7037
  docs/security-testing-orchestration/sto-techref-category/built-in/_category_.json
  docs/security-testing-orchestration/sto-techref-category/built-in/containers.md
  docs/security-testing-orchestration/sto-techref-category/built-in/dast.md
  docs/security-testing-orchestration/sto-techref-category/built-in/sast.txt
  docs/security-testing-orchestration/sto-techref-category/built-in/sca.md
  docs/security-testing-orchestration/sto-techref-category/built-in/secrets.md
  docs/security-testing-orchestration/sto-techref-category/semgrep/semgrep-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/static/built-in-scan-steps.png
  docs/security-testing-orchestration/sto-techref-category/zap/zap-scanner-reference.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/set-up-baselines.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/static/baseline-regex-individual-target.png
  release-notes/early-access.md
  release-notes/security-testing-orchestration.md
  release-notes/static/built-in-scan-steps.png
Labels: tech review, DO NOT MERGE, pm review

#6016 Add troubleshooting info to BDH/Sonar scanner refs STO-7274
  docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/optimize-sto-pipelines.md
  kb/security-testing-orchestration/security-testing-orchestration-faqs.md
Labels: DO NOT MERGE

#5924 CHAOs-4765 update release notes 1.33.1
  release-notes/chaos-engineering.md
Labels: release notes, DO NOT MERGE

#5987 feat: [IDP-2512]: Added the release notes for v0.24.0
  release-notes/internal-developer-portal.md
Labels: release notes

#6024 CODE 0.75.0 rn
  docs/code-repository/pull-requests/review-pr.md
  release-notes/code-repository.md
Labels: release notes

#6025 Ci deprecated ff 22 mar 24
  docs/continuous-integration/ci-supported-platforms.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
Labels: Content - chore/cleanup, Content - deprecation / removal

#6027 CI-11768
  docs/continuous-integration/shared/build-and-push-runtime-flags.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-nonroot.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ghcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-without-push.md
  docs/continuous-integration/use-ci/caching-ci-data/docker-layer-caching.md
  docs/continuous-integration/use-ci/optimize-and-more/ci-env-var.md
  release-notes/continuous-integration.md
Labels: Content - gap / tech debt, Content - feature flag

#6037 cache intelligence policy and override configs
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
Labels: Content - gap / tech debt

#6022 CI-11814 Add MLOps tutorial to CI docs.
  docs/continuous-integration/development-guides/mlops/e2e-mlops-tutorial.md
  docs/continuous-integration/development-guides/mlops/mlops-mlflow.md
  docs/continuous-integration/development-guides/mlops/mlops-overview.md
  docs/continuous-integration/development-guides/mlops/static/architecture.png
  docs/continuous-integration/development-guides/mlops/static/artifacts-tab.png
  docs/continuous-integration/development-guides/mlops/static/connector-connectivity-status.png
  docs/continuous-integration/development-guides/mlops/static/creditcardapprovalapp.gif
  docs/continuous-integration/development-guides/mlops/static/lambda-arn.png
  docs/continuous-integration/development-guides/mlops/static/lambda-execution.png
  docs/continuous-integration/development-guides/mlops/static/lambda-function-url.png
  docs/continuous-integration/development-guides/mlops/static/s3bucketpublic.png
  docs/continuous-integration/development-guides/mlops/static/trigger-webhook.png
  docs/continuous-integration/development-guides/mlops/static/webhook-success.png
Labels: Content - tutorials

#6045 Unsupported helm v2 bug fix
  docs/continuous-delivery/shared/cd-integrations-supported.md
Labels: Content - deprecation / removal

#5965 CDS-94177
  docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
  docs/platform/variables-and-expressions/add-a-variable.md
  docs/platform/variables-and-expressions/harness-variables.md
  release-notes/continuous-delivery.md
Labels: Draft, Release notes, DO NOT MERGE

#5972 Ci rn 1 19 x
  release-notes/continuous-integration.md
Labels: Release notes

#6044 Created a KB for new permissions breaking changes
  docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/containerized-step-groups.md
  kb/continuous-delivery/articles/configuration-inheritance-stepgroup-step.md
  kb/continuous-delivery/static/RunAsRootSettings.png
Labels: Content - KB

#6062 Added missing feature flag
  kb/continuous-delivery/articles/configuration-inheritance-stepgroup-step.md
Labels: Content - chore/cleanup

#6061 Moved logic changes to early access.
  release-notes/continuous-delivery.md
Labels: Content - chore/cleanup

#6065 Ci grab bag 26 mar 24
  docs/continuous-integration/development-guides/ci-python.md
  docs/continuous-integration/development-guides/ci-ruby.md
  docs/continuous-integration/get-started/overview.md
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
  docs/continuous-integration/use-ci/run-step-settings.md
  docs/continuous-integration/use-ci/run-tests/run-tests-in-ci.md
  docs/continuous-integration/use-ci/run-tests/speed-up-ci-test-pipelines-using-parallelism.md
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-python.md
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-ruby.md
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-test-splitting.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
  docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
  docs/infra-as-code-management/workspaces/create-workspace.md
  docs/platform/pipelines/pipeline-chaining.md
  docs/security-testing-orchestration/get-started/shared/_why-define-baselines.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/set-up-baselines.md
  kb/continuous-delivery/continuous-delivery-faqs.md
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - chore/cleanup, Content - gap / tech debt

#6071 Removed <+approval> functor from non-Harness approval topics
  docs/continuous-delivery/shared/jira-approval-steps.md
  docs/continuous-delivery/shared/servicenow-approval-steps.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/approvals/using-harness-approval-steps-in-cd-stages.md
  docs/platform/variables-and-expressions/harness-variables.md
Labels: DO NOT MERGE

#6074 [PL-48563] SMP add 0.14.6 upgrade info
  release-notes/self-managed-enterprise-edition.md
Labels: Review - SME, DO NOT MERGE

#6081 Update default-settings.md
  docs/platform/settings/default-settings.md
Labels: Content - chore/cleanup

#6104 Reorg Try Harness CI
  docs/continuous-integration/get-started/tutorials.md
Labels: Content - chore/cleanup

#6109 Ci new nav doc updates
  docs/continuous-integration/get-started/ci-subscription-mgmt.md
  docs/continuous-integration/get-started/static/harness-yaml-quickstart-21.png
  docs/continuous-integration/get-started/tutorials.md
  docs/continuous-integration/shared/aida-use.md
  docs/continuous-integration/shared/subscription-add-billing-admin.md
  docs/continuous-integration/shared/subscription-cancel.md
  docs/continuous-integration/shared/subscription-create.md
  docs/continuous-integration/shared/subscription-update-billing.md
  docs/continuous-integration/shared/subscription-view-invoice.md
  docs/continuous-integration/shared/subscription-view-subscriptions.md
  docs/continuous-integration/shared/subscription-view-usage.md
  docs/continuous-integration/troubleshoot-ci/debug-mode.md
  docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/tutorial-ci-kubernetes-build-infra.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
  docs/continuous-integration/use-ci/viewing-builds.md
  kb/continuous-integration/articles/maven-settings-xml.md
Labels: Content - chore/cleanup

#6029 Wiz integration sto 6903
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-ingestion-formats.md
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
  docs/security-testing-orchestration/sto-techref-category/shared/dind-bg-step-setup.md
  docs/security-testing-orchestration/sto-techref-category/trivy/aqua-trivy-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/wiz-scanner-reference.md
  release-notes/early-access.md
  release-notes/security-testing-orchestration.md
Labels: DO NOT MERGE, Review - PM

#6009 [PL-48480] SMP 0.15.0 Release Notes
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes, Review - SME

#6088 Adding Cloud marketplace integration section
  docs/platform/get-started/cloud-marketplace-integration/_category_.json
  docs/platform/get-started/cloud-marketplace-integration/google-cloud-marketplace.md
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_create_private_offer.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_public_offer_subscribe.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_pvt_offer_activation_in_progress.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_pvt_offer_activation_inprogress.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_pvt_offer_active.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_pvt_offer_contact_sales_form.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_pvt_offer_customer_accept.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_pvt_offer_customer_accepted.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_pvt_offer_customer_email.png
  docs/platform/get-started/cloud-marketplace-integration/static/gcp_pvt_offer_pending_state.png
Labels: Review - SME, DO NOT MERGE
