Repository harness/developer-hub, pull requests merged in 2024-02, with the labels that each got.

#5222 Coverity scanner reference v0 STO-6976
  docs/security-testing-orchestration/sto-techref-category/coverity-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-ingestion-formats.md
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
  docs/security-testing-orchestration/sto-techref-category/static/coverity-ingest-pipeline.png
Labels: DO NOT MERGE

#4118 [DOC-2349] [PL-44156] Update gRPC requirement
  docs/first-gen/fg-sme/k8s/existing-cluster-kubernetes-on-prem-infrastructure-requirements.md
  docs/first-gen/fg-sme/vm/embedded-kubernetes-on-prem-infrastructure-requirements.md
  docs/first-gen/firstgen-platform/account/manage-delegates/delegate-requirements-and-limitations.md
  docs/platform/delegates/delegate-concepts/delegate-requirements.md
  docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-infrastructure-requirements.md
  docs/self-managed-enterprise-edition/deploy-with-kots/kubernetes-cluster-on-prem-kubernetes-cluster-setup.md
Labels: tech review, DO NOT MERGE

#5193 [PL-46738] SMP patch 0.13.1 release notes
  release-notes/self-managed-enterprise-edition.md
Labels: tech review, DO NOT MERGE

#5249 Release notes for 1.23.x
  release-notes/continuous-delivery.md
Labels: release notes, Waiting for Release

#5052 Update use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
Labels: DO NOT MERGE

#5200 CHAOS-4046 Release notes 1.30
  release-notes/chaos-engineering.md
Labels: release notes, Waiting for Release

#5271 [PL-46853] Correct version compatibility, clarify text
  docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration.md
Labels: tech review, DO NOT MERGE

#5139 AWS SAM configuration clarification for authentication with IRSA
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
Labels: documentation, gap in docs

#5337 [PL-46956] SMP 0.12.1, 0.13.3 patch release notes
  release-notes/self-managed-enterprise-edition.md
Labels: tech review, DO NOT MERGE

#5370 Create custom scanner images STO-7082
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/build-scan-push-workflows.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/customize-scan-image.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/download-images-from-private-registry.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/optimize-sto-pipelines.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/set-up-baselines.md
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/static/custom-image-in-registry.png
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/static/custom-image-ingestion-step.png
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/static/custom-image-run-step.png
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/static/custom-image-shared-path.png
  docs/security-testing-orchestration/use-sto/set-up-sto-pipelines/static/owasp-with-yarn-and-npm-example-pipeline.png
Labels: tech review, DO NOT MERGE, pm review

#5413 [PL-47061] Add encrypted SAML feature doc
  docs/platform/authentication/single-sign-on-saml.md
  docs/platform/authentication/static/enable-encrypted-saml.png
Labels: tech review, DO NOT MERGE

#5256 update Supported Scanners table, misc other tweaks STO-7034
  docs/security-testing-orchestration/sto-techref-category/fortify-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/security-step-ui-settings-reference.txt
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
  docs/security-testing-orchestration/sto-techref-category/tenable-scanner-reference.md
  release-notes/early-access.md
  release-notes/security-testing-orchestration.md
Labels: tech review, DO NOT MERGE

#5442 feat: [CDS-91176]: add doc for delegate hotfix 82306
  release-notes/delegate.md
Labels: tech review, DO NOT MERGE

#5460 [PL-45598] Add diagrams to external MongoDB tutorial
  tutorials/self-managed-enterprise-edition/static/mongodb-arch-1.png
  tutorials/self-managed-enterprise-edition/static/mongodb-dr-arch-1.png
  tutorials/self-managed-enterprise-edition/static/mongodb-dr-arch-2.png
  tutorials/self-managed-enterprise-edition/use-an-external-self-managed-mongodb.md
Labels: tech review, DO NOT MERGE

#5447 feat: [IDP-2063]: Initial draft for custom dashboard docs
  docs/internal-developer-portal/get-started/custom-dashboards.md
  docs/internal-developer-portal/get-started/static/catalog-dashboard.png
  docs/internal-developer-portal/get-started/static/new-nav.png
  docs/internal-developer-portal/get-started/static/old-nav.png
  docs/internal-developer-portal/get-started/static/plugins-dashboard.png
  docs/internal-developer-portal/get-started/static/scorecards-dashboard.png
  docs/internal-developer-portal/get-started/static/workflows-dashboard.png
Labels: draft, Waiting for Release

#5398 [PL-47012] PL 1.25.5 Release Notes
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#5433 DOC-3976-CD-Release-Notes-1.25.x
  release-notes/continuous-delivery.md
Labels: documentation, DO NOT MERGE

#5277 feat:[CDS-85313]: Customize repeat looping strategy step and stage name similar to that of matrix
  docs/platform/pipelines/looping-strategies/looping-strategies-matrix-repeat-and-parallelism.md
  docs/platform/pipelines/looping-strategies/static/looping_name_example_1.png
  docs/platform/pipelines/looping-strategies/static/looping_name_example_2.png
Labels: DO NOT MERGE, Waiting for Release

#5488 CHAOS-4369 Release notes 1.31.2
  release-notes/chaos-engineering.md
Labels: release notes

#5498 Traffic shifting nit fixes
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
Labels: documentation, edit

#5475 CDS-80594-kustomize-support-gitops
  docs/continuous-delivery/gitops/use-gitops/gitops-pipeline-steps.md
Labels: documentation, DO NOT MERGE

#5459 CI doc DESTINATION_CA_PATH as an advanced workflow STO-7143
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
Labels: tech review, DO NOT MERGE, peer review

#5366 [PL-44167] Add steps to reset 2fa
  docs/platform/authentication/static/reset-two-factor-authentication.png
  docs/platform/authentication/two-factor-authentication.md
Labels: tech review, DO NOT MERGE

#5541 CHAOS-4246 Update IAM integration doc
  docs/chaos-engineering/technical-reference/chaos-faults/aws/aws-iam-integration.md
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/remove-secret-refs.png
  docs/chaos-engineering/technical-reference/chaos-faults/aws/static/images/use-secret.png
Labels: documentation

#5192 GitEx support for Overrrides V2
  docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
  docs/continuous-delivery/x-platform-cd-features/static/overrides_gitex.png
  docs/continuous-delivery/x-platform-cd-features/static/remote_overrides.png
Labels: DO NOT MERGE

#5514 DOC-3985-CD RN 1.26.x
  release-notes/continuous-delivery.md
Labels: documentation, DO NOT MERGE

#5580 [PL-47785] Add minikube windows install link, clarify variable info for UI vs CLI delegate installs
  docs/platform/delegates/install-delegates/install-delegate.md
Labels: tech review, DO NOT MERGE

#5601 Integrations tab, more details
  docs/continuous-delivery/deploy-srv-diff-platforms/integrations/cd-integrations.md
Labels: edit

#5553 Added an important note about rollback in AWS SAM
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
Labels: edit

#5604 changed language for rollback
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
Labels: edit

#5629 Added example for SCCM
  docs/continuous-delivery/deploy-srv-diff-platforms/integrations/cd-integrations.md
Labels: edit

#5312 Added CD required roles to GCP connector reference
  docs/continuous-delivery/deploy-srv-diff-platforms/google-functions.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
Labels: documentation, DO NOT MERGE, Waiting for Release

#5467 misc STO backlog items STO-7006, 7003, 6983, 6975, 7153
  docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
  kb/security-testing-orchestration/security-testing-orchestration-faqs.md
Labels: DO NOT MERGE
