Repository harness/developer-hub, pull requests merged in 2024-10, with the labels that each got.

#8130 docs: [IAC-2518]: IaCM Best Practices
  kb/reference-architectures/iacm/_category_.json
  kb/reference-architectures/iacm/iacm-best-practices.md
  kb/reference-architectures/iacm/static/iacm-hierarchy-diagram.png
  src/components/ReferenceArchitectures/data/referenceArchitecture.ts
Labels: Content - enhancement, Content - gap / tech debt

#8181 docs: [IAC-2567]: Update custom images example
  docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md
Labels: Content - enhancement, Content - chore/cleanup, Content - gap / tech debt

#8165 docs: [IAC-2558]: Update reference architecture
  kb/reference-architectures/iacm/static/iacm-hierarchy-diagram.png
  src/components/ReferenceArchitectures/data/referenceArchitecture.ts
Labels: Content - chore/cleanup

#8160 add secret best practice
  docs/continuous-delivery/get-started/key-concepts.md
Labels: Content - chore/cleanup

#8192 docs: [IAC-2572]: Add OpenTofu migration link
  docs/infra-as-code-management/get-started/onboarding-guide.md
  docs/infra-as-code-management/whats-supported.md
  src/components/NavbarItems/CoveoSearch.js
Labels: Content - chore/cleanup

#8204 docs: [IAC-2575]: Add opentofu restricted network envs
  .github/CODEOWNERS
  docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md
Labels: Content - gap / tech debt

#8228 Add CI 1.49 RN.
  release-notes/continuous-integration.md
Labels: Release notes

#8194 IAC-2574 Move SMP (on-prem) to Q4 in roadmap
  src/components/Roadmap/data/iacmData.ts
Labels: Content - chore/cleanup

#8177 Add minimum required delegate version.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
  release-notes/continuous-integration.md
Labels: Content - gap / tech debt

#8257 fix dead link
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
Labels: Content - chore/cleanup

#8211 docs: [IAC-2491]: Add TF Auth approaches
  .github/CODEOWNERS
  kb/reference-architectures/iacm/iacm-best-practices.md
Labels: Content - gap / tech debt

#8287 feat: [IDP]: Added the info on mode append
  docs/internal-developer-portal/catalog/catalog-ingestion/catalog-ingestion-api.md
Labels: Blocked / On hold

#8331 docs: [IAC-2672]: Update workspace expression doc
  docs/infra-as-code-management/workspaces/workspace-expressions.md
Labels: Content - chore/cleanup, Content - gap / tech debt

#8371 docs: [IAC-2473] IaCM workspace templates
  docs/infra-as-code-management/workspaces/cost-estimation.md
  docs/infra-as-code-management/workspaces/delete-workspace.md
  docs/infra-as-code-management/workspaces/workspace-expressions.md
  docs/infra-as-code-management/workspaces/workspace-tempates.md
Labels: Content - enhancement

#8351 docs: [IAC-2642]: Document IaCM workspace CLI Integration screen
  docs/infra-as-code-management/workspaces/cli-integration.md
Labels: Content - gap / tech debt

#8427 docs: [IAC-2591]: Move network connectivity requirements
  docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md
Labels: Content - gap / tech debt

#8423 CHAOS-6910 License docs
  docs/chaos-engineering/concepts/explore-features.md
  docs/chaos-engineering/use-harness-ce/application-map.md
  docs/chaos-engineering/use-harness-ce/image-registry.md
  docs/chaos-engineering/use-harness-ce/infrastructures/infrastructures.md
  docs/chaos-engineering/use-harness-ce/license-consumption.md
  kb/chaos-engineering/chaos-engineering-faq.md
  src/components/Docs/data/chaosEngineeringData.ts
  src/components/Docs/data/chaosEngineeringData_Complex.ts
Labels: DO NOT MERGE, Review - PM

#8425 docs: [IAC-2700]: Add delegate pre-req for module registry
  docs/infra-as-code-management/module-registry.md
Labels: Content - gap / tech debt
