Repository harness/developer-hub, pull requests merged in 2024-01, with the labels that each got.

#4690 [PL-43739] Platform 1.17.8, Delegate 82000 release notes
  release-notes/delegate.md
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#4752 fix: [CDS-76667]:Add in FAQs that GitEx is supported for services, environment and infrastructure definitions
  docs/faqs/git-exp-vs-config-as-code.md
  docs/platform/git-experience/git-experience-overview.md
  docs/platform/git-experience/manage-services-using-git-experience.md
  docs/platform/git-experience/static/Gitex_service.png
  docs/platform/git-experience/static/branch_switching.png
  docs/platform/git-experience/static/branches_adding_services.png
  docs/platform/git-experience/static/inline_to_remote.png
  docs/platform/git-experience/static/save_service_config.png
  docs/platform/git-experience/static/service_remote_git.png
  docs/platform/git-experience/static/stage_service_settings.png
  docs/platform/git-experience/static/template.png
  docs/platform/git-experience/static/template_2.png
Labels: DO NOT MERGE

#4783 feat: [CDS-87714]: Add Docs for GitEx support for environment and Infrastructure Definition
  docs/platform/git-experience/manage-environments-infra-definitions.md
  docs/platform/git-experience/static/branch-switching-environment.png
  docs/platform/git-experience/static/env_branch_switching_remote.png
  docs/platform/git-experience/static/env_move_to_git.png
  docs/platform/git-experience/static/env_pipeline_remote.png
  docs/platform/git-experience/static/environment-settings.png
  docs/platform/git-experience/static/envrionment.png
  docs/platform/git-experience/static/infra_Def1.png
  docs/platform/git-experience/static/infra_def_2.png
  docs/platform/git-experience/static/infra_def_edit.png
  docs/platform/git-experience/static/infra_move_git.png
  docs/platform/git-experience/static/specify_env_remote.png
  docs/platform/git-experience/static/yaml_path.png
Labels: DO NOT MERGE

#4486 Code-1180
  docs/code-repository/code-supported.md
  docs/code-repository/config-repos/delete-repo.md
  docs/code-repository/config-repos/rules.md
  docs/code-repository/pipelines/code-triggers.md
  docs/code-repository/pipelines/codebase-from-harness-code.md
  docs/code-repository/pull-requests/merge-pr.md
  docs/code-repository/pull-requests/review-pr.md
  docs/code-repository/work-in-repos/keyword-search.md
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/ci-stage-settings.md
  docusaurus.config.js
  release-notes/code-repository.md
  release-notes/continuous-delivery.md
  release-notes/continuous-error-tracking.md
  release-notes/continuous-integration.md
  release-notes/early-access.md
  release-notes/feature-flags.md
  release-notes/internal-developer-portal.md
  release-notes/security-testing-orchestration.md
  release-notes/self-managed-enterprise-edition.md
  release-notes/service-reliability-management.md
  release-notes/software-supply-chain-assurance.md
  sidebars-release-notes.js
  src/components/Docs/data/codeRepositoryData.tsx
  src/components/ReleaseNotes/data/releaseNotesData.ts
Labels: DO NOT MERGE

#4547 DOC 3214 SSH chaos
  docs/chaos-engineering/technical-reference/chaos-faults/categories.tsx
  docs/chaos-engineering/technical-reference/chaos-faults/chaos-faults.md
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/experiments.ts
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/prerequisites.md
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/ssh-chaos.md
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/ssh.md
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/static/images/ssh-chaos/chaos-parameter.png
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/static/images/ssh-chaos/customize-env.png
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/static/images/ssh-chaos/ssh-chaos.png
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/static/manifests/ssh-chaos/abort-parameter.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/static/manifests/ssh-chaos/abort-script-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/static/manifests/ssh-chaos/chaos-parameter.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/ssh/static/manifests/ssh-chaos/chaos-script-path.yaml
  docs/chaos-engineering/technical-reference/chaos-faults/vmware/_category_.json
  docs/chaos-engineering/technical-reference/chaos-faults/windows/_category_.json
  src/components/ChaosEngineering/utils/helper.ts
  src/components/ChaosEngineering/utils/types.ts
  src/components/Docs/data/chaosEngineeringData.ts
  src/components/Docs/data/chaosEngineeringData_Complex.ts
  static/img/chaos/ssh.svg
Labels: work in progress, DO NOT MERGE, peer review

#4755 feat:[CDS-79028]: docs for harness approval notification improvement phase 1
  docs/platform/approvals/adding-harness-approval-stages.md
  docs/platform/approvals/static/adding-harness-approval-stages-21.png
  docs/platform/approvals/static/adding-harness-approval-stages-22.png
Labels: DO NOT MERGE

#4827 CD RN for Jan 2024 Version 1.19.6
  release-notes/continuous-delivery.md
  release-notes/static/78b4f649d9c4a9d0d858499e9508e846095f643d22b5f64dae60d6a30037b8cd.png
  release-notes/static/fedb79c8b5740f96280530b92d761ba52babb5c15336acbc713793d9687a1b97.png
Labels: release notes, DO NOT MERGE

#4792 [PL-43856] Platform 1.19.6 release notes
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#4878 STO relnotes 2024-01-09 STO-6938
  release-notes/security-testing-orchestration.md
Labels: tech review, DO NOT MERGE

#4244 [SMP-2308] [SMP-2363] SMP Self-Managed Amazon ElastiCache Redis database tutorial
  src/components/LandingPage/data/smpData.tsx
  tutorials/self-managed-enterprise-edition/use-aws-elasticache.md
Labels: tech review, DO NOT MERGE

#4862 [SMP-2386] SMP customer reference architectures
  docs/self-managed-enterprise-edition/advanced-configurations/configure-external-databases.md
  docs/self-managed-enterprise-edition/advanced-configurations/increase-pv-size-statefulsets.md
  docs/self-managed-enterprise-edition/advanced-configurations/reference-architecture.md
  docs/self-managed-enterprise-edition/advanced-configurations/static/smp-ref-arch-dt.png
  docs/self-managed-enterprise-edition/advanced-configurations/use-external-secrets-for-license-values.md
Labels: tech review, DO NOT MERGE

#4109 fix gitops appset docs
  docs/continuous-delivery/gitops/applicationsets/appset-basics.md
  docs/continuous-delivery/gitops/applicationsets/harness-git-ops-application-set-tutorial.md
Labels: work in progress

#4876 add orchestration settings STO-6877
  docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
Labels: tech review, DO NOT MERGE

#4745 add supported ingestion formats STO-6698
  docs/security-testing-orchestration/sto-techref-category/openvas-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference.md
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-ingestion-formats.md
  docs/security-testing-orchestration/whats-supported.md
Labels: tech review, DO NOT MERGE

#4854 Release notes 1.28.1
  release-notes/chaos-engineering.md
Labels: release notes

#4890 [PL-41689]: Add documentation for absolute session timeout
  docs/platform/authentication/authentication-overview.md
  docs/platform/authentication/static/SessionTimeout.png
Labels: tech review, DO NOT MERGE

#4621 DOC-3942 Probe acceptance criteria [WIP]
  docs/chaos-engineering/technical-reference/probes/cmd-probe.md
  docs/chaos-engineering/technical-reference/probes/datadog-probe.md
  docs/chaos-engineering/technical-reference/probes/http-probe.md
  docs/chaos-engineering/technical-reference/probes/k8s-probe.md
  docs/chaos-engineering/technical-reference/probes/overview.md
  docs/chaos-engineering/technical-reference/probes/probe-acceptance-criteria.md
  docs/chaos-engineering/technical-reference/probes/prom-probe.md
  docs/chaos-engineering/technical-reference/probes/slo-probe.md
  docs/chaos-engineering/technical-reference/probes/static/probe-acceptance/choose-experiment.png
  docs/chaos-engineering/technical-reference/probes/static/probe-acceptance/edit-1.png
  docs/chaos-engineering/technical-reference/probes/static/probe-acceptance/edit-2.png
  docs/chaos-engineering/technical-reference/probes/static/probe-acceptance/edit-3.png
  docs/chaos-engineering/technical-reference/probes/static/probe-acceptance/edit-4.png
  docs/chaos-engineering/technical-reference/probes/static/probe-acceptance/edit-probe.png
  docs/chaos-engineering/technical-reference/probes/static/probe-acceptance/navigate.png
  docs/chaos-engineering/technical-reference/probes/static/probe-acceptance/select-type.png
Labels: enhancement, tech review, DO NOT MERGE

#4896 Release notes for 1.20.9 release
  release-notes/continuous-delivery.md
Labels: release notes, DO NOT MERGE, Waiting for Release

#4929 Update custom-deployment-tutorial.md
  docs/continuous-delivery/deploy-srv-diff-platforms/custom-deployment-tutorial.md
Labels: documentation, DO NOT MERGE

#4998 Add 1.29.0 release notes
  release-notes/chaos-engineering.md
Labels: release notes, peer review, Waiting for Release

#4955 [PL-44116] PL 1.21.5 release notes
  release-notes/platform.md
Labels: tech review

#4968 Release notes for 1.21.0 release
  release-notes/continuous-delivery.md
Labels: release notes

#4981 [DOC-3902] [PL-44174] Update key concepts
  docs/get-started/key-concepts.md
  docs/get-started/static/learn-harness-key-concepts-05.png
  docs/get-started/static/learn-harness-key-concepts-06.png
  docs/get-started/static/pipeline_visual.png
  docs/get-started/static/pipeline_yaml.png
Labels: DO NOT MERGE

#5078 Add future roadmap for CD
  src/components/Roadmap/data/cdData.ts
  src/components/Roadmap/data/platformData.ts
  src/components/Roadmap/data/roadmapData.ts
  src/components/Roadmap/index.tsx
Labels: DO NOT MERGE

#5072 Anchore scanner reference updates STO-7013
  docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-scanners.md
Labels: tech review, DO NOT MERGE

#5118 Update PL RN with issues discovered during SMP RN process
  release-notes/platform.md
Labels: tech review, DO NOT MERGE

#5117 add delegate 24.01.82108 RN
  release-notes/delegate.md
Labels: tech review, DO NOT MERGE

#5119 [PL-46605] Delegate 24.01.82202 release notes
  release-notes/delegate.md
Labels: tech review, DO NOT MERGE

#5166 Update hide-logs-using-regex.md
  docs/platform/delegates/manage-delegates/hide-logs-using-regex.md
Labels: tech review, DO NOT MERGE

#5099 Release notes for 1.22.0
  release-notes/continuous-delivery.md
Labels: release notes, DO NOT MERGE

#5138 Auto detect targets variants v2 STO-6974
  docs/security-testing-orchestration/sto-techref-category/aa_step-palette-scanner-reference.TEMPLATE.v2.txt
  docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/aqua-trivy-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/aws-security-hub-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/codeql-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/custom-ingest-reference.md
  docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/mend-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/nessus-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/prowler-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/semgrep-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/shared/_zz-step-palette-scanner-reference.TEMPLATE.txt
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/_auto-detect.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/target/_name.md
  docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/zap-scanner-reference.md
Labels: DO NOT MERGE

#4843 add early access 1.19.6 feature (PL-42471)
  docs/platform/delegates/delegate-concepts/delegate-registration.md
Labels: tech review, DO NOT MERGE

#5141 [PL-46590] PL 1.22.3 release notes
  release-notes/platform.md
Labels: tech review

#5028 [PL-46419] SMP 0.13.0 release notes
  release-notes/self-managed-enterprise-edition.md
Labels: tech review

#5168 [PL-46627] Update AIDA dashboard intelligence
  docs/platform/Harness-AIDA/aida-overview.md
  docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
Labels: tech review, DO NOT MERGE
