Repository harness/developer-hub, pull requests merged in 2024-09, with the labels that each got.

#7574 CHAOS-6233 FIS Generic experiment template docs
  docs/chaos-engineering/chaos-faults/aws/aws.md
  docs/chaos-engineering/chaos-faults/aws/dynamodb-replication-pause.md
  docs/chaos-engineering/chaos-faults/aws/experiments.ts
  docs/chaos-engineering/chaos-faults/aws/generic-experiment-template.md
  docs/chaos-engineering/chaos-faults/aws/static/images/dynamodb-replication-pause.png
  docs/chaos-engineering/chaos-faults/aws/static/images/generic-experiment-template.png
  docs/chaos-engineering/chaos-faults/aws/static/manifests/dynamodb-replication-pause/count.yaml
  docs/chaos-engineering/chaos-faults/aws/static/manifests/dynamodb-replication-pause/fis-details.yaml
  docs/chaos-engineering/chaos-faults/aws/static/manifests/dynamodb-replication-pause/stop-conditions.yaml
  docs/chaos-engineering/chaos-faults/aws/static/manifests/dynamodb-replication-pause/table-names.yaml
  docs/chaos-engineering/chaos-faults/aws/static/manifests/generic-experiment-template/experiment-template-id.yaml
  docs/chaos-engineering/get-started/powered-by-litmus.md
Labels: Content - enhancement

#7884 docs: [IAC-2437]: Update plan command support info
  docs/infra-as-code-management/pipelines/iacm-plugins/terraform-plugins.md
Labels: Content - enhancement

#7831 Deprioritize the CLI in tabs
  docs/continuous-delivery/get-started/cd-tutorials/aws-lambda.md
  docs/continuous-delivery/get-started/cd-tutorials/gcp-cloud-func.md
  docs/continuous-delivery/get-started/cd-tutorials/helm-chart.md
  docs/continuous-delivery/get-started/cd-tutorials/kustomize.md
  docs/continuous-delivery/get-started/cd-tutorials/manifest.md
  docs/continuous-delivery/get-started/cd-tutorials/ownapp.md
Labels: Content - deprecation / removal

#7886 Add troubleshooting notes for cert issues with vanity URLs.
  docs/platform/delegates/troubleshooting/certificate-issues.md
Labels: Content - chore/cleanup, Content - gap / tech debt

#7918 docs: [IAC_2470]: Add workspace expression migration guide
  docs/infra-as-code-management/workspaces/workspace-expressions.md
Labels: Content - enhancement, Content - gap / tech debt

#7946 [PL-56994]: PL 1.56.x Release Notes
  release-notes/platform.md
Labels: DO NOT MERGE

#7963 Add best practice
  docs/continuous-delivery/get-started/key-concepts.md
Labels: Content - chore/cleanup

#7962 Update image
  docs/continuous-delivery/gitops/use-gitops/static/gitopssync-step.png
Labels: Content - chore/cleanup

#7943 Canonical URL updates HDH-320
  docs/continuous-delivery/cd-infrastructure/aws-cdk.md
  docs/continuous-delivery/cd-infrastructure/azure-arm-provisioning.md
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/cloud-formation-provisioning-with-harness.md
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/provision-target-deployment-infra-dynamically-with-cloud-formation.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-provisioning-with-harness.md
  docs/continuous-delivery/deploy-srv-diff-platforms/custom/custom-deployment-tutorial.md
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/native-helm-quickstart.md
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/use-a-local-helm-chart.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/canary-deployment-step.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/example-kubernetes-manifests-using-go-templating.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollback.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/using-open-shift-with-harness-kubernetes.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/add-artifacts-for-kubernetes-deployments.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-kubernetes-category/prune-kubernetes-resources.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/delete-kubernetes-resources.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/deploy-manifests-using-apply-step.md
  docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-deployment-faqs.md
  docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/add-bg-with-configurable-amount-of-tanzu.md
  docs/continuous-delivery/get-started/cd-tutorials/aws.md
  docs/continuous-delivery/get-started/cd-tutorials/cosign-opa.md
  docs/continuous-delivery/get-started/cd-tutorials/ownapp.md
  docs/continuous-delivery/gitops/connect-and-manage/external-secrets-integration.md
  docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
  docs/continuous-delivery/gitops/connect-and-manage/multiple-argo-to-single-harness.md
  docs/continuous-delivery/gitops/connect-and-manage/use-argo-rollouts.md
  docs/continuous-delivery/gitops/pr-pipelines/gitops-pipeline-steps.md
  docs/continuous-delivery/gitops/pr-pipelines/pr-pipelines.md
  docs/continuous-delivery/gitops/use-gitops/sops.md
  docs/continuous-delivery/manage-deployments/deployment-faqs.md
  docs/continuous-delivery/monitor-deployments/monitor-cd-deployments.md
  docs/continuous-delivery/verify/configure-cv/health-sources/app-dynamics.md
  docs/continuous-delivery/verify/cv-concepts/cv_ml.md
  docs/continuous-delivery/verify/cv-getstarted/configure-first-cv.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/cd-steps-faqs.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/containerized-step-groups.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/container-step.md
  docs/continuous-delivery/x-platform-cd-features/environments/create-environments.md
  docs/continuous-delivery/x-platform-cd-features/executions/stages-steps-strategies.md
  docs/continuous-delivery/x-platform-cd-features/templates/artifact-source-template.md
  docs/continuous-error-tracking/create-jira-ticket.md
  docs/continuous-error-tracking/get-started/cet-source-attach.md
  docs/first-gen/first-gen-quickstarts/helm-quickstart.md
  kb/continuous-delivery/articles/input-set-gitsync.md
Labels: DO NOT MERGE

#8000 Added release note, changed formatting
  release-notes/self-managed-enterprise-edition.md
Labels: Content - chore/cleanup

#7998 Add CI 1.46 RN and 1.45 RN from backlog.
  release-notes/continuous-integration.md
Labels: Release notes

#8012 Add note for `CI_ENABLE_BASE_IMAGE_DOCKER_CONNECTOR` FF.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
Labels: Content - gap / tech debt

#7975 docs: [IAC-2490]: Update what's supported details
  docs/infra-as-code-management/whats-supported.md
  src/components/Docs/data/iacmData.ts
Labels: Content - chore/cleanup

#8056 docs: [IAC-2506] Update IaCM state migration repo reference
  docs/infra-as-code-management/remote-backends/state-migration.md
Labels: Content - chore/cleanup

#8038 CHAOS-6466 Add content for resilience probes
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/cmd-probe.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/datadog-probe.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/dynatrace-probe.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/http-probe.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/k8s-probe.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/prom-probe.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/resilience-probes.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/shared/common-note.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/slo-probe.md
  docs/chaos-engineering/concepts/explore-concepts/resilience-probes/types.md
  docs/chaos-engineering/concepts/explore-features.md
  docs/chaos-engineering/use-harness-ce/experiments/experiments.md
  docs/chaos-engineering/use-harness-ce/probes/cmd-probe-usage.md
  docs/chaos-engineering/use-harness-ce/probes/probes.md
Labels: DO NOT MERGE

#8062 docs: [IAC-2497]: Update initialize backend doc with dynamo db example
  docs/infra-as-code-management/remote-backends/init-configuration.md
Labels: Content - gap / tech debt

#8063 Add CI 1.47 RN.
  release-notes/continuous-integration.md
Labels: Release notes

#8085 docs: [IAC-2520]: Update state migration doc
  docs/infra-as-code-management/remote-backends/state-migration.md
Labels: Content - gap / tech debt

#8081 Indicate that the CLI is primarily for CLG use case
  docs/platform/automation/cli/install.md
Labels: Content - chore/cleanup, Content - deprecation / removal

#8069 Add FAQ and a link in the docs.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ghcr.md
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - gap / tech debt

#8068 Add FAQ and link to docs - CI-14287.
  docs/platform/connectors/cloud-providers/ref-cloud-providers/docker-registry-connector-settings-reference.md
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - gap / tech debt
