Repository harness/developer-hub, pull requests merged in 2024-12, with the labels that each got.

#8506 CHAOS-6978 Windows network corruption docs
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/images/windows-network-corruption.png
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/manifests/windows-network-corruption/destination-hosts.yaml
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/manifests/windows-network-corruption/destination-ips.yaml
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/manifests/windows-network-corruption/network-packet-corruption.yaml
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/windows-network-corruption.md
Labels: Review - SME, DO NOT MERGE

#8758 CHAOS-7140 add note about SRM and delegate task
  docs/service-reliability-management/monitored-service/health-source/google-cloud-operations.md
Labels: Review - SME

#8822 docs: [IAC-2861]: Handle drift update
  docs/infra-as-code-management/pipelines/operations/drift-detection.md
  docs/infra-as-code-management/pipelines/operations/static/plan-refresh-only.png
Labels: Content - gap / tech debt

#8837 docs: [IAC-2871]: Update Terraform commands
  docs/infra-as-code-management/pipelines/iacm-plugins/terraform-plugins.md
Labels: Content - gap / tech debt

#8841 docs: [AH-764]: Add Tango guide to create a docker upstream proxy
  .github/CODEOWNERS
  docs/artifact-registry/get-started/quickstart.md
Labels: Content - enhancement

#8852 docs: [IAC-2892]: Move docs to Use IaCM
  docs/infra-as-code-management/get-started/_category_.json
  docs/infra-as-code-management/pipelines/_category_.json
  docs/infra-as-code-management/use-iacm/approval-step.md
  docs/infra-as-code-management/use-iacm/pr-automation.md
  docs/infra-as-code-management/use-iacm/provision-workspace.md
  docs/infra-as-code-management/use-iacm/static/add-approval-step.png
  docs/infra-as-code-management/use-iacm/static/approval-runtime.png
  docs/infra-as-code-management/use-iacm/static/pr-comment.png
  docs/infra-as-code-management/use-iacm/static/trigger.png
  docs/infra-as-code-management/whats-supported.md
  kb/reference-architectures/iacm/iacm-best-practices.md
  src/components/Docs/data/iacmData.ts
Labels: Content - chore/cleanup

#8864 docs: [IAC-2895]: Move features to new feature section
  docs/infra-as-code-management/iacm-features/_category_.json
  docs/infra-as-code-management/iacm-features/default-pipelines.md
  docs/infra-as-code-management/iacm-features/module-registry.md
  docs/infra-as-code-management/iacm-features/terraform-plan-cost-policy.md
  docs/infra-as-code-management/iacm-features/workspace-tempates.md
Labels: Content - chore/cleanup

#8858 bumped versions
  docs/platform/platform-whats-supported.md
Labels: Content - chore/cleanup

#8859 Update CI Codowner to add sushrut
  .github/CODEOWNERS
Labels: Content - enhancement

#8807 CHAOS-6966 Pod JVM modify return
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/experiments.ts
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/kubernetes.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/common-tunables-for-pod-faults.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/pod-jvm-modify-return.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/images/pod-jvm-modify-return.png
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/pod-jvm-modify-return/params.yaml
Labels: Review - SME

#8820 CHAOS-7059 Redis cache limit docs
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/experiments.ts
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/kubernetes.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/redis-cache-limit.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/shared/redis-auth.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/images/pod-redis-cache-limit.png
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/pod/static/manifests/redis-cache-limit/params.yaml
Labels: DO NOT MERGE

#8883 upload sonatype
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-sonatype-nexus.md
Labels: Content - chore/cleanup

#8804 Integrations page for AR
  docs/artifact-registry/platform-integrations/_category_.json
  docs/artifact-registry/platform-integrations/cd-ar-integrations.md
  docs/artifact-registry/platform-integrations/ci-ar-integrations.md
Labels: Content - enhancement

#8898 JIRA plugin will now update for multiple issues
  docs/continuous-integration/use-ci/use-drone-plugins/ci-jira-int-plugin.md
Labels: Content - enhancement, Content - chore/cleanup

#8920 docs: [AH-803]: Add Tango guide to AH and CI integration
  docs/artifact-registry/platform-integrations/ci-ar-integrations.md
Labels: Content - enhancement

#8867 docs: [IAC-2896]: Reorder IaCM sidebar
  docs/infra-as-code-management/faq.md
  docs/infra-as-code-management/iacm-security.md
  docs/infra-as-code-management/pipelines/_category_.json
  docs/infra-as-code-management/project-setup/_category_.json
  docs/infra-as-code-management/remote-backends/_category_.json
  docs/infra-as-code-management/reports-insights/_category_.json
  docs/infra-as-code-management/use-iacm/_category_.json
  docs/infra-as-code-management/workspaces/_category_.json
  src/components/University/data/iacm-certification-developer-review-guide.md
Labels: Content - chore/cleanup

#8939 Add note for other registries for local tar output.
  docs/continuous-integration/shared/build-and-push-local-tar.md
Labels: Content - chore/cleanup

#8945 Add warnings for platform connectivity
  docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
Labels: Blocked / On hold

#8869 Docs for Gitops Fail if steps times out
  docs/continuous-delivery/gitops/use-gitops/sync-gitops-applications.md
Labels: Blocked / On hold

#8749 CHAOS-6900 CHAOS-7122 Custom service account with DDCR
  docs/chaos-engineering/use-harness-ce/infrastructures/custom-sa.md
  docs/chaos-engineering/use-harness-ce/infrastructures/infrastructures.md
  docs/chaos-engineering/use-harness-ce/infrastructures/proxy-support.md
  docs/chaos-engineering/use-harness-ce/infrastructures/static/delegate/attach.png
  docs/chaos-engineering/use-harness-ce/infrastructures/static/delegate/cluster.png
  docs/chaos-engineering/use-harness-ce/infrastructures/static/delegate/diff-cluster.png
  docs/chaos-engineering/use-harness-ce/infrastructures/static/delegate/k8s-con.png
  docs/chaos-engineering/use-harness-ce/infrastructures/static/delegate/same-cluster.png
Labels: Review - SME
