Repository harness/developer-hub, pull requests merged in 2024-06, with the labels that each got.

#6861 CHAOS-5538 Use cmd probe in source mode with New Relic
  docs/chaos-engineering/features/probes/cmd-probe-usage.md
  docs/chaos-engineering/features/probes/cmd-probe/_category_.json
  docs/chaos-engineering/features/probes/cmd-probe/cmd-probe-newrelic.md
  docs/chaos-engineering/features/probes/cmd-probe/cmd-probe-usage.md
  docs/chaos-engineering/features/probes/cmd-probe/cmd-probe.md
  docs/chaos-engineering/features/probes/cmd-probe/static/cmd-probe-usage/confirm-5.png
  docs/chaos-engineering/features/probes/cmd-probe/static/cmd-probe-usage/inline-3.png
  docs/chaos-engineering/features/probes/cmd-probe/static/cmd-probe-usage/new-probe-1.png
  docs/chaos-engineering/features/probes/cmd-probe/static/cmd-probe-usage/select-probe-2.png
  docs/chaos-engineering/features/probes/cmd-probe/static/cmd-probe-usage/source-mode-3.png
  docs/chaos-engineering/features/probes/cmd-probe/static/cmd-probe-usage/source-mode-4.png
  docs/chaos-engineering/features/probes/cmd-probe/static/cmd-probe-usage/val-inline.png
  docs/chaos-engineering/features/probes/cmd-probe/static/cmd-probe-usage/val-source.png
  docs/chaos-engineering/features/probes/cmd-probe/static/confirm-5.png
  docs/chaos-engineering/features/probes/cmd-probe/static/inline-3.png
  docs/chaos-engineering/features/probes/cmd-probe/static/new-probe-1.png
  docs/chaos-engineering/features/probes/cmd-probe/static/newrelic/details-1.png
  docs/chaos-engineering/features/probes/cmd-probe/static/newrelic/details-2.png
  docs/chaos-engineering/features/probes/cmd-probe/static/newrelic/details-3.png
  docs/chaos-engineering/features/probes/cmd-probe/static/select-probe-2.png
  docs/chaos-engineering/features/probes/cmd-probe/static/source-mode-3.png
  docs/chaos-engineering/features/probes/cmd-probe/static/source-mode-4.png
  docs/chaos-engineering/features/probes/cmd-probe/static/val-inline.png
  docs/chaos-engineering/features/probes/cmd-probe/static/val-source.png
  docs/chaos-engineering/features/probes/overview.md
  docs/faqs/chaos-engineering-faq.md
Labels: Content - enhancement, Review - SME, DO NOT MERGE, Review - Editorial

#6879 Delegate size
  docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-kubernetes.md
  docs/platform/delegates/delegate-concepts/delegate-overview.md
  docs/platform/delegates/install-delegates/overview.md
Labels: Review - SME, DO NOT MERGE

#6849 [PL-51498] SMP 0.17.0 Release Notes
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes

#6907 Update SMP 0.17.0 release notes - add missing smp pl tickets
  release-notes/self-managed-enterprise-edition.md
Labels: Review - SME, DO NOT MERGE

#6912 NodeInfo labels issue fix
  release-notes/delegate.md
Labels: DO NOT MERGE

#6857 CHAOS-5623 Release notes 1.38.1
  release-notes/chaos-engineering.md
Labels: Release notes, Review - SME, DO NOT MERGE, Review - Editorial

#6919 CHAOS-5625 Experiment and fault status
  docs/chaos-engineering/features/experiments/experiment-execution.md
Labels: Content - chore/cleanup, Review - SME, Review - Editorial

#6924 CHAOS-5486 FAQ for k8s v1 optimization
  docs/faqs/chaos-engineering-faq.md
Labels: Content - FAQ

#6951 Remove nav 2.0 ff
  docs/platform/get-started/harness-ui-overview.md
Labels: Content - deprecation / removal

#6956 docs: [IAC-2028]: Add OIDC snippet to onboarding doc
  docs/infra-as-code-management/get-started/onboarding-guide.md
Labels: Content - gap / tech debt

#6321 mobile changes and ios tutorial
  docs/continuous-integration/development-guides/mobile/_category_.json
  docs/continuous-integration/development-guides/mobile/android.md
  docs/continuous-integration/development-guides/mobile/e2e-ios-tutorial.md
  docs/continuous-integration/development-guides/mobile/ios.md
  docs/continuous-integration/development-guides/mobile/mobile-dev-with-ci.md
  docs/continuous-integration/development-guides/mobile/static/appicons.png
  docs/continuous-integration/development-guides/mobile/static/buildstage.png
  docs/continuous-integration/development-guides/mobile/static/securitystage.png
  docs/continuous-integration/development-guides/mobile/static/simulator.png
Labels: Blocked / On hold

#6962 docs: [IAC-2044]: Rearrange IACM OPA usage doc
  docs/infra-as-code-management/workspaces/project-setup/opa-workspace.md
Labels: Content - gap / tech debt

#6943 docs: [IAC-2029]: Add custom images doc
  docs/infra-as-code-management/pipelines/iacm-plugins/plugin-images.md
  docs/infra-as-code-management/pipelines/iacm-plugins/terraform-plugins.md
Labels: Content - gap / tech debt

#6988 Roadmap for CD + a few for Platform.
  src/components/Roadmap/data/cdData.ts
  src/components/Roadmap/data/platformData.ts
Labels: Content - enhancement

#7003 Admonition for concurrent nodes.
  docs/platform/pipelines/looping-strategies/looping-strategies-matrix-repeat-and-parallelism.md
Labels: Content - chore/cleanup

#6986 [PL-51753] Update SMP installation
  docs/cloud-cost-management/shared/ccm-supported-platforms.md
  docs/faqs/self-managed-ee-faq.md
  docs/platform/get-started/onboarding-guide.md
  docs/platform/get-started/tutorials/install-delegate.md
  docs/self-managed-enterprise-edition/advanced-configurations/increase-pv-size-statefulsets.md
  docs/self-managed-enterprise-edition/advanced-configurations/use-ingress-controller-overrides.md
  docs/self-managed-enterprise-edition/demo-non-prod-install/install-in-demo-non-prod-env.md
  docs/self-managed-enterprise-edition/demo-non-prod-install/install-in-gcp.md
  docs/self-managed-enterprise-edition/get-started/onboarding-guide.md
  docs/self-managed-enterprise-edition/install/_category_.json
  docs/self-managed-enterprise-edition/install/harness-helm-chart.md
  docs/self-managed-enterprise-edition/install/install-in-an-air-gapped-environment.md
  docs/self-managed-enterprise-edition/install/install-in-openshift.md
  docs/self-managed-enterprise-edition/install/install-using-helm.md
  docs/self-managed-enterprise-edition/install/manage-feature-flags.md
  docs/self-managed-enterprise-edition/install/static/air-gapped-environment-workflow.png
  docs/self-managed-enterprise-edition/install/static/install-harness-self-managed-enterprise-edition-using-helm-ga-00.png
  docs/self-managed-enterprise-edition/install/uninstall-helm-chart.md
  docs/self-managed-enterprise-edition/install/upgrade-helm-chart.md
  docs/self-managed-enterprise-edition/reference-architecture.md
  docs/self-managed-enterprise-edition/shared/post-install-next-steps.md
  docs/self-managed-enterprise-edition/smp-supported-platforms.md
  kb/platform/harness-platform-faqs.md
  release-notes/self-managed-enterprise-edition.md
  src/components/Docs/data/selfManagedEnterpriseEditionData.ts
Labels: Review - SME, DO NOT MERGE

#7024 OIDC warnings for AWS
  docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
Labels: Content - chore/cleanup

#6995 CHAOS-5742 tkgi fault injection approach
  docs/chaos-engineering/chaos-faults/aws/aws-iam-integration.md
  docs/chaos-engineering/chaos-faults/aws/ec2-and-serverless-faults.md
  docs/chaos-engineering/chaos-faults/kubernetes/classification.md
  docs/chaos-engineering/chaos-faults/kubernetes/node/_category_.json
  docs/chaos-engineering/chaos-faults/kubernetes/permissions/_category_.json
  docs/chaos-engineering/chaos-faults/kubernetes/permissions/container-permissions.md
  docs/chaos-engineering/chaos-faults/kubernetes/permissions/fault-wise-permission.md
  docs/chaos-engineering/chaos-faults/kubernetes/pod/_category_.json
  docs/chaos-engineering/chaos-faults/kubernetes/security-considerations/_category_.json
  docs/chaos-engineering/chaos-faults/kubernetes/static/cloud-target-6.png
  docs/chaos-engineering/chaos-faults/kubernetes/static/cluster-2.png
  docs/chaos-engineering/chaos-faults/kubernetes/static/control-plane-1.png
  docs/chaos-engineering/chaos-faults/kubernetes/static/dns-chaos-4.png
  docs/chaos-engineering/chaos-faults/kubernetes/static/generic-flow-3.png
  docs/chaos-engineering/chaos-faults/kubernetes/static/ios-stress-5.png
  docs/chaos-engineering/chaos-faults/kubernetes/tkgi-deployment.md
Labels: Review - Editorial, Review - PM

#7059 CHAOS-5766 Update content
  docs/chaos-engineering/architecture-and-security/security/namespace-considerations.md
  docs/chaos-engineering/features/chaos-hubs/add-chaos-hub.md
  docs/chaos-engineering/features/chaos-hubs/introduction.md
  docs/chaos-engineering/features/chaos-hubs/manage-hub.md
  docs/chaos-engineering/features/chaos-infrastructure/introduction.md
  docs/chaos-engineering/features/experiments/construct-and-run-custom-chaos-experiments.md
  docs/chaos-engineering/features/experiments/edit-chaos-experiment.md
  docs/chaos-engineering/features/experiments/static/construct-and-run-custom-chaos-experiments/cron-schedule.png
  docs/chaos-engineering/features/experiments/static/construct-and-run-custom-chaos-experiments/schedule.png
  docs/chaos-engineering/onboarding/guided-onboarding.md
  docs/chaos-engineering/onboarding/hce-onboarding.md
  docs/chaos-engineering/onboarding/single-click-onboarding.md
  docs/chaos-engineering/onboarding/static/guided/connector.png
  docs/chaos-engineering/onboarding/static/guided/env-2.png
  docs/chaos-engineering/onboarding/static/guided/go-1.png
  docs/chaos-engineering/onboarding/static/guided/go-2.png
  docs/chaos-engineering/onboarding/static/guided/id-5.png
  docs/chaos-engineering/onboarding/static/guided/id-6.png
  docs/chaos-engineering/onboarding/static/guided/id-7.png
  docs/chaos-engineering/onboarding/static/guided/infra-def-4.png
  docs/chaos-engineering/onboarding/static/guided/nav-cd-1.png
  docs/chaos-engineering/onboarding/static/guided/run-checks-4.png
  docs/chaos-engineering/onboarding/static/guided/select-env-3.png
Labels: Content - chore/cleanup, DO NOT MERGE, Review - Editorial, Review - PM

#7054 Updates to quickstart guide
  docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
Labels: Content - enhancement, Content - chore/cleanup

#7080 docs: [IAC-2082]: Update Tango steps to follow UI updates
  docs/infra-as-code-management/get-started/onboarding-guide.md
Labels: Content - gap / tech debt

#7091 We added this ability. Fits best as a FAQ
  docs/continuous-delivery/gitops/gitops-faqs.md
Labels: Content - enhancement

#7037 AWS custom parameters
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
Labels: Content - enhancement, Content - feature flag

#7113 Minor change to include Base ASG option to docs.
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
Labels: Content - enhancement, Content - chore/cleanup

#7150 Help differentiate rollout deployment and restart steps
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollout-restart.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-rollout-step.md
Labels: Content - gap / tech debt

#7199 CHAOS-3347 Alert integration for chaos experiments
  docs/chaos-engineering/features/experiments/alert-integration.md
  docs/chaos-engineering/features/experiments/create-complex-chaos-experiments.md
  docs/chaos-engineering/features/experiments/edit-chaos-experiment.md
  docs/chaos-engineering/features/experiments/export-chaos-experiments.md
  docs/chaos-engineering/features/experiments/halt-chaos-experiments.md
  docs/chaos-engineering/features/experiments/static/alert-integration/admin-set-1.png
  docs/chaos-engineering/features/experiments/static/alert-integration/apply-15.png
  docs/chaos-engineering/features/experiments/static/alert-integration/channel-6.png
  docs/chaos-engineering/features/experiments/static/alert-integration/chaos-mod-4.png
  docs/chaos-engineering/features/experiments/static/alert-integration/condition-11.png
  docs/chaos-engineering/features/experiments/static/alert-integration/create-12.png
  docs/chaos-engineering/features/experiments/static/alert-integration/create-channel-7.png
  docs/chaos-engineering/features/experiments/static/alert-integration/delete-18.png
  docs/chaos-engineering/features/experiments/static/alert-integration/notification-5.png
  docs/chaos-engineering/features/experiments/static/alert-integration/notification-8-2.png
  docs/chaos-engineering/features/experiments/static/alert-integration/resources-10.png
  docs/chaos-engineering/features/experiments/static/alert-integration/rule-9.png
  docs/chaos-engineering/features/experiments/static/alert-integration/sample-report-17.png
  docs/chaos-engineering/features/experiments/static/alert-integration/see-channel-8.png
  docs/chaos-engineering/features/experiments/static/alert-integration/set-13.png
  docs/chaos-engineering/features/experiments/static/alert-integration/set-channel-14-2.png
  docs/chaos-engineering/features/experiments/static/alert-integration/setup-done-3.png
  docs/chaos-engineering/features/experiments/static/alert-integration/submit-16.png
Labels: Content - enhancement, DO NOT MERGE, Review - Editorial, Review - PM

#7185 [PL-52028] Platform 1.43.6 release notes
  release-notes/platform.md
Labels: Review - SME, DO NOT MERGE

#7235 Added language for terra https connector support
  docs/continuous-delivery/cd-infrastructure/terraform-infra/provision-infra-dynamically-with-terraform.md
  docs/continuous-delivery/cd-infrastructure/terragrunt-howtos.md
Labels: Content - enhancement, Blocked / On hold
