Repository harness/developer-hub, pull requests merged in 2024-08, with the labels that each got.

#7558 docs: [IAC-2279]: Add IaCM onboarding tile to get started panel
  src/components/Docs/data/iacmData.ts
Labels: Content - gap / tech debt

#7567 CI 1.38 Release Notes
  release-notes/continuous-integration.md
Labels: Release notes, Review - PM

#7548 docs: [IAC-2239]: Backfilled IaCM Release Notes
  release-notes/infrastructure-as-code-management.md
Labels: Release notes

#7504 onboarding guide and overview doc for db devops
  docs/database-devops/_category_.json
  docs/database-devops/get-started/_category_.json
  docs/database-devops/get-started/onboarding-guide.md
  docs/database-devops/get-started/overview.md
  sidebars.js
Labels: Ready to merge

#7592 CI 1.39 release notes.
  release-notes/continuous-integration.md
Labels: Release notes, Review - PM

#7588 roadmap rough draft
  src/components/Roadmap/data/cdData.ts
Labels: Content - enhancement

#7480 Add updated CRD deployment page for NG.
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/create-a-kubernetes-crd-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/static/create-kubernetes-crd-deployments-215.png
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-executions/static/create-kubernetes-crd-deployments-216.png
Labels: Content - enhancement, DO NOT MERGE, Content - gap / tech debt

#7598 Add git revert in CI docs.
  docs/continuous-integration/development-guides/security/_category_.json
  docs/continuous-integration/development-guides/security/git_revert_from_pr.md
  docs/continuous-integration/use-ci/codebase-configuration/git-revert-commit.md
Labels: Content - enhancement

#7620 Deprecate manual proxy instructions
  docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
  docs/continuous-delivery/gitops/connect-and-manage/static/add-a-proxy.png
Labels: Content - deprecation / removal

#7664 feat: [SEI-7926]: Added release notes for patch releases
  release-notes/software-engineering-insights.md
Labels: Release notes

#7650 [CDS-99734] CD release notes 1.51.x
  release-notes/continuous-delivery.md
Labels: Release notes

#7064 FF FAQ
  kb/feature-flags/harness-feature-flag-faqs.md
Labels: DO NOT MERGE, Review - Editorial

#7666 Add CI 1.41 RN.
  release-notes/continuous-integration.md
Labels: Release notes, Review - PM

#6970 [CI-12707] Update CI arch diagram
  docs/continuous-integration/get-started/static/ci-concepts-10.png
Labels: Review - SME, DO NOT MERGE

#7683 Upgrade policy made
  docs/continuous-delivery/cd-infrastructure/_category_.json
  docs/continuous-delivery/cd-onboarding/_category_.json
  docs/continuous-delivery/deploy-srv-diff-platforms/_category_.json
  docs/continuous-delivery/get-started/_category_.json
  docs/continuous-delivery/manage-deployments/_category_.json
  docs/continuous-delivery/toolchain-policy.md
  docs/continuous-delivery/x-platform-cd-features/_category_.json
Labels: Content - enhancement

#7537 CI-13300 Build Intelligence docs
  docs/continuous-integration/get-started/harness-ci-intelligence.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
Labels: Content - enhancement, Review - SME, Review - PM

#7687 Change formatting for link.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
Labels: Content - chore/cleanup

#7693 docs: [IAC-2344]: Update iacm overview
  docs/infra-as-code-management/get-started/overview.md
Labels: Content - enhancement

#7617 Clarification on
  docs/platform/triggers/trigger-deployments-using-custom-triggers.md
Labels: Content - chore/cleanup

#7529 CHAOS-6262 Update experiment-as-gitlab-pipeline
  docs/chaos-engineering/integrations/experiment-as-gitlab-pipeline.md
  docs/chaos-engineering/integrations/experiment-as-jenkins-pipeline.md
Labels: Content - chore/cleanup

#7718 Added status step to docs
  docs/continuous-delivery/gitops/pr-pipelines/gitops-pipeline-steps.md
Labels: Content - enhancement

#7764 BigQuery
  docs/continuous-delivery/verify/configure-cv/health-sources/google-big-query.md
Labels: Content - enhancement

#7773 CI 1.43 RN.
  release-notes/continuous-integration.md
Labels: Release notes, Review - PM

#7787 docs: [IAC-2255]: Add dynamic IaCM supported framework versions
  docs/infra-as-code-management/whats-supported.md
  docusaurus.config.js
  src/components/HarnessApiData/index.tsx
Labels: Content - enhancement, Content - chore/cleanup, Content - gap / tech debt

#7799 Fixed google cloud operations
  docs/continuous-delivery/verify/configure-cv/health-sources/google-cloud-operations.md
  docs/continuous-delivery/verify/configure-cv/health-sources/static/verify-deployments-with-google-cloud-operations-125.png
Labels: Content - chore/cleanup

#7736 docs: [IAC-2375]: IaCM delete workspace doc
  docs/infra-as-code-management/iacm_security.md
  docs/infra-as-code-management/project-setup/_category_.json
  docs/infra-as-code-management/project-setup/input-variables.md
  docs/infra-as-code-management/project-setup/opa-workspace.md
  docs/infra-as-code-management/project-setup/static/workspace-rbac.png
  docs/infra-as-code-management/project-setup/static/workspace-rg.png
  docs/infra-as-code-management/project-setup/use-delegates-with-iacm.md
  docs/infra-as-code-management/project-setup/workspace-rbac.md
  docs/infra-as-code-management/remote-backends/_category_.json
  docs/infra-as-code-management/reports-insights/_category_.json
  docs/infra-as-code-management/reports-insights/output-variables.md
  docs/infra-as-code-management/reports-insights/reports.md
  docs/infra-as-code-management/reports-insights/review-workspace.md
  docs/infra-as-code-management/reports-insights/static/output.png
  docs/infra-as-code-management/reports-insights/static/overview.png
  docs/infra-as-code-management/reports-insights/static/report-cost-breakdown.png
  docs/infra-as-code-management/reports-insights/static/report-current-activities.png
  docs/infra-as-code-management/reports-insights/static/report-workspace-status.png
  docs/infra-as-code-management/reports-insights/static/resources-tab.png
  docs/infra-as-code-management/reports-insights/static/state.png
  docs/infra-as-code-management/workspaces/delete-workspace.md
  src/components/Docs/data/iacmData.ts
Labels: Content - tutorials, Content - chore/cleanup, Content - gap / tech debt

#7817 docs: [IAC-2413: IACM Release Notes entry
  release-notes/infrastructure-as-code-management.md
Labels: Release notes

#7836 docs: [IAC-2419]: Update IaCM key concepts
  docs/infra-as-code-management/get-started/key-concepts.md
Labels: Content - gap / tech debt

#7840 Update _server-redirects for CD AWS category
  _server-redirects
Labels: Content - chore/cleanup, Content - gap / tech debt

#7842 Add redirect for broken CI FAQ page.
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - chore/cleanup, Content - FAQ

#7854 doc: [IAC-2426]: Remove support feature flags table
  docs/infra-as-code-management/whats-supported.md
Labels: Content - chore/cleanup

#7843 Regex for sync
  docs/continuous-delivery/gitops/pr-pipelines/gitops-pipeline-steps.md
  docs/continuous-delivery/gitops/use-gitops/static/gitopssync-step-regex.png
  docs/continuous-delivery/gitops/use-gitops/sync-gitops-applications.md
Labels: Content - chore/cleanup
