Repository harness/developer-hub, pull requests merged in 2024-07, with the labels that each got.

#7230 docs: [IAC-2104]: Add IaCM built-in policies
  docs/infra-as-code-management/policies/_category_.json
  docs/infra-as-code-management/policies/terraform-plan-cost-policy.md
Labels: Content - gap / tech debt

#7272 docs: [IAC-2151]: IaCM State migration tooling document
  docs/infra-as-code-management/remote-backends/state-migration.md
Labels: Content - gap / tech debt

#7266 trigger v2/v3 webhook clarifications
  docs/platform/triggers/trigger-deployments-using-custom-triggers.md
Labels: Content - chore/cleanup

#7284 docs: [IAC-2136]: Add Wiz scan support to IaCM docs
  docs/infra-as-code-management/pipelines/iacm-plugins/approval-step.md
  docs/infra-as-code-management/whats-supported.md
Labels: Content - gap / tech debt

#6837 [PL-51486] PL subscriptions - Cloud credits
  docs/continuous-integration/get-started/ci-subscription-mgmt.md
  docs/platform/get-started/subscriptions-licenses/subscriptions.md
  docs/platform/shared/static/cloud-credits.png
  docs/platform/shared/subscription-cloud-credits.md
Labels: DO NOT MERGE

#7315 Adding https protocol to two spots I missed
  docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md
  docs/continuous-delivery/cd-infrastructure/terragrunt-howtos.md
Labels: Content - chore/cleanup

#7307 Add Azure DevOps PAT requirements.
  docs/code-repository/config-repos/import-repo.md
Labels: Content - gap / tech debt

#7327 Add docs for setting env variables during helm steps
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/native-helm-quickstart.md
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/static/helm_environment_variables.png
Labels: Content - enhancement

#7292 [PL-55258] PL 1.45.x Release Notes
  release-notes/platform.md
Labels: Release notes, Review - SME, DO NOT MERGE

#7349 [PL-52124] Add a Subscriptions section to KB FAQ
  kb/platform/harness-platform-faqs.md
Labels: Review - SME

#7170 [PL-42276] Active PL Feature Flags
  docs/platform/platform-whats-supported.md
Labels: Review - SME, DO NOT MERGE

#7352 Add supported swimlanes for AWS OIDC
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
Labels: Content - chore/cleanup

#7384 [PL-52053] Update Gitness to Harness Open Source
  kb/platform/pipeline-faq.md
Labels: DO NOT MERGE

#7373 Updated gitops version table
  docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
Labels: Content - enhancement, Content - deprecation / removal

#7405 added clarifications for single host
  docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md
Labels: Content - enhancement, Content - chore/cleanup

#7406 Added an argo rollouts page to gitops
  docs/continuous-delivery/gitops/connect-and-manage/external-secrets-integration.md
  docs/continuous-delivery/gitops/connect-and-manage/hosted-gitops.md
  docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-1.png
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-2.png
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-3.png
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-4.png
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-5.png
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-6.png
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-7.png
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-8.png
  docs/continuous-delivery/gitops/connect-and-manage/static/use-argo-rollouts-9.png
  docs/continuous-delivery/gitops/connect-and-manage/use-argo-rollouts.md
  docs/continuous-delivery/gitops/connect-and-manage/use-flux.md
Labels: Content - enhancement

#7423 Remove GA FF from triggers topic
  docs/platform/triggers/trigger-on-a-new-artifact.md
Labels: Review - SME

#7374 Added admonition for k8s delegate
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
Labels: Content - chore/cleanup

#7429 CDS-99252 Removed feature flags
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/asg-tutorial.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-deployment-faqs.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/canary-deployment-step.md
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/add-bg-with-configurable-amount-of-tanzu.md
  docs/continuous-delivery/deploy-srv-diff-platforms/tanzu/tanzu-application-service-deployment-faqs.md
  docs/platform/pipelines/failure-handling/define-a-failure-strategy-on-stages-and-steps.md
  release-notes/continuous-delivery.md
  release-notes/self-managed-enterprise-edition.md
Labels: Content - chore/cleanup, DO NOT MERGE, Review - Editorial, Review - PM

#7453 Ad hoc update for copy config path creation behavior
  docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/download-and-copy-artifacts-using-the-command-step.md
Labels: Content - chore/cleanup

#7451 Added, K8s
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/define-your-kubernetes-target-infrastructure.md
Labels: Content - enhancement

#7388 CHAOS-6181 Release notes 1.41.1
  release-notes/chaos-engineering.md
Labels: Release notes, DO NOT MERGE

#7460 docs: [IAC-2177]: Update state migration instruction
  docs/infra-as-code-management/get-started/onboarding-guide.md
  docs/infra-as-code-management/remote-backends/state-migration.md
Labels: Content - enhancement

#7467 Add admonition for k8s deployments with delegate selectors
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-apply-step.md
  docs/platform/delegates/manage-delegates/select-delegates-with-selectors.md
Labels: Content - enhancement

#7057 CHAOS-5793 Replace network map with application map
  docs/chaos-engineering/features/app-maps/_category_.json
  docs/chaos-engineering/features/app-maps/intro-app-map.md
  docs/chaos-engineering/features/app-maps/static/confirm-delete-7.png
  docs/chaos-engineering/features/app-maps/static/create-agent-1.png
  docs/chaos-engineering/features/app-maps/static/create-nw-1.png
  docs/chaos-engineering/features/app-maps/static/delete-6.png
  docs/chaos-engineering/features/app-maps/static/edit-8.png
  docs/chaos-engineering/features/app-maps/static/name-np-2.png
  docs/chaos-engineering/features/app-maps/static/navigate-3.png
  docs/chaos-engineering/features/app-maps/static/save-nw-5.png
  docs/chaos-engineering/features/app-maps/static/select-agent-2.png
  docs/chaos-engineering/features/app-maps/static/select-service-3.png
  docs/chaos-engineering/features/app-maps/static/service-rel-4.png
  docs/chaos-engineering/features/chaos-infrastructure/harness-infra/harness-infra.md
  docs/chaos-engineering/features/network-maps/_category_.json
  docs/chaos-engineering/features/network-maps/intro-network-map.md
  docs/chaos-engineering/features/network-maps/static/confirm-delete-7.png
  docs/chaos-engineering/features/network-maps/static/create-nw-1.png
  docs/chaos-engineering/features/network-maps/static/delete-6.png
  docs/chaos-engineering/features/network-maps/static/edit-8.png
  docs/chaos-engineering/features/network-maps/static/name-np-2.png
  docs/chaos-engineering/features/service-discovery/intro-service-discovery.md
  docs/chaos-engineering/features/service-discovery/service-discovery-usage.md
  docs/chaos-engineering/features/service-discovery/static/usage/discovery.png
  docs/chaos-engineering/features/service-discovery/static/usage/select-agent.png
  docs/chaos-engineering/onboarding/hce-onboarding.md
  src/components/Roadmap/data/ceData.ts
Labels: Content - chore/cleanup, DO NOT MERGE

#7256 CHAOS-5004 DynamoDB replication pause fault
  docs/chaos-engineering/chaos-faults/aws/dynamo-db-replication-pause.md
  docs/chaos-engineering/chaos-faults/aws/static/images/dynamo-db-replication-pause.png
  docs/chaos-engineering/chaos-faults/aws/static/manifests/dynamo-db-replication-pause/count.yaml
  docs/chaos-engineering/chaos-faults/aws/static/manifests/dynamo-db-replication-pause/fis-details.yaml
  docs/chaos-engineering/chaos-faults/aws/static/manifests/dynamo-db-replication-pause/stop-conditions.yaml
  docs/chaos-engineering/chaos-faults/aws/static/manifests/dynamo-db-replication-pause/table-names.yaml
Labels: Content - enhancement, DO NOT MERGE, Review - Editorial, Review - PM

#7487 FFM-11810 Update Relay PRoxy Docs
  docs/feature-flags/use-ff/relay-proxy/relay_proxy_v2.md
  release-notes/feature-flags.md
Labels: DO NOT MERGE

#7507 deprecation for container step
  docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/container-step.md
Labels: Content - deprecation / removal

#7479 terminate sync docs
  docs/continuous-delivery/gitops/use-gitops/static/terminate_sync.png
  docs/continuous-delivery/gitops/use-gitops/sync-gitops-applications.md
Labels: Content - enhancement

#7478 CI-13349 Update clone codebase and clone step docs with new functionality
  docs/continuous-integration/shared/ci-supported-platforms.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-subdirectory.md
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/continuous-integration/use-ci/codebase-configuration/git-clone-step.md
  docs/continuous-integration/use-ci/codebase-configuration/static/clone-subdirectory-sparse-checkout-1.png
  docs/continuous-integration/use-ci/codebase-configuration/static/clone-subdirectory-sparse-checkout-2.png
  docs/continuous-integration/use-ci/codebase-configuration/static/create-and-configure-a-codebase-00.png
  docs/continuous-integration/use-ci/codebase-configuration/static/create-and-configure-a-codebase-03.png
  docs/continuous-integration/use-ci/codebase-configuration/static/git-clone-step.png
  docs/continuous-integration/use-ci/codebase-configuration/static/gitlfs.md
  docs/continuous-integration/use-ci/codebase-configuration/static/harness_code_repository_default.png
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - enhancement

#7464 CI 1.36 and 1.37 RN for CI.
  release-notes/continuous-integration.md
Labels: Release notes, Review - PM

#7322 Update windows custom image info note.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md
Labels: Content - chore/cleanup

#7534 Add requirement to open port 20001.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
Labels: Content - gap / tech debt
