Repository harness/developer-hub, pull requests merged in 2024-04, with the labels that each got.

#6115 CDS-94151
  docs/platform/variables-and-expressions/harness-variables.md
Labels: DO NOT MERGE

#6110 Added documentation for user id possible mismatch for git commands
  docs/continuous-delivery/cd-infrastructure/aws-cdk.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/git-clone-step.md
Labels: Content - gap / tech debt

#6138 Update secure-connect-arch2.png
  docs/continuous-integration/secure-ci/static/secure-connect-arch2.png
Labels: Content - chore/cleanup

#6112 Add github-app-pat-dispenser kb article
  kb/continuous-integration/articles/github-app-pat-dispenser.md
  kb/continuous-integration/static/github-app-pat-dispenser-1.png
  kb/continuous-integration/static/github-app-pat-dispenser-2.png
  kb/continuous-integration/static/github-app-pat-dispenser-3.png
  kb/continuous-integration/static/github-app-pat-dispenser-4.png
Labels: Content - KB

#6141 Update debug-mode.md
  docs/continuous-integration/troubleshoot-ci/debug-mode.md
Labels: Content - chore/cleanup

#6137 CDS-93927 - using secrets as URLs in an HTTP step
  docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
Labels: Content - gap / tech debt

#6146 Add information that it is possible to create a connector with a none…
  docs/platform/connectors/cloud-providers/add-a-kubernetes-cluster-connector.md
  docs/platform/connectors/cloud-providers/add-a-microsoft-azure-connector.md
  docs/platform/connectors/cloud-providers/add-aws-connector.md
  docs/platform/connectors/cloud-providers/connect-to-google-cloud-platform-gcp.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/kubernetes-cluster-connector-settings-reference.md
Labels: Draft, DO NOT MERGE, Content - gap / tech debt

#6151 Added Oldgen data retention to FAQ
  docs/continuous-delivery/get-started/upgrading/cdng-upgrade-faq.md
Labels: Content - gap / tech debt

#6167 Pl subscription license section
  docs/continuous-delivery/cd-onboarding/new-user/rampup-admin.md
  docs/continuous-delivery/get-started/service-licensing-for-cd.md
  docs/continuous-integration/shared/subscription-create.md
  docs/continuous-integration/shared/subscription-view-usage.md
  docs/first-gen/starthere-firstgen/view-account-info-and-subscribe-to-downtime-alerts.md
  docs/platform/get-started/cloud-marketplace-integration/google-cloud-marketplace.md
  docs/platform/get-started/harness-ui-overview.md
  docs/platform/get-started/key-concepts.md
  docs/platform/get-started/onboarding-guide.md
  docs/platform/get-started/subscriptions-licenses/_category_.json
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/_category_.json
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/aws-marketplace.md
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/google-cloud-marketplace.md
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_create_private_offer.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_public_offer_subscribe.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_pvt_offer_activation_in_progress.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_pvt_offer_activation_inprogress.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_pvt_offer_active.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_pvt_offer_contact_sales_form.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_pvt_offer_customer_accept.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_pvt_offer_customer_accepted.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_pvt_offer_customer_email.png
  docs/platform/get-started/subscriptions-licenses/cloud-marketplace-integration/static/gcp_pvt_offer_pending_state.png
  docs/platform/get-started/subscriptions-licenses/subscriptions.md
  docs/platform/get-started/subscriptions-licenses/view-account-info-and-subscribe-to-alerts.md
  docs/platform/get-started/tutorials/install-delegate.md
Labels: Content - chore/cleanup, Review - Editorial, Content - gap / tech debt

#6168 update srm early access for new style
  docs/service-reliability-management/srm-whats-supported.md
  release-notes/early-access.md
Labels: Content - enhancement, Content - chore/cleanup

#6132 CHAOS-4911 Specify how to use env vars for chaos and abort parameters
  docs/chaos-engineering/chaos-faults/ssh/prerequisites.md
  docs/chaos-engineering/chaos-faults/ssh/ssh-chaos.md
  docs/chaos-engineering/chaos-faults/ssh/static/images/ssh-chaos/prep-1.png
  docs/chaos-engineering/chaos-faults/ssh/static/images/ssh-chaos/prep-2.png
  docs/chaos-engineering/chaos-faults/ssh/static/images/ssh-chaos/prep-3.png
  docs/chaos-engineering/chaos-faults/ssh/static/images/ssh-chaos/prep-4.png
  docs/chaos-engineering/chaos-faults/ssh/static/images/ssh-chaos/secret-button.png
Labels: Content - enhancement

#6079 CI 1.21.x rns
  docs/continuous-integration/ci-supported-platforms.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
  docs/platform/connectors/code-repositories/ref-source-repo-provider/bitbucket-connector-settings-reference.md
  docs/software-engineering-insights/sei-metrics-and-reports/quality-metrics-reports/testrail-reports.md
  release-notes/continuous-integration.md
Labels: Release notes

#6169 New PR and Issue templates
  .github/issue_template.md
  .github/pull_request_template.md
Labels: Content - chore/cleanup, Review - Editorial, Content - gap / tech debt

#6189 Update secure-connect.md
  docs/continuous-integration/secure-ci/secure-connect.md
Labels: Content - chore/cleanup

#6188 Remove valueless `tags` metadata
  CONTRIBUTING.md
  docs/platform/get-started/tutorials/gke-workload-identity.md
  docs/platform/get-started/tutorials/secure-delegate-default-to-minimal.md
  release-notes/chaos-engineering.md
  release-notes/cloud-cost-management.md
  release-notes/code-repository.md
  release-notes/continuous-delivery.md
  release-notes/continuous-error-tracking.md
  release-notes/continuous-integration.md
  release-notes/delegate.md
  release-notes/feature-flags.md
  release-notes/internal-developer-portal.md
  release-notes/platform.md
  release-notes/security-testing-orchestration.md
  release-notes/self-managed-enterprise-edition.md
  release-notes/service-reliability-management.md
  release-notes/software-engineering-insights.md
  release-notes/software-supply-chain-assurance.md
Labels: Content - chore/cleanup

#6193 STO 2024-04-03 releas notes STO-7391
  release-notes/security-testing-orchestration.md
Labels: Review - SME, DO NOT MERGE

#6205 Delegate 24.04.82603 Hotfix RN
  release-notes/delegate.md
Labels: Release notes

#6231 Update ci-localstack-background-step.md
  docs/continuous-integration/use-ci/manage-dependencies/ci-localstack-background-step.md
Labels: Content - chore/cleanup

#6217 Add missing expression to reference. (CDS-95148)
  docs/platform/variables-and-expressions/harness-variables.md
Labels: Content - enhancement

#6216 Zap docs updates sto 7295
  docs/security-testing-orchestration/sto-techref-category/shared/_sto-supported-binaries.md
  docs/security-testing-orchestration/sto-techref-category/shared/root-access-requirements-no-dind.md
  docs/security-testing-orchestration/sto-techref-category/static/sto-7287-zap-workaround.png
  docs/security-testing-orchestration/sto-techref-category/zap/zap-scanner-reference.md
  release-notes/security-testing-orchestration.md
Labels: Blocked / On hold, Review - SME, Review - PM

#6235 hotfix for 1.90 release STO-7402
  release-notes/security-testing-orchestration.md
Labels: Blocked / On hold, Review - Editorial

#6180 CHAOS-4583 GCP IAM integration
  docs/chaos-engineering/chaos-faults/aws/aws-iam-integration.md
  docs/chaos-engineering/chaos-faults/gcp/gcp-iam-integration.md
Labels: Review - SME, DO NOT MERGE, Content - gap / tech debt

#6072 feat: [CDS-91799]: Add reconciliation concept in the doc
  docs/platform/templates/reconcile-pipeline-templates.md
  docs/platform/templates/static/reconcile_pipeline_template.png
  docs/platform/templates/static/reconcile_popup.png
Labels: Review - SME, DO NOT MERGE

#6250 CI/CODE misc 08 apr 24
  docs/code-repository/config-repos/create-repo.md
  docs/code-repository/config-repos/import-repo.md
  docs/code-repository/config-repos/rules.md
  docs/code-repository/get-started/onboarding-guide.md
  docs/code-repository/get-started/overview.md
  docs/continuous-integration/secure-ci/gcp-oidc-token-plugin.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/use-drone-plugins/explore-ci-plugins.md
Labels: Content - chore/cleanup

#6256 Update which-build-infrastructure-is-right-for-me.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
Labels: Content - chore/cleanup

#6174 CHAOS-4950 Release notes 1.34.0
  release-notes/chaos-engineering.md
Labels: Release notes, DO NOT MERGE

#6220 Fixed yaml to be accurate (hopefully)
  docs/continuous-delivery/deploy-srv-diff-platforms/google-functions.md
Labels: Content - chore/cleanup, Content - gap / tech debt

#6266 Adding 8 FAQs to our docs
  kb/platform/harness-platform-faqs.md
Labels: DO NOT MERGE, Review - Editorial

#6270 typo fix
  docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
Labels: Content - chore/cleanup

#6199 CHAOS-4388 HCE onboard CLI
  docs/chaos-engineering/api-reference/hce-onboarding-api.md
  docs/chaos-engineering/api-reference/hce-saas-api.md
  docs/chaos-engineering/features/chaos-infrastructure/connect-chaos-infrastructures.md
Labels: Review - SME, DO NOT MERGE, Review - Editorial, Content - gap / tech debt

#6276 CHAOS-5023 update powered-by-litmus
  docs/chaos-engineering/get-started/powered-by-litmus.md
Labels: Content - chore/cleanup

#6149 Trigger sto scan to block pull requests with vulnerabilities sto 7342
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/trigger-to-block-prs/add-check-to-branch-protection-rule.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/trigger-to-block-prs/changed-file-condition-example-simple.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/trigger-to-block-prs/github-new-trigger.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/trigger-to-block-prs/pr-check-failed.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/trigger-to-block-prs/review-comment-condition-example-simple.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/trigger-to-block-prs/test-trigger-01-req-response-successful.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/trigger-to-block-prs/test-trigger-02-new-pipeline-execution.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/static/trigger-to-block-prs/test-trigger-03-check-running-in-pr.png
  docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/trigger-sto-scans-to-block-prs-with-vulnerabilities.md
Labels: Review - SME, DO NOT MERGE, Review - PM

#6254 [PL-48906] Clock synchronization
  docs/platform/settings/clock-sychronization.md
  docs/platform/settings/default-settings.md
Labels: Review - SME, DO NOT MERGE

#6269 CD FAQ
  kb/continuous-delivery/continuous-delivery-faqs.md
Labels: DO NOT MERGE, Review - Editorial

#6271 add -Dsonar.projectName and -Dsonar.projectKey STO-7377
  docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
Labels: Blocked / On hold, Review - SME

#6282 Scaffolding for RA section
  docusaurus.config.js
  kb/reference-architectures/about-reference-architectures.md
  sidebars-kb.js
Labels: DO NOT MERGE

#5581 [PL-40502] PL central notifications - delegate
  docs/platform/notifications/add-smtp-configuration.md
  docs/platform/notifications/manage-notifications.md
  docs/platform/notifications/send-notifications-to-microsoft-teams.md
  docs/platform/notifications/send-notifications-using-slack.md
  docs/platform/notifications/static/new-notification-setup.png
  docs/platform/notifications/static/notifications-management.png
Labels: DO NOT MERGE

#6286 CDS-89735
  docs/platform/triggers/static/create-input-set.png
  docs/platform/triggers/triggers-reference.md
Labels: DO NOT MERGE

#6302 add migration utility topic
  docs/continuous-integration/migration-guides/migration-utility.md
Labels: Content - gap / tech debt

#6301 ci-12007 - Harness Container Image Registry
  docs/continuous-integration/shared/docker-hub-rate-limiting-trbs.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
  docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md
Labels: Content - chore/cleanup, Content - gap / tech debt

#6252 Add Caution snippet to CLI argument examples for external scanners STO-7278 v2
  docs/security-testing-orchestration/sto-techref-category/anchore-enterprise-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/aquasec-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/aws-ecr-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/bandit-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/black-duck-hub-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/brakeman-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/burp-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/codeql-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/fortify-on-demand-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/fortify-on-demand-scanner-reference.txt
  docs/security-testing-orchestration/sto-techref-category/fossa-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/grype/grype-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/mend-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/nikto-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/nmap-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/osv-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/prisma-cloud-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/prowler-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/security-step-ui-settings-reference.txt
  docs/security-testing-orchestration/sto-techref-category/semgrep/semgrep-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/all/_cli-flags-caution.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/all/_cli-flags.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/all/_settings.md
  docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/sysdig-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/trivy/aqua-trivy-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/zap/zap-scanner-reference.md
Labels: Blocked / On hold, Review - SME

#6300 Remove OPA_PIPELINE_GOVERNANCE FF
  docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/add-a-governance-policy-step-to-a-pipeline.md
  docs/continuous-delivery/x-platform-cd-features/advanced/cd-governance/harness-governance-quickstart.md
  docs/feature-flags/harness-policy-engine.md
  docs/platform/governance/policy-as-code/harness-governance-quickstart.md
  docs/platform/governance/policy-as-code/sample-policy-use-case.md
  docs/platform/governance/policy-as-code/using-harness-policy-engine-for-feature-flags.md
  docs/platform/governance/policy-as-code/using-policy-enforcement-on-pipeline-steps.md
Labels: Content - chore/cleanup

#6322 Fix technical docs error about step group nesting
  docs/continuous-delivery/x-platform-cd-features/cd-steps/step-groups.md
Labels: Content - gap / tech debt

#6325 Docs review
  docs/chaos-engineering/chaos-faults/linux/linux-network-corruption.md
  docs/chaos-engineering/chaos-faults/linux/linux-network-duplication.md
  docs/chaos-engineering/chaos-faults/linux/linux-network-latency.md
  docs/chaos-engineering/chaos-faults/linux/linux-network-loss.md
  docs/chaos-engineering/chaos-faults/linux/linux-network-rate-limit.md
Labels: Content - enhancement, Review - Editorial

#6313 CHAOS-4980 Update content and screenshots
  docs/chaos-engineering/get-started/hce-onboarding.md
  docs/chaos-engineering/get-started/key-concepts.md
  docs/chaos-engineering/get-started/overview.md
  docs/chaos-engineering/get-started/powered-by-litmus.md
  docs/chaos-engineering/get-started/tutorials/chaos-experiment-from-blank-canvas.md
  docs/chaos-engineering/get-started/tutorials/experiment-using-api.md
  docs/chaos-engineering/get-started/tutorials/first-chaos-engineering.md
  docs/chaos-engineering/get-started/tutorials/prerequisites.md
  docs/chaos-engineering/get-started/tutorials/static/add-new-user.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/apply-changes.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/boutique-delete-3.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/configure-chaos-infrastructure.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/continuous-mode.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/create-new-environment.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/create-new-experiment-1.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/deploy-chaos-infrastructure.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/enable-chaos.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/exp-running.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/exp-status.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/fail-msg.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/fault-weight.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/hce-overview.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/new-chaos-infrastructure.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/pod-delete-fail.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/probes-config-2.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/probes-config-3.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/probes-config-4.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/probes-config.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/provide-name.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/run-n-save.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/specify-params-2.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/target-application-config.png
  docs/chaos-engineering/get-started/tutorials/static/first-chaos/tune-fault-config.png
  docs/chaos-engineering/get-started/tutorials/static/using-api/detailed-chaos-execution.png
  docs/chaos-engineering/get-started/tutorials/static/using-api/experiment-executing.png
  docs/chaos-engineering/get-started/tutorials/static/using-api/experiment-failed-probe.png
  docs/chaos-engineering/get-started/tutorials/static/using-api/fail-step-result.png
Labels: Content - chore/cleanup

#6351 CDS-91035-Store Terraform Plan files on Harness Delegate temporarily
  docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-plan-step.md
Labels: Draft

#6359 added missing org identifier expression
  docs/platform/variables-and-expressions/harness-variables.md
Labels: Content - gap / tech debt

#6362 Update harness-platform-faqs.md
  kb/platform/harness-platform-faqs.md
Labels: DO NOT MERGE, Review - Editorial

#6186 CI 1.22.x rns
  docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-steps/plugin-step.md
  docs/continuous-integration/ci-supported-platforms.md
  docs/continuous-integration/development-guides/mobile-dev-with-ci.md
  docs/continuous-integration/get-started/key-concepts.md
  docs/continuous-integration/migration-guides/migrating-from-circleci.md
  docs/continuous-integration/migration-guides/migrating-from-gitlab.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
  docs/continuous-integration/use-ci/use-drone-plugins/ci-bitrise-plugin.md
  docs/continuous-integration/use-ci/use-drone-plugins/explore-ci-plugins.md
  kb/continuous-integration/continuous-integration-faqs.md
  release-notes/continuous-integration.md
  src/components/Docs/data/continuousIntegrationData.ts
Labels: Release notes

#6381 Ci grab bag 18 apr 24
  docs/continuous-integration/get-started/ci-subscription-mgmt.md
  docs/continuous-integration/get-started/overview.md
  docs/continuous-integration/get-started/static/ci_subscribe_compare_plans.png
  docs/continuous-integration/shared/subscription-view-usage.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
  docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - chore/cleanup

#6382 Update testGlobs pattern.
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-ruby.md
Labels: Content - chore/cleanup

#6356 [PL-46739] Update install delegate screenshot - remove legacy link
  docs/platform/delegates/install-delegates/install-a-kubernetes-delegate.md
  docs/platform/get-started/tutorials/install-delegate.md
  docs/platform/get-started/tutorials/static/install-a-k8s-delegate-helm.png
Labels: Content - chore/cleanup

#6355 [PL-48995] Delegate notifications - update screenshot and UI elements
  docs/platform/notifications/manage-notifications.md
  docs/platform/notifications/static/notifications-management.png
Labels: Content - chore/cleanup

#6377 2024-04-18 release notes STO-7455
  docs/security-testing-orchestration/sto-techref-category/shared/_supported-infrastructures.md
  docs/security-testing-orchestration/sto-techref-category/zap/zap-scanner-reference.md
  release-notes/security-testing-orchestration.md
  release-notes/static/sto-7384-security-stage-name-update-when-adding-new-stage.png
  release-notes/static/sto-7385-custom-scan-step-in-step-library.png
Labels: Release notes, Review - SME, DO NOT MERGE, Review - Editorial

#6374 add Gitleak workflows based on WW input STO-7396
  docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md
Labels: Review - SME, DO NOT MERGE

#6390 add detailed support info for Checkmarx STO-7419
  docs/security-testing-orchestration/sto-techref-category/checkmarx-scanner-reference.md
Labels: DO NOT MERGE, Review - Editorial

#6389 Fixed docs errors, gaps relating terraform
  docs/continuous-delivery/cd-infrastructure/terraform-infra/run-a-terraform-plan-with-the-terraform-apply-step.md
Labels: Content - deprecation / removal

#6407 Gitleaks/OSV/OWASP CLI arg examples STO-7278-v2
  docs/security-testing-orchestration/sto-techref-category/gitleaks-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/osv-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/owasp-scanner-reference.md
  docs/security-testing-orchestration/sto-techref-category/shared/step_palette/all/_cli-flags-caution.md
  docs/security-testing-orchestration/sto-techref-category/static/gitleaks-toolargs-example.png
Labels: Review - SME, DO NOT MERGE, Review - Editorial

#6405 remove post prod rollback FF mentions
  docs/continuous-delivery/manage-deployments/rollback-deployments.md
  kb/continuous-delivery/continuous-delivery-faqs.md
  release-notes/continuous-delivery.md
  release-notes/self-managed-enterprise-edition.md
Labels: Content - chore/cleanup

#6401 CHAOS-5149 Audit images and grammar check
  docs/chaos-engineering/architecture-and-security/architecture/architecture.md
  docs/chaos-engineering/architecture-and-security/security/introduction.md
  docs/chaos-engineering/features/chaos-infrastructure/connect-chaos-infrastructures.md
  docs/chaos-engineering/features/chaos-infrastructure/disconnect-chaos-infrastructure.md
  docs/chaos-engineering/features/chaos-infrastructure/openshift-infra.md
  docs/chaos-engineering/features/experiments/construct-and-run-custom-chaos-experiments.md
  docs/chaos-engineering/features/experiments/create-complex-chaos-experiments.md
  docs/chaos-engineering/features/experiments/edit-chaos-experiment.md
  docs/chaos-engineering/features/experiments/export-chaos-experiments.md
  docs/chaos-engineering/features/experiments/halt-chaos-experiments.md
  docs/chaos-engineering/features/experiments/static/edit-experiment/navigate-1.png
  docs/chaos-engineering/features/gameday/introduction-to-gameday.md
  docs/chaos-engineering/features/gameday/run-gameday.md
  docs/chaos-engineering/features/image-registry.md
  docs/chaos-engineering/features/probes/cmd-probe-usage.md
  docs/chaos-engineering/features/probes/configure-and-add-probe.md
  docs/chaos-engineering/features/probes/http-probe.md
  docs/chaos-engineering/features/probes/k8s-probe.md
  docs/chaos-engineering/features/probes/overview.md
  docs/chaos-engineering/features/probes/prom-probe.md
  docs/chaos-engineering/features/probes/static/cmd-probe-usage/confirm-5.png
  docs/chaos-engineering/features/probes/static/cmd-probe-usage/new-probe-1.png
  docs/chaos-engineering/features/probes/static/configure-and-add-probe/step2.png
  docs/chaos-engineering/features/probes/static/configure-and-add-probe/step3.1.png
  docs/chaos-engineering/features/probes/static/configure-and-add-probe/step3.2.png
  docs/chaos-engineering/features/probes/static/configure-and-add-probe/step3.3.png
  docs/chaos-engineering/features/probes/static/configure-and-add-probe/step4.png
  docs/chaos-engineering/features/probes/static/probe-acceptance/edit-4.png
  docs/chaos-engineering/features/probes/static/probe-acceptance/navigate.png
  docs/chaos-engineering/features/probes/static/validate-hypothesis-using-probes/probe-list.png
  docs/chaos-engineering/features/resilience-probes/introduction.md
  docs/chaos-engineering/features/resilience-probes/probe-acceptance-criteria.md
  docs/chaos-engineering/get-started/tutorials/chaos-experiment-from-blank-canvas.md
  docs/chaos-engineering/get-started/tutorials/first-chaos-engineering.md
  docs/chaos-engineering/integrations/hce-and-cd/chaos-cd.md
  docs/chaos-engineering/integrations/hce-and-cd/experiment-as-cd-pipeline.md
  docs/chaos-engineering/troubleshooting/troubleshooting.md
Labels: Content - chore/cleanup

#6380 ci 1.24.x rns
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-ruby.md
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/manage-feature-flags.md
  release-notes/continuous-integration.md
Labels: Release notes, Review - Editorial

#6406 [PL-49173] SMP Add vanity URL script
  docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
Labels: Review - Editorial

#6426 Ci grab bag 23 apr 24
  docs/continuous-integration/secure-ci/secure-connect.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
Labels: Content - chore/cleanup, Review - Editorial, Content - gap / tech debt

#6366 [PL-49108] PL 1.34.x Release Notes
  release-notes/platform.md
Labels: Release notes

#6430 broken link
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - chore/cleanup

#6285 CHAOS-5040 Release notes 1.35.0
  release-notes/chaos-engineering.md
Labels: Release notes, DO NOT MERGE

#6415 [IAC-1786] IAC 0.181.0 Release Notes
  release-notes/infrastucture-as-code-management.md
  src/components/ReleaseNotes/data/releaseNotesData.ts
Labels: Release notes

#6367 [PL-49109] DEL 82800 Release Notes
  release-notes/delegate.md
Labels: Release notes, Review - SME, DO NOT MERGE

#6438 docs: [IAC-1830]: IACM release notes (versions 0.175.0, 0.176.0 & 0.178.0)
  release-notes/infrastucture-as-code-management.md
Labels: Release notes

#6433 CHAOS-5188 CF fault chaos components and deployment architecture
  docs/chaos-engineering/chaos-faults/cloud-foundry/cf-components-and-arch.md
  docs/chaos-engineering/chaos-faults/cloud-foundry/static/images/control-plane-2.png
  docs/chaos-engineering/chaos-faults/cloud-foundry/static/images/deployment-model-3.png
  docs/chaos-engineering/chaos-faults/cloud-foundry/static/images/deployment-tanzu-4.png
  docs/chaos-engineering/chaos-faults/cloud-foundry/static/images/test-resilience-1.png
Labels: Content - enhancement

#6435 Update aws-sam-deployments.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
Labels: Draft

#6453 Recommend GH app for GH connector; MSI support for Local Runner Build Infra
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
  docs/platform/connectors/code-repositories/connect-to-code-repo.md
  docs/platform/connectors/code-repositories/git-hub-app-support.md
  docs/platform/connectors/code-repositories/ref-source-repo-provider/git-hub-connector-settings-reference.md
Labels: Content - enhancement, Content - chore/cleanup

#6451 docs: [IAC-1847]: IAC 0.152.0 Release Notes
  release-notes/infrastucture-as-code-management.md
Labels: Release notes

#6471 docs: [IAC-1842]: Update IACM description and fix release notes seo typo
  release-notes/infrastructure-as-code-management.md
  src/components/Docs/Iacm.tsx
  src/components/ReleaseNotes/data/releaseNotesData.ts
Labels: Content - chore/cleanup

#6463 Added steps on how to find values for Azure health source
  docs/service-reliability-management/monitored-service/health-source/azurelogs.md
Labels: Content - enhancement

#4851 Ccm onboarding guide
  docs/cloud-cost-management/ccm-onboarding/_category_.json
  docs/cloud-cost-management/ccm-onboarding/onboarding-path.md
  docs/cloud-cost-management/get-started/_category_.json
Labels: Draft, DO NOT MERGE

#6462 FAQ on how stats are calculated.
  kb/continuous-delivery/continuous-delivery-faqs.md
Labels: Content - gap / tech debt

#6475 Added troubleshooting for OAuth with git.
  docs/platform/triggers/triggering-pipelines.md
Labels: Content - gap / tech debt

#6455 CDS-96111 CD RN 1.35.x
  release-notes/continuous-delivery.md
Labels: Draft, Release notes

#6496 Secret type selection for CI Run steps
  docs/continuous-integration/ci-supported-platforms.md
  docs/continuous-integration/shared/output-var.md
  docs/continuous-integration/use-ci/run-tests/test-intelligence/set-up-test-intelligence.md
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-csharp.md
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-java-kotlin-scala.md
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-python.md
  docs/continuous-integration/use-ci/run-tests/test-intelligence/ti-for-ruby.md
  docs/continuous-integration/use-ci/static/run-step-output-var-type.png
  release-notes/continuous-integration.md
Labels: Content - feature flag

#6408 [PL-49125] Add Harness OIDC provider endpoint and OIDC audience settings
  docs/platform/connectors/cloud-providers/add-aws-connector.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
  kb/continuous-delivery/continuous-delivery-faqs.md
Labels: Review - SME, DO NOT MERGE

#6504 CHAOS-5287 Update hce versus litmus
  docs/chaos-engineering/get-started/powered-by-litmus.md
Labels: Content - chore/cleanup

#6486 CHAOS-5241 Update prerequisites.md
  docs/chaos-engineering/get-started/tutorials/prerequisites.md
Labels: Content - chore/cleanup

#6511 docs: [IAC-1870]: Update overview doc description
  docs/infra-as-code-management/get-started/overview.md
Labels: Content - chore/cleanup

#6481 CDS-92138 K8s Patch Step
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-patch-step.md
Labels: Draft, DO NOT MERGE

#6521 CD FAQs
  kb/continuous-delivery/continuous-delivery-faqs.md
Labels: DO NOT MERGE, Review - Editorial
