Repository harness/developer-hub, pull requests merged in 2025-02, with the labels that each got.

#9233 [PL-Doc] Release Notes 1.74.x
  release-notes/platform.md
Labels: Release notes

#9279 Update additional docs page for IP whitelisting.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
Labels: Content - chore/cleanup

#9213 GitOps Application Filtering Improvements
  docs/continuous-delivery/cd-integrations.md
  docs/continuous-delivery/gitops/use-gitops/manage-gitops-applications.md
Labels: Content - enhancement

#9298 Add Tango for Azure Function
  docs/continuous-delivery/deploy-srv-diff-platforms/azure/azure-function-tutorial.md
Labels: DO NOT MERGE

#9301 Output Variables on Step Failure
  docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md
Labels: Content - chore/cleanup

#9316 Change whitelist to allowlist.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
  release-notes/continuous-integration.md
Labels: Content - chore/cleanup

#9324 Bumped required versions
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
Labels: Content - chore/cleanup

#9322 Added new variable functionality to update release repo
  docs/continuous-delivery/gitops/pr-pipelines/gitops-pipeline-steps.md
Labels: Content - enhancement

#9341 [PL-Doc] Hotfix SMP-Release Notes 0.14.13
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes

#9349 Document feature flag for CI always true
  docs/continuous-integration/ci-supported-platforms.md
  docs/continuous-integration/troubleshoot-ci/ci-env-var.md
Labels: Content - chore/cleanup

#9362 Add a key concept that a harness delegate is always used for deployments
  docs/continuous-delivery/get-started/key-concepts.md
Labels: Content - enhancement

#9348 Monitored service limitation
  docs/platform/monitored-service.md
Labels: Content - chore/cleanup

#9295 docs: [IAC-3068]: Update iacm cd provisioning doc
  docs/infra-as-code-management/pipelines/operations/iacm-cd-pipeline.md
Labels: Content - enhancement, Content - chore/cleanup

#9336 docs: [IAC-3031]: Add new workspace tabs doc
  docs/infra-as-code-management/workspaces/cli-integration.md
  docs/infra-as-code-management/workspaces/cost-estimation.md
  docs/infra-as-code-management/workspaces/delete-workspace.md
  docs/infra-as-code-management/workspaces/destroy-workspaces.md
  docs/infra-as-code-management/workspaces/workspace-expressions.md
  docs/infra-as-code-management/workspaces/workspace-tabs.md
  docs/infra-as-code-management/workspaces/workspace-tempates.md
Labels: Content - enhancement

#9325 SCS: Release Notes 1.25.1
  release-notes/software-supply-chain-assurance.md
Labels: Release notes

#9376 Add note about private IP creation for pool.yml
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
Labels: Content - chore/cleanup

#9391 docs: [IAC-3120]: Update remote backend initialization doc
  docs/infra-as-code-management/pipelines/terraform-plugins.md
  docs/infra-as-code-management/remote-backends/init-configuration.md
  docs/infra-as-code-management/remote-backends/state-migration.md
  kb/reference-architectures/iacm/iacm-best-practices.md
Labels: Content - chore/cleanup

#9390 deleted excessive permission.
  docs/platform/connectors/code-repositories/git-hub-app-support.md
Labels: Content - chore/cleanup

#9294 docs: [IAC-3085]: Pre GA module registry doc updates
  docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
Labels: Content - chore/cleanup

#9402 docs: [IAC-3124]: Fix IaCM Uni broken links
  src/components/University/data/iacm-certification-developer-review-guide.md
Labels: Content - chore/cleanup

#9176 Update supported build infra docs
  docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
Labels: Content - chore/cleanup

#9413 Add CI 1.66 RN
  release-notes/continuous-integration.md
Labels: Release notes

#9418 docs: [IAC-2964]: Update docs to include pending new workspace wizard
  docs/infra-as-code-management/get-started/get-started.md
  docs/infra-as-code-management/get-started/overview.md
  docs/infra-as-code-management/workspaces/create-workspace.md
Labels: Content - enhancement

#9431 [PL-Doc] SMP release notes 0.25.3
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes, Ready to merge

#9401 [Pl-Doc] Platform Release Note 1.77.x
  release-notes/platform.md
Labels: Release notes

#9440 docs: [AH-980]: Update supported registries
  docs/artifact-registry/get-started/overview.md
  docs/artifact-registry/whats-supported.md
Labels: Content - chore/cleanup

#9442 [PL-Doc] OIDC SSO with Okta & Harness
  docs/platform/authentication/single-sign-on-sso-with-oidc.md
  docs/platform/authentication/static/auth-enabled.png
  docs/platform/authentication/static/authentication-oidc.gif
  docs/platform/authentication/static/claim-key-value-jit.png
  docs/platform/authentication/static/create-app-integration.png
  docs/platform/authentication/static/edit-for-okta-provider.png
  docs/platform/authentication/static/group-assign-okta-application.gif
  docs/platform/authentication/static/link-to-sso.gif
  docs/platform/authentication/static/newweb-oidc-app.gif
  docs/platform/authentication/static/oidc-groups-scope.png
  docs/platform/authentication/static/oidc-page-1.png
  docs/platform/authentication/static/oidc-with-discovery.png
  docs/platform/authentication/static/oidc-without-discovery.png
  docs/platform/authentication/static/okta-app-assignments.png
  docs/platform/authentication/static/okta-assign-application.gif
  docs/platform/authentication/static/okta-group-assignment.gif
  docs/platform/authentication/static/okta-login-sso.gif
  docs/platform/authentication/static/okta-user-group.png
  docs/platform/authentication/static/sign-in-method-okta.png
Labels: Content - enhancement, Review - Editorial

#9433 IAC-3150 Update workspace expression doc for improved engagement
  docs/infra-as-code-management/workspaces/workspace-expressions.md
Labels: Content - chore/cleanup

#9447 [PL-Doc] Release notes 1.78.x
  release-notes/platform.md
Labels: Release notes

#9494 docs: [IAC-3171]: Update plugin images
  docs/infra-as-code-management/pipelines/plugin-images.md
Labels: Content - chore/cleanup

#9462 CI-16113 Update Build and Push pages with FAQ.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ghcr.md
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - gap / tech debt, Content - FAQ

#9518 Remove incorrect supportability information from doc.
  docs/continuous-integration/secure-ci/configure-oidc-gcp-wif-ci-hosted.md
Labels: Content - chore/cleanup

#9544 Remove dated warnings about OIDC
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
Labels: Content - chore/cleanup

#9524 [PL-Doc] SMP RNs for 0.26.0 & 0.25.4
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes

#9534 docs: [AH-995]: Add client setup doc
  .github/CODEOWNERS
  docs/artifact-registry/manage-registries/client-setup.md
  docs/artifact-registry/manage-registries/delete-registry.md
  sidebars.ts
Labels: Content - gap / tech debt

#9554 Remove beta from IR, AR, and DBDEVOPS
  docs/database-devops/dbdevops_supported_platforms.md
  docs/database-devops/get-started/overview.md
  sidebars.ts
  src/components/Docs/ArtifactRegistry.tsx
  src/components/Docs/DatabaseDevOps.tsx
Labels: Content - deprecation / removal

#9555 Native support to handle immutable ECR repo.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
Labels: Content - enhancement

#9553 Add CI 1.68 RN.
  release-notes/continuous-integration.md
Labels: Release notes
