Repository harness/developer-hub, pull requests merged in 2025-01, with the labels that each got.

#8909 CHAOS-7199 Windows disk stress
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/experiments.ts
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/images/windows-disk-stress.png
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/static/manifests/windows-disk-stress/params.yaml
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/windows-disk-stress.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/windows/windows.md
Labels: Review - SME

#8494 CHAOS-6731 EC2 chaos for k8s and linux
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/comparison-ec2.md
  docs/chaos-engineering/use-harness-ce/chaos-faults/kubernetes/tkgi/permissions.md
Labels: Review - SME, DO NOT MERGE

#8919 [CDS-105245] Added Google Cloud Run Job step details
  docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/google-cloud-run.md
  docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/static/google-cloud-run-1.png
  docs/continuous-delivery/deploy-srv-diff-platforms/google-cloud-functions/static/google-cloud-run-job.png
Labels: Blocked / On hold

#9000 docs: [AH-860]: Update platform connector doc to support AR
  docs/platform/connectors/cloud-providers/ref-cloud-providers/docker-registry-connector-settings-reference.md
Labels: Content - gap / tech debt

#8861 docs: [IAC-2892] Move drift detection to Use IaCM
  docs/infra-as-code-management/pipelines/iacm-plugins/terraform-plugins.md
  docs/infra-as-code-management/use-iacm/drift-detection.md
  docs/infra-as-code-management/use-iacm/static/Workspace-drift-attributes.png
  docs/infra-as-code-management/use-iacm/static/Workspace-drift.png
  docs/infra-as-code-management/use-iacm/static/drift-pipeline-detected.png
  docs/infra-as-code-management/use-iacm/static/drift-pipeline.png
  docs/infra-as-code-management/use-iacm/static/plan-refresh-only.png
  docs/infra-as-code-management/use-iacm/static/provision-drift.png
  kb/reference-architectures/iacm/iacm-best-practices.md
  src/components/Docs/data/iacmData.ts
  src/components/University/data/iacm-certification-developer-review-guide.md
Labels: Content - chore/cleanup

#9029 Add warning note for deprecation timeline.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
Labels: Content - chore/cleanup

#8979 Add language for multi source apps in pr pipeline docs.
  docs/continuous-delivery/gitops/pr-pipelines/gitops-pipeline-steps.md
Labels: Blocked / On hold

#9035 CI Release Notes 1.60
  release-notes/continuous-integration.md
Labels: Release notes

#8929 [CDS-101519] Added Disable Artifact Validation
  docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
  docs/continuous-delivery/x-platform-cd-features/services/static/disable-artifact-2.png
  docs/continuous-delivery/x-platform-cd-features/services/static/disable-artifact.png
Labels: Blocked / On hold

#9074 docs: [AH-874]: Add AWS ECR selection tab
  docs/artifact-registry/manage-registries/create-registry.md
Labels: Content - enhancement

#9001 Gitops release notes 1.23.0
  release-notes/continuous-delivery.md
Labels: Blocked / On hold

#9094 CI 1.61 release notes.
  release-notes/continuous-integration.md
Labels: Release notes

#9088 docs: [AH-872]: Update CI integration to include Run and Plugin steps.
  docs/artifact-registry/platform-integrations/ci-ar-integrations.md
Labels: Content - enhancement

#9101 Add note that windows is not supported
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/run-windows-builds-in-a-kubernetes-build-infrastructure.md
Labels: Content - enhancement, Content - chore/cleanup, Content - gap / tech debt

#9102 updated versions, added haproxy
  docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
Labels: Content - chore/cleanup

#9079 update mtls support doc
  docs/continuous-integration/ci-supported-platforms.md
  docs/platform/delegates/secure-delegates/delegate-mtls-support.md
Labels: Content - chore/cleanup

#9137 docs: [IAC-2947]: Add mod reg tab content guide
  docs/infra-as-code-management/iacm-features/default-pipelines.md
  docs/infra-as-code-management/iacm-features/module-registry/_category_.json
  docs/infra-as-code-management/iacm-features/module-registry/module-registry-tabs.md
  docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
  docs/infra-as-code-management/iacm-features/module-registry/static/registered-module-instructions.png
  docs/infra-as-code-management/iacm-features/workspace-tempates.md
Labels: Content - enhancement

#9129 CI 1.62 RN
  release-notes/continuous-integration.md
Labels: Release notes

#9139 roadmap: [IAC-3004]: Update IaCM roadmap
  src/components/Roadmap/data/iacmData.ts
Labels: Content - chore/cleanup

#9143 chore: [IAC-3014]: Update codeowners for IACM and AR
  .github/CODEOWNERS
Labels: Content - chore/cleanup

#9141 docs: [IAC-3012]: Module registry tab review updates
  docs/infra-as-code-management/iacm-features/module-registry/module-registry-tabs.md
  docs/infra-as-code-management/iacm-features/module-registry/static/registered-module-instructions.png
Labels: Content - chore/cleanup

#9156 Update CI CODEOWNERS
  .github/CODEOWNERS
Labels: DO NOT MERGE

#9169 docs: [IAC-3015]: IaCM sidebar headers
  docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
  docs/infra-as-code-management/iacm-security.md
  docs/infra-as-code-management/pipelines/default-pipelines.md
  docs/infra-as-code-management/policies-governance/_category_.json
  docs/infra-as-code-management/policies-governance/opa-workspace.md
  docs/infra-as-code-management/policies-governance/terraform-plan-cost-policy.md
  docs/infra-as-code-management/use-iacm/pr-automation.md
  docs/infra-as-code-management/workspaces/workspace-tempates.md
  sidebars.js
  src/components/Docs/data/iacmData.ts
  src/components/HomepageFeatures/data/featureListData.tsx
Labels: Content - enhancement

#9157 Updated screenshot
  docs/continuous-delivery/monitor-deployments/monitor-cd-deployments.md
  docs/continuous-delivery/monitor-deployments/static/monitor-cd-deployments-21.png
Labels: Content - chore/cleanup

#9186 docs: [IAC-3035]: Merge IaCM overview and key-concepts docs
  docs/infra-as-code-management/get-started/key-concepts.md
  docs/infra-as-code-management/get-started/onboarding-guide.md
  docs/infra-as-code-management/get-started/overview.md
  docs/infra-as-code-management/pipelines/iacm-plugins/terraform-plugins.md
  docs/infra-as-code-management/pipelines/operations/approval-step.md
  docs/infra-as-code-management/pipelines/operations/drift-detection.md
  docs/infra-as-code-management/pipelines/operations/pr-automation.md
  docs/infra-as-code-management/pipelines/operations/static/add-approval-step.png
  docs/infra-as-code-management/pipelines/operations/static/approval-runtime.png
  docs/infra-as-code-management/pipelines/operations/static/drift-attributes.png
  docs/infra-as-code-management/pipelines/operations/static/drift-pipeline-detected.png
  docs/infra-as-code-management/pipelines/operations/static/drift-pipeline.png
  docs/infra-as-code-management/pipelines/operations/static/plan-refresh-only.png
  docs/infra-as-code-management/pipelines/operations/static/pr-comment.png
  docs/infra-as-code-management/pipelines/operations/static/provision-drift.png
  docs/infra-as-code-management/pipelines/operations/static/trigger.png
  docs/infra-as-code-management/pipelines/operations/static/ws-drift.png
  docs/infra-as-code-management/use-iacm/_category_.json
  docs/infra-as-code-management/workspaces/create-workspace.md
  docs/infra-as-code-management/workspaces/provision-workspace.md
  docs/infra-as-code-management/workspaces/static/create-workspace.png
  docs/infra-as-code-management/workspaces/static/new-workspace.png
  docs/infra-as-code-management/workspaces/static/select-stage.png
  docs/infra-as-code-management/workspaces/static/workspace-variables.png
  sidebars.js
  src/components/Docs/data/iacmData.ts
Labels: Content - enhancement, Content - chore/cleanup

#9134 [PL-Doc] CD - Datadog notification updates
  docs/continuous-delivery/x-platform-cd-features/cd-steps/notify-users-of-pipeline-events.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/static/datadog-api-conf.png
  docs/continuous-delivery/x-platform-cd-features/cd-steps/static/datadog-notification-1.png
Labels: Content - enhancement, Ready to merge

#9204 docs: [IAC-3041]: Update collapsible sidebar for AR and IACM
  sidebars.ts
Labels: Content - enhancement, Content - chore/cleanup

#9158 Release notes gitops version 1.24.0
  docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
  release-notes/continuous-delivery.md
Labels: Content - chore/cleanup

#9211 add demo video for event relay
  docs/platform/triggers/trigger-pipelines-using-generic-events.md
Labels: DO NOT MERGE

#9212 Add tango to docvideo
  docs/artifact-registry/platform-integrations/ci-ar-integrations.md
  src/components/DocVideo/index.tsx
Labels: DO NOT MERGE

#9232 [PL-Doc] HashiCorp JWT/OIDC Documentation
  docs/platform/secrets/secrets-management/add-hashicorp-vault.md
  docs/platform/secrets/static/harshicorp-with-delegate.gif
  docs/platform/secrets/static/harshicorp-without-delegate.gif
  docs/platform/secrets/static/harshicorp.gif
  docs/platform/secrets/static/jwt-configure.png
Labels: Content - enhancement, Content - gap / tech debt

#9234 [PL-Doc] SMP release notes 0.25.0
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes

#9219 CI 1.63 release notes
  release-notes/continuous-integration.md
Labels: Release notes
