Repository harness/developer-hub, pull requests merged in 2025-03, with the labels that each got.

#9538 [PL-Doc] Release notes for 1.79.x
  release-notes/platform.md
Labels: Release notes

#9541 docs: [IAC-3227]: Add module registry structure and submodule usage docs
  docs/infra-as-code-management/iacm-features/module-registry/module-registry-code-structure.md
  docs/infra-as-code-management/iacm-features/module-registry/module-registry-tabs.md
  docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
  docs/infra-as-code-management/iacm-features/module-registry/root-sub-module-usage.md
Labels: Content - gap / tech debt

#9570 Fix IaCM release notes broken link.
  release-notes/infrastructure-as-code-management.md
Labels: Content - chore/cleanup

#9567 docs: [IAC-3243]: Make roadmap tiles clickable
  docs/infra-as-code-management/iacm-features/module-registry/module-registry-code-structure.md
  docs/infra-as-code-management/workspaces/worksace-statuses.md
  docs/infra-as-code-management/workspaces/workspace-tabs.md
  docs/infra-as-code-management/workspaces/workspace-tempates.md
  src/components/Roadmap/data/iacmData.ts
Labels: Content - enhancement

#9619 Redis NOAuth docs added to troubleshooting
  docs/continuous-delivery/gitops/troubleshooting.md
Labels: Content - FAQ

#9634 CI 1.70 Release Notes
  release-notes/continuous-integration.md
Labels: Release notes

#9576 Added background task monitoring step
  kb/continuous-integration/articles/parallel-step-for-logging.md
Labels: Content - chore/cleanup

#9682 Update to 1.70 RN.
  release-notes/continuous-integration.md
Labels: Release notes

#9678 Docs update for CI-16538
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
Labels: Content - chore/cleanup

#9684 Add warning for release names to be unique.
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/kubernetes-releases-and-versioning.md
Labels: Content - chore/cleanup

#9711 CI-16383 update and remove long GA note.
  docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase.md
  docs/continuous-integration/use-ci/codebase-configuration/git-clone-step.md
Labels: Content - enhancement

#9574 Release notes 1.27
  docs/continuous-delivery/gitops/connect-and-manage/install-a-harness-git-ops-agent.md
  release-notes/continuous-delivery.md
Labels: Content - deprecation / removal

#9698 Ci get started revamp
  docs/continuous-integration/get-started/onboarding-guide.md
Labels: Content - enhancement

#9702 docs: [IAC-3329]: Update module registry local auth
  docs/infra-as-code-management/iacm-features/module-registry/root-sub-module-usage.md
Labels: Content - gap / tech debt

#9578 Add OIDC support to download for GCS
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-gcs-step-settings.md
Labels: Content - enhancement

#9731 Update AWS OIDC connector limitations
  docs/continuous-delivery/cd-infrastructure/cloudformation-infra/cloud-formation-provisioning-with-harness.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
  docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-provisioning-with-harness.md
  docs/continuous-delivery/cd-infrastructure/terragrunt-howtos.md
  docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot-deployment.md
  docs/continuous-delivery/deploy-srv-diff-platforms/serverless/serverless-lambda-cd-quickstart.md
  docs/continuous-delivery/deploy-srv-diff-platforms/traditional/ssh-ng.md
  docs/continuous-delivery/deploy-srv-diff-platforms/traditional/win-rm-tutorial.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
Labels: Blocked / On hold

#9770 docs: [IAC-3370]: Update State Migration doc
  docs/infra-as-code-management/remote-backends/state-migration.md
Labels: Content - chore/cleanup

#9777 updated Harness AI roadmap
  src/components/Roadmap/data/aidaData.ts
Labels: Content - enhancement

#9837 Added support for other secret managers.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
Labels: Content - enhancement, Content - deprecation / removal

#9839 Update paths to be absolute not relative. Fix dead links
  docs/continuous-integration/get-started/onboarding-guide.md
Labels: Content - chore/cleanup

#9822 [PL-Doc] Delegate RN 25.03.85503
  release-notes/delegate.md
Labels: Release notes

#9821 [PL-Doc] Platform Release Notes 1.82.xx
  release-notes/platform.md
Labels: Release notes

#9841 Add local files as build dependencies
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-jfrog.md
Labels: Content - enhancement

#9864 CI Release Notes 1.72
  release-notes/continuous-integration.md
Labels: Release notes

#9842 added payload conditions for push tag triggers
  docs/platform/triggers/trigger-pipeline-on-tag-event.md
Labels: Content - enhancement

#9867 Changes per CI-16202
  docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
Labels: Content - gap / tech debt
