Repository harness/developer-hub, pull requests merged in 2025-05, with the labels that each got.

#10164 [PL-Doc] Platform Release 1.87.x
  release-notes/platform.md
Labels: Release notes

#10154 [PIPE-24711] Feature: Improved Git Synchronization for Pipeline Execu…
  docs/platform/git-experience/git-experience-overview.md
Labels: Content - enhancement

#10247 docs: [IAC-3628]: Update delete action warning
  docs/infra-as-code-management/pipelines/operations/pr-automation.md
  docs/infra-as-code-management/workspaces/delete-workspace.md
  docs/infra-as-code-management/workspaces/destroy-workspaces.md
Labels: Content - chore/cleanup, Content - gap / tech debt

#10246 [IaCM]: Roadmap update for IaCM
  src/components/Roadmap/data/iacmData.ts
Labels: DO NOT MERGE, Roadmap

#10250 docs: [IAC-3502]: Elaborate on drift detection doc
  docs/infra-as-code-management/pipelines/operations/drift-detection.md
  docs/infra-as-code-management/pipelines/terraform-plugins.md
Labels: Content - gap / tech debt

#10241 docs: [IAC-3538]: Add release note IAC-Server version 1.143
  release-notes/infrastructure-as-code-management.md
Labels: Release notes

#10277 docs: [IAC-3595]: Update workspace settings resources tab details
  docs/infra-as-code-management/workspaces/workspace-tabs.md
Labels: Content - enhancement, Blocked / On hold

#10300 rn: [IAC-3570]: IAC Server Release Notes v1.145.0
  release-notes/infrastructure-as-code-management.md
Labels: Release notes

#10145 [Pipe-25180] Feature: Custom Notification Template Phase 2
  docs/platform/templates/customized-notification-template.md
  docs/platform/templates/static/customised-notifiy-1.png
  docs/platform/templates/static/notification-referenced-by.png
  docs/platform/templates/static/notification-temp.png
  docs/platform/templates/static/notification-template-1.png
  docs/platform/templates/static/notification-template-3.png
  docs/platform/templates/static/notification-template-audit.png
  docs/platform/templates/static/yaml-notification.png
Labels: Content - enhancement

#10308 Changes per CI-17489
  docs/continuous-integration/secure-ci/authenticate-gcp-key-in-run-step.md
Labels: Content - gap / tech debt

#10322 docs: [IAC-3726]: Update Module Registry to specify git tag requirement
  docs/infra-as-code-management/iacm-features/module-registry/module-registry-code-structure.md
  docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
  docs/infra-as-code-management/iacm-features/module-registry/root-sub-module-usage.md
Labels: Content - gap / tech debt

#10290 docs: [AH-1307]: Update HAR Whats Supported packages
  docs/artifact-registry/whats-supported.md
Labels: Content - gap / tech debt

#10325 Harness CI 1.79 Release Notes
  release-notes/continuous-integration.md
Labels: Release notes

#10330 Add Harness MCP Server docs.
  docs/platform/harness-aida/harness-mcp-server.md
Labels: Content - gap / tech debt

#10355 Remove 'Coming Soon' text.
  docs/platform/harness-aida/harness-mcp-server.md
Labels: Content - chore/cleanup

#10296 Add Git LFS docs.
  docs/code-repository/work-in-repos/git-lfs.md
  docs/code-repository/work-in-repos/static/git-lfs-view.png
Labels: Content - gap / tech debt

#10364 Typo, grammar, and style fixes.
  docs/platform/harness-aida/ai-devops.md
Labels: Content - chore/cleanup

#10375 Dewan ci17216
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
Labels: Content - gap / tech debt

#10387 CI 1.80 RN.
  release-notes/continuous-integration.md
Labels: Release notes

#10352 [PL-Doc]System Release Note 1.90x
  release-notes/platform.md
Labels: Release notes

#10353 Delegate Release Notes 25.05.85900
  release-notes/delegate.md
Labels: Release notes

#10299 docs: [AH-1310]: Add new Generic quickstart
  docs/artifact-registry/content/generic-quickstart.md
  docs/artifact-registry/supported-formats.md
  static/provider-logos/generic-logo.svg
Labels: Content - enhancement

#10362 FMEPRD-151 Add April 16 Release Note
  release-notes/feature-management-experimentation.md
Labels: Review - PM

#10411 Add Harness AI Code agent video.
  docs/platform/harness-aida/code-agent.md
Labels: Content - gap / tech debt

#10408 CODE REPO 1.41 and 1.42 Release Notes
  release-notes/code-repository.md
Labels: Release notes

#10303 Add Experimentation Documentation
  docs/feature-management-experimentation/60-experimentation/events/index.md
  docs/feature-management-experimentation/60-experimentation/events/setup.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/analyzing-experiment-results/attribution-and-exclusion.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/analyzing-experiment-results/dimensional-analysis.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/analyzing-experiment-results/health-check.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/analyzing-experiment-results/index.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/analyzing-experiment-results/sample-ratio-check.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/index.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/reallocate-traffic.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/viewing-experiment-results/index.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/viewing-experiment-results/metric-calculation-schedule.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/viewing-experiment-results/metric-details-and-trends.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/viewing-experiment-results/metrics-impact-cards.md
  docs/feature-management-experimentation/60-experimentation/experiment-results/viewing-experiment-results/randomization-and-stickiness.md
  docs/feature-management-experimentation/60-experimentation/key-concepts/fixed-horizon.md
  docs/feature-management-experimentation/60-experimentation/key-concepts/frequentist-vs-bayesian.md
  docs/feature-management-experimentation/60-experimentation/key-concepts/index.md
  docs/feature-management-experimentation/60-experimentation/key-concepts/multiple-comparison-correction.md
  docs/feature-management-experimentation/60-experimentation/key-concepts/p-value.md
  docs/feature-management-experimentation/60-experimentation/key-concepts/sample-size-calculator.md
  docs/feature-management-experimentation/60-experimentation/key-concepts/statistical-significance.md
  docs/feature-management-experimentation/60-experimentation/metrics/alert-policies.md
  docs/feature-management-experimentation/60-experimentation/metrics/categories/guardrail-metrics.md
  docs/feature-management-experimentation/60-experimentation/metrics/categories/index.md
  docs/feature-management-experimentation/60-experimentation/metrics/index.md
  docs/feature-management-experimentation/60-experimentation/metrics/setup/capping.md
  docs/feature-management-experimentation/60-experimentation/metrics/setup/filtering.md
  docs/feature-management-experimentation/60-experimentation/metrics/setup/index.md
  docs/feature-management-experimentation/60-experimentation/overview.md
  docs/feature-management-experimentation/60-experimentation/setup/a-a-testing.md
  docs/feature-management-experimentation/60-experimentation/setup/anonymous-and-logged-in-users.md
  docs/feature-management-experimentation/60-experimentation/setup/experiment-hypothesis.md
  docs/feature-management-experimentation/60-experimentation/setup/experiment-scope.md
  docs/feature-management-experimentation/60-experimentation/setup/experiment-settings.md
  docs/feature-management-experimentation/60-experimentation/setup/index.md
  docs/feature-management-experimentation/60-experimentation/setup/metric-selection/guardrail-metrics.md
  docs/feature-management-experimentation/60-experimentation/setup/metric-selection/index.md
  docs/feature-management-experimentation/60-experimentation/setup/metric-selection/key-metrics.md
  docs/feature-management-experimentation/60-experimentation/setup/metric-selection/static/key-metrics.png
  docs/feature-management-experimentation/60-experimentation/setup/metric-selection/static/supporting-metrics.png
  docs/feature-management-experimentation/60-experimentation/setup/metric-selection/supporting-metrics.md
  docs/feature-management-experimentation/60-experimentation/setup/mutually-exclusive-experiments.md
  docs/feature-management-experimentation/60-experimentation/setup/power-analysis.md
  docs/feature-management-experimentation/shared/metrics/setup/index.md
  sidebars.ts
  src/components/Docs/data/featureManagementExperimentationData.ts
Labels: DO NOT MERGE, Review - PM
