Repository harness/developer-hub, pull requests merged in 2025-06, with the labels that each got.

#10469 Clarify ECR authentication for private repositories in Docker connector setup
  docs/platform/connectors/artifact-repositories/connect-to-harness-container-image-registry-using-docker-connector.md
Labels: Content - gap / tech debt

#10492 CI RN 1.82
  release-notes/continuous-integration.md
Labels: Release notes

#10528 IAC-3886 Remove workspace template pending banners
  docs/infra-as-code-management/workspaces/workspace-tempates.md
Labels: Content - chore/cleanup

#10522 1.43 and 1.44 Release Notes for Code Repo.
  release-notes/code-repository.md
Labels: Release notes

#10523 Add missing ticket to CI 1.80 RN.
  release-notes/continuous-integration.md
Labels: Content - gap / tech debt

#10520 Rename account.harnessImage to generic image connector.
  docs/continuous-integration/development-guides/ci-c.md
  docs/continuous-integration/development-guides/ci-dotnet.md
  docs/continuous-integration/development-guides/ci-golang.md
  docs/continuous-integration/development-guides/ci-java.md
  docs/continuous-integration/development-guides/ci-nodejs.md
  docs/continuous-integration/development-guides/ci-python.md
  docs/continuous-integration/development-guides/ci-ruby.md
  docs/continuous-integration/development-guides/ci-windows.md
  docs/continuous-integration/development-guides/mlops/mlops-azureml.md
  docs/continuous-integration/development-guides/mlops/mlops-databricks.md
  docs/continuous-integration/development-guides/mlops/mlops-mlflow.md
  docs/continuous-integration/development-guides/mlops/mlops-sagemaker.md
  docs/continuous-integration/development-guides/mlops/mlops-vertexai.md
  docs/continuous-integration/development-guides/mobile/android.md
  docs/continuous-integration/migration-guides/migrating-from-circleci.md
  docs/continuous-integration/migration-guides/migrating-from-githubactions.md
  docs/continuous-integration/migration-guides/migrating-from-gitlab.md
  docs/continuous-integration/secure-ci/gcp-oidc-token-plugin.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/artifacts-tab.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-nonroot.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-multi-arch.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/drone-email-plugin.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/migrate-images.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-gcs-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-s3.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-sonatype-nexus.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-dotnet-to-azure-artifacts.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-helm-chart.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-azure.md
  docs/continuous-integration/use-ci/codebase-configuration/clone-and-process-multiple-codebases-in-the-same-pipeline.md
  docs/continuous-integration/use-ci/codebase-configuration/scm-status-checks.md
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
  docs/continuous-integration/use-ci/manage-dependencies/ci-localstack-background-step.md
  docs/continuous-integration/use-ci/manage-dependencies/ci-saucelabs-background-step.md
  docs/continuous-integration/use-ci/manage-dependencies/health-check-services.md
  docs/continuous-integration/use-ci/manage-dependencies/multiple-postgres.md
  docs/continuous-integration/use-ci/run-step-settings.md
  docs/continuous-integration/use-ci/run-tests/ci-fastapi-test.md
  docs/continuous-integration/use-ci/run-tests/code-coverage.md
  docs/continuous-integration/use-ci/run-tests/run-tests-in-ci.md
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-csharp.md
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-java-kotlin-scala.md
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-python.md
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-ruby.md
  docs/continuous-integration/use-ci/run-tests/tests-v2.md
  docs/continuous-integration/use-ci/run-tests/viewing-tests.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/public-docker-images.md
  docs/continuous-integration/use-ci/use-drone-plugins/ci-jira-int-plugin.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-drone-plugin-in-ci.md
  docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie.md
Labels: Content - gap / tech debt

#10446 Add Maven config for BI.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
Labels: Content - enhancement

#10441 docs: [IAC-3527]: Add use backends doc
  docs/infra-as-code-management/remote-backends/use-backends.md
Labels: Content - enhancement, Content - gap / tech debt

#10563 CI 1.83 RN.
  release-notes/continuous-integration.md
Labels: Release notes

#10587 Add better explanation for plugin output variables.
  docs/continuous-integration/use-ci/use-drone-plugins/plugin-step-settings-reference.md
Labels: Content - gap / tech debt

#10593 docs: [AH-1428]: Add python quickstart
  docs/artifact-registry/content/python-quickstart.md
  docs/artifact-registry/supported-formats.md
Labels: Content - enhancement

#10602 docs: [CCM-23666]: Clean New to CCM section
  docs/cloud-cost-management/faq.md
  docs/cloud-cost-management/get-started/overview.md
  docs/cloud-cost-management/get-started/static/latest_overview.png
  docs/cloud-cost-management/shared/ccm-supported-platforms.md
  docs/cloud-cost-management/whats-supported.md
  docs/self-managed-enterprise-edition/install/install-using-helm.md
  kb/cloud-cost-management/cloud-cost-management-faqs.md
  sidebars.ts
  src/components/Docs/data/cloudCostManagementData.ts
  src/components/Docs/data/platformData.ts
  src/components/HomepageFeatures/data/featureListData.tsx
  src/components/University/data/ccm-certification-admin-review-guide.md
Labels: Content - chore/cleanup

#10621 docs: [IAC-3942]: Add approval resources uage admonition
  docs/infra-as-code-management/get-started/get-started.md
  docs/infra-as-code-management/pipelines/operations/approval-step.md
Labels: Content - gap / tech debt

#10452 Add webhook execution info per CODE-2252.
  docs/code-repository/config-repos/assets/webhook-execution.png
  docs/code-repository/config-repos/webhooks.md
Labels: Content - enhancement

#10454 Add the required FF for public repos.
  docs/code-repository/config-repos/create-repo.md
Labels: Content - gap / tech debt

#10668 Add documentation for S3 support in Harness Open Source artifact registry
  docs/open-source/registries/artifacts.md
Labels: Content - gap / tech debt

#10669 CI 1.84 release notes.
  release-notes/continuous-integration.md
Labels: Release notes

#10697 docs: [IAC-3990]: Add Apply Needed status description
  docs/infra-as-code-management/workspaces/worksace-statuses.md
Labels: Content - gap / tech debt

#10605 Add changes per CI-17862
  docs/continuous-integration/use-ci/run-tests/static/parallelism-test-intelligence.png
  docs/continuous-integration/use-ci/run-tests/ti-overview.md
Labels: Content - gap / tech debt

#10601 Changes per CI-12928
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
Labels: Content - gap / tech debt

#10588 Update Run step to native Plugin step for git revert.
  docs/continuous-integration/development-guides/security/git-revert-from-pr.md
  docs/continuous-integration/use-ci/codebase-configuration/git-revert-commit.md
Labels: Content - gap / tech debt

#10708 Make delegate requirement more prominent.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
Labels: Content - gap / tech debt
