Repository harness/developer-hub, pull requests merged in 2025-09, with the labels that each got.

#11438 Key event trigger automation
  docs/ai-sre/runbooks/create-runbook.md
  docs/ai-sre/runbooks/static/dynamic-parameter-selection.png
  docs/ai-sre/runbooks/static/key-event-dynamic-input.png
  docs/ai-sre/runbooks/static/key-event-integration.png
  docs/ai-sre/runbooks/static/key-event-trigger.png
Labels: Content - enhancement

#11430 docs: Add FF sidebars and deprecation notice
  sidebars.ts
  src/components/Docs/FeatureFlags.tsx
  src/components/Docs/data/featureFlagsData.ts
  src/components/HomepageFeatures/data/featureListData.tsx
Labels: Content - chore/cleanup, Content - gap / tech debt

#11328 Update per CODE-4066
  docs/code-repository/config-repos/rules.md
Labels: Content - chore/cleanup

#11442 Add artifact-metadata-publisher environment variables and k8s flow details to CI artifacts tab docs
  docs/continuous-integration/use-ci/build-and-upload-artifacts/artifacts-tab.md
Labels: Content - chore/cleanup

#11423 Enable Path Style Support for Cache Intelligence S3 via Stage Variable per CI-17982
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
Labels: Content - chore/cleanup

#11071 Update per CI-18239 - step5 only
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
Labels: Content - gap / tech debt

#11347 Point to the correct Linux Ubuntu 2404 image.
  docs/platform/references/harness-cloud-vm-images.md
Labels: Content - chore/cleanup

#11466 Add S3 bucket encryption policy guidance for Save/Restore Cache from S3
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
Labels: Content - enhancement, Content - chore/cleanup

#11448 Fix inconsistency in BI messaging.
  docs/continuous-integration/use-ci/harness-ci-intelligence.md
Labels: Content - chore/cleanup

#11420 docs: [AH-1795]: Add new Hugging Face AR guide
  docs/artifact-registry/content/supported-formats/hugging-face-quickstart.md
  docs/artifact-registry/get-started/quickstart.md
  static/provider-logos/hugging-face-logo.svg
Labels: Content - enhancement

#11504 Remove Build and Push to GCR page and its references. Added redirect.
  archive/redirects/client-redirect-netlify-format-aug-23-2023.txt
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push-nonroot.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gcr.md
  docs/continuous-integration/use-ci/use-drone-plugins/explore-ci-plugins.md
  docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
  llms.txt
Labels: Content - chore/cleanup

#11425 Update PodSpec Overlay page to include spec.containers overrides
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/customize-podspec.md
Labels: Content - enhancement

#11334 Add required setting from drone email plugin.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/drone-email-plugin.md
Labels: Content - chore/cleanup

#11503 docs: [IAC-4477]: Update workspace template steps
  docs/infra-as-code-management/manage-projects/connectors-variables.md
  docs/infra-as-code-management/workspaces/create-workspace.md
  docs/infra-as-code-management/workspaces/delete-workspace.md
  docs/infra-as-code-management/workspaces/workspace-templates.md
  docs/internal-developer-portal/environment-management/get-started.md
  docs/internal-developer-portal/environment-management/overview.md
  src/components/Roadmap/data/iacmData.ts
Labels: Content - chore/cleanup, Content - gap / tech debt

#11569 Document preserveMetadata flag for Save/Restore Cache
  docs/continuous-integration/shared/preserve-metadata.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-azure.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
Labels: Content - enhancement

#11536 Update note that TI supports venv for Python
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-python.md
Labels: Content - enhancement, Content - chore/cleanup
