Repository harness/developer-hub, pull requests merged in 2025-07, with the labels that each got.

#10788 docs: [AH-1497]: Add RPM quickstart supporting YUM and DNF
  docs/artifact-registry/content/supported-formats/rpm-quickstart.md
  docs/artifact-registry/supported-formats.md
  static/provider-logos/rpm-logo.svg
Labels: Content - enhancement

#10782 IR-1617: Publish SRM autorollback doc on HDH
  docs/service-reliability-management/manage-slo/automated-deployment-rollback.md
  docs/service-reliability-management/manage-slo/static/assign-health-source.png
  docs/service-reliability-management/manage-slo/static/cd-environment.png
  docs/service-reliability-management/manage-slo/static/configure-health-source.png
  docs/service-reliability-management/manage-slo/static/deployment-pipeline.png
  docs/service-reliability-management/manage-slo/static/error-budget-policy.png
  docs/service-reliability-management/manage-slo/static/new-notification-rollback.png
  docs/service-reliability-management/manage-slo/static/nginx-deployment-manifest.png
  docs/service-reliability-management/manage-slo/static/nginx-deployment-service.png
  docs/service-reliability-management/manage-slo/static/setup-monitored-service.png
  docs/service-reliability-management/manage-slo/static/setup-slo.png
  docs/service-reliability-management/manage-slo/static/verify-rollback.png
  src/components/Docs/ServiceReliabilityManagement.tsx
Labels: Content - enhancement

#10761 CI 1.85 release notes.
  release-notes/continuous-integration.md
Labels: Release notes

#10819 Fix broken FAQ link.
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - chore/cleanup

#10683 Changes per CODE-3659
  docs/code-repository/pull-requests/prs-of-interest.md
  docs/code-repository/pull-requests/static/pr-dashboard.png
  docs/code-repository/pull-requests/static/pr-overview.png
Labels: Content - gap / tech debt

#10728 Change per CI-17750
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - gap / tech debt

#10735 Update FAQ on HashiCorp Vault for Harness CI.
  kb/continuous-integration/continuous-integration-faqs.md
Labels: Content - gap / tech debt

#10909 Updates based on CI-18281
  docs/continuous-integration/secure-ci/secure-connect.md
Labels: Content - chore/cleanup

#10822 [PL-Doc] SMP release notes 0.30.x
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes

#10918 Add reusable guide for SSH key usage during Docker builds
  docs/continuous-integration/shared/ssh-during-docker-build.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-acr.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-jfrog.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ecr-step-settings.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-gar.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-ghcr.md
Labels: Content - gap / tech debt

#10922 Link examples for supported runtime environments.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
Labels: Content - chore/cleanup

#10935 CI 1.87 Release Notes and addressing previous review comments.
  docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/customize-podspec.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-azure.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-a-ci-build-infrastructure-in-google-cloud-platform.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/define-macos-build-infra-with-anka-registry.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
  docs/continuous-integration/use-ci/use-drone-plugins/ci-bitrise-plugin.md
  docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
  release-notes/continuous-integration.md
Labels: Release notes

#10939 Add BuildKit self-signed cert configuration for Dockerfile builds usi…
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-registry.md
  docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates.md
Labels: Content - gap / tech debt

#10865 Servicenow Integration with AI SRE and update redirects from incident response
  _server-redirects
  docs/ai-sre/ai-agent/ai-agent.md
  docs/ai-sre/alerts/alert-rules.md
  docs/ai-sre/alerts/alerts.md
  docs/ai-sre/alerts/integrations.md
  docs/ai-sre/alerts/webhooks.md
  docs/ai-sre/change/change.md
  docs/ai-sre/get-started/overview.md
  docs/ai-sre/incidents/incident-fields.md
  docs/ai-sre/incidents/incident-templates.md
  docs/ai-sre/incidents/incident-workflows.md
  docs/ai-sre/incidents/incidents.md
  docs/ai-sre/oncall/oncall.md
  docs/ai-sre/resources/ai-sre-best-practices.md
  docs/ai-sre/resources/ai-sre-security.md
  docs/ai-sre/resources/faq.md
  docs/ai-sre/resources/ir-security.md
  docs/ai-sre/resources/whats-supported.md
  docs/ai-sre/runbooks/configure-authentication.md
  docs/ai-sre/runbooks/configure-incident-fields.md
  docs/ai-sre/runbooks/configure-project-connectors.md
  docs/ai-sre/runbooks/create-runbook.md
  docs/ai-sre/runbooks/integrations/harness-pipelines.md
  docs/ai-sre/runbooks/integrations/jira.md
  docs/ai-sre/runbooks/integrations/servicenow.md
  docs/ai-sre/runbooks/integrations/slack.md
  docs/ai-sre/runbooks/integrations/static/create-integration.png
  docs/ai-sre/runbooks/integrations/static/payload-configuration.png
  docs/ai-sre/runbooks/integrations/static/test-url.png
  docs/ai-sre/runbooks/integrations/teams.md
  docs/ai-sre/runbooks/integrations/zoom.md
  docs/ai-sre/runbooks/runbooks.md
  sidebars.ts
Labels: Content - enhancement

#10875 docs: [AH-1526]: Clarify upstream proxy naming convention
  docs/artifact-registry/ar-best-practices.md
Labels: Content - gap / tech debt

#10946 Add tag rules.
  docs/code-repository/config-repos/rules.md
Labels: Content - enhancement

#11001 Replace platform archi image with new one.
  docs/platform/delegates/delegate-concepts/static/harness-platform-architecture-00.png
  docs/platform/get-started/static/harness-platform-architecture-00.png
Labels: Content - chore/cleanup

#10698 docs: [IAC-3994]: Update create workspace docs
  docs/infra-as-code-management/get-started/get-started.md
  docs/infra-as-code-management/workspaces/create-workspace.md
Labels: Content - chore/cleanup

#11032 docs: CCM update Get Started right TOC
  docs/cloud-cost-management/content/get-started/aws-quickstart.md
  docs/cloud-cost-management/content/get-started/gcp-quickstart.md
  docs/cloud-cost-management/content/get-started/kubernetes-quickstart.md
  docs/cloud-cost-management/get-started/get-started.md
Labels: Content - chore/cleanup

#10969 Add guidance to exclude Build and Cache Intel directories from Apache…
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
  docs/continuous-integration/use-ci/run-tests/tests-v2.md
Labels: Content - gap / tech debt

#11051 Update troubleshooting sections for BI,TI,CI.
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-intelligence.md
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
  docs/continuous-integration/use-ci/run-tests/tests-v2.md
Labels: Content - chore/cleanup

#10968 Add up to date list of CI images including BuildX
  docs/continuous-integration/use-ci/set-up-build-infrastructure/harness-ci.md
Labels: Content - gap / tech debt

#11080 CI 1.89 RN
  release-notes/continuous-integration.md
Labels: Release notes

#10910 Add GitHub App Token Plugin Doc and Cross-Link from Existing PAT Article
  docs/continuous-integration/secure-ci/github-app-token-in-harness.md
  kb/continuous-integration/articles/github-app-pat-dispenser.md
Labels: Content - gap / tech debt
