Repository harness/developer-hub, pull requests merged in 2025-04, with the labels that each got.

#9894 docs: [IAC-3416]: Remove execution history from workspace settings
  docs/infra-as-code-management/workspaces/workspace-tabs.md
Labels: Content - chore/cleanup

#9631 docs: [AH-1076]: Artifact registry security scanner config
  docs/artifact-registry/platform-integrations/security-integrations/_category_.json
  docs/artifact-registry/platform-integrations/security-integrations/ar-security.md
  docs/artifact-registry/platform-integrations/security-integrations/ssd-ar-integrations.md
Labels: Content - enhancement, Content - gap / tech debt

#9905 Add redirect to fix broken link from product tooltip.
  docs/open-source/pipelines/overview.md
Labels: Content - chore/cleanup

#9836 [PL-Doc] SMP RN 0.27.0
  release-notes/self-managed-enterprise-edition.md
Labels: Release notes

#9900 [PL-Doc] Platform RN 1.83.x
  release-notes/platform.md
Labels: Release notes

#9848 Update "Harness AI Code Assistant" to "Harness AI Code Agent"
  docs/platform/harness-aida/aida-overview.md
  docs/platform/harness-aida/code-agent.md
Labels: Content - chore/cleanup

#9931 Update per https://harness.atlassian.net/browse/CI-16943
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-without-push.md
Labels: Content - gap / tech debt

#9920 Add CI 1.73 release notes.
  release-notes/continuous-integration.md
Labels: Release notes

#9904 Add note regarding dynamic branch population when creating a new pipeline.
  docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
Labels: Content - enhancement

#9937 Add missing FF for CI-15398
  release-notes/continuous-integration.md
Labels: Release notes

#9798 [PL-Doc] Delegate on Google Cloud Run
  docs/platform/delegates/install-delegates/install-delegate-on-google-cloud-run.md
  docs/platform/delegates/install-delegates/static/cloud-run-configure.png
  docs/platform/delegates/install-delegates/static/configure-container-vol-security.png
  docs/platform/delegates/install-delegates/static/container-image-url.png
  docs/platform/delegates/install-delegates/static/delegate-status.png
  docs/platform/delegates/install-delegates/static/deploy-container.gif
  docs/platform/delegates/install-delegates/static/environment-variables.gif
  docs/platform/delegates/install-delegates/static/health-check.png
Labels: Review - SME, DO NOT MERGE

#9972 docs: [IAC-3374]: Add updated module registry testing doc
  docs/infra-as-code-management/iacm-features/module-registry/module-registry-testing.md
  docs/infra-as-code-management/iacm-features/module-registry/module-registry.md
Labels: Content - enhancement, Blocked / On hold

#9895 docs: [IAC-2903]: Add tfvar jexl support info panels
  docs/infra-as-code-management/remote-backends/state-migration.md
  docs/infra-as-code-management/workspaces/create-workspace.md
Labels: Content - gap / tech debt

#9958 Revised explanation for envDockerSecrets.
  docs/continuous-integration/shared/build-and-push-runtime-flags.md
Labels: Content - chore/cleanup

#9976 Update to early access features and remove GA table.
  docs/continuous-integration/ci-supported-platforms.md
Labels: Content - chore/cleanup

#9984 docs: [IAC-3480]: Add workspace configuration advanced option descriptions
  docs/infra-as-code-management/workspaces/workspace-tabs.md
Labels: Content - enhancement, Content - gap / tech debt

#9957 Update note re: dynamic branch selection.
  docs/continuous-integration/use-ci/prep-ci-pipeline-components.md
Labels: Content - chore/cleanup

#9960 Remove GCR reference.
  docs/continuous-integration/secure-ci/configure-oidc-gcp-wif-ci-hosted.md
  docs/continuous-integration/secure-ci/static/build-and-push-gar-step-logs.png
  docs/continuous-integration/secure-ci/static/oidc-build-and-push-gar.png
  docs/continuous-integration/shared/build-and-push-runtime-flags.md
  docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-upload-an-artifact.md
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
  docs/continuous-integration/use-ci/run-step-settings.md
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-csharp.md
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-java-kotlin-scala.md
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-python.md
  docs/continuous-integration/use-ci/run-tests/tests-v1/ti-for-ruby.md
Labels: Content - chore/cleanup, DO NOT MERGE

#9994 Remove front matter from partials.
  docs/continuous-integration/shared/enhanced-output-variables.md
  docs/continuous-integration/shared/output-var.md
Labels: Content - chore/cleanup

#9987 [PL-Doc] Delegate 25.04.85601
  release-notes/delegate.md
Labels: Release notes

#9985 [PL-Doc] RN for PL 1.84.x
  release-notes/platform.md
Labels: Release notes

#10002 FME release note - Append impression properties
  release-notes/feature-management-experimentation.md
Labels: Release notes

#10015 Add info on how to enable semantic search.
  docs/code-repository/work-in-repos/semantic-search.md
Labels: Content - chore/cleanup

#9999 Update to previous changes for CI-16272
  docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-azure.md
  docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs.md
  docs/continuous-integration/use-ci/caching-ci-data/saving-cache.md
Labels: Content - chore/cleanup

#9819 docs: [IAC-3191]: Update best practices re approvals
  docs/infra-as-code-management/iacm-best-practices.md
Labels: Content - gap / tech debt

#10027 [CDS-106825] Added CD faqs
  docs/continuous-delivery/deploy-srv-diff-platforms/helm/helm-faqs.md
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/kubernetes-faqs.md
  docs/continuous-delivery/verify/continuous-verification-faqs.md
  docs/continuous-delivery/x-platform-cd-features/cd-steps/cd-steps-faqs.md
  docs/continuous-delivery/x-platform-cd-features/services/cd-artifact-sources-faqs.md
Labels: Content - FAQ

#10057 docs: [IAC-3544]: Add pending release banners to workspace templates
  docs/infra-as-code-management/workspaces/workspace-tempates.md
Labels: Content - chore/cleanup

#10043 CI 1.75 RN.
  release-notes/continuous-integration.md
Labels: Release notes

#10060 Remove limitations on auth methods.
  docs/platform/settings/default-settings.md
Labels: Content - chore/cleanup

#10076 docs: [IAC-3543]: Minor doc fixes plus Tango guide adjustments
  docs/infra-as-code-management/get-started/get-started.md
  docs/infra-as-code-management/iacm-features/module-registry/module-registry-testing.md
Labels: Content - enhancement, Content - chore/cleanup

#10029 Release Notes: Add server 1.26.1 release notes
  release-notes/infrastructure-as-code-management.md
Labels: Release notes

#10087 Add trigger event conditions for PRs.
  docs/continuous-integration/use-ci/run-tests/ti-overview.md
Labels: Content - gap / tech debt

#10045 [PL-Doc] Release notes 1.85.x
  release-notes/platform.md
Labels: Release notes

#10101 Update TI docs for specific trigger steps.
  docs/continuous-integration/use-ci/run-tests/tests-v2.md
  docs/continuous-integration/use-ci/run-tests/ti-overview.md
Labels: Content - gap / tech debt

#10109 Changes per CI-17233
  docs/continuous-integration/use-ci/codebase-configuration/git-clone-step.md
Labels: Content - gap / tech debt

#10111 feature: Dynamic markdown selector component
  src/components/DynamicMarkdownSelector/DynamicMarkdownSelector.css
  src/components/DynamicMarkdownSelector/DynamicMarkdownSelector.tsx
Labels: Content - enhancement

#10126 docs: [IAC-3581]: Reinstate remote backend init configuration
  docs/infra-as-code-management/remote-backends/init-configuration.md
Labels: Content - gap / tech debt

#10121 [CDS-109184] CD release notes 1.86
  docs/continuous-delivery/cd-integrations.md
  release-notes/continuous-delivery.md
Labels: Release notes

#10119 [PL-Doc] Delegate release notes 25.04.85701
  release-notes/delegate.md
Labels: Release notes

#10123 feature: Add InLine TOC and URL hash for deep linking
  src/components/DynamicMarkdownSelector/DynamicMarkdownSelector.css
  src/components/DynamicMarkdownSelector/DynamicMarkdownSelector.tsx
Labels: Content - enhancement

#10130 docs: [IAC-3524]: Add IaCM Looker Dashboard doc
  docs/infra-as-code-management/reports-insights/dashboards.md
Labels: Content - enhancement

#9915 docs: [AH-1034]: Add new AR webhooks doc
  docs/artifact-registry/ar-webhooks.md
  docs/platform/triggers/trigger-on-a-new-artifact.md
  docs/platform/triggers/triggers-overview.md
  sidebars.ts
Labels: Content - enhancement

#10141 Remove unused images and add support for GCS and Artifactory.
  docs/continuous-integration/secure-ci/secure-connect.md
  docs/continuous-integration/secure-ci/static/secure-connect-arch.png
  docs/continuous-integration/secure-ci/static/secure-connect-arch2.png
  docs/continuous-integration/secure-ci/static/secure-connect-arch3.png
Labels: Content - enhancement

#10118 [PL-Doc] System Release notes 1.86.x
  release-notes/platform.md
Labels: Release notes

#10143 release notes: [IAC-3453]: Add v1.138 release notes
  docs/infra-as-code-management/workspaces/create-workspace.md
  release-notes/infrastructure-as-code-management.md
Labels: Release notes

#10158 Revert PR docs.
  docs/code-repository/pull-requests/merge-pr.md
  docs/code-repository/pull-requests/revert-pr.md
  docs/code-repository/pull-requests/static/pr-revert.png
Labels: Content - enhancement

#10159 Changes per CODE-3241
  docs/code-repository/pull-requests/change-target-branch.md
  docs/code-repository/pull-requests/static/change-target-branch1.png
  docs/code-repository/pull-requests/static/change-target-branch2.png
  docs/code-repository/pull-requests/static/change-target-branch3.png
Labels: Content - enhancement

#10135 CI Release Notes 1.76
  release-notes/continuous-integration.md
Labels: Release notes

#10166 FME release note - Experiment (new feature) [Release date: April 30]
  release-notes/feature-management-experimentation.md
  release-notes/static/fme/experiments-dashboard-configuration.png
  release-notes/static/fme/experiments-dashboard-metric-charts.gif
  release-notes/static/fme/experiments-dashboard-standard-discount.png
  release-notes/static/fme/experiments-dashboard.png
Labels: Release notes
