Repository harness/developer-hub, pull requests merged in 2025-08, with the labels that each got.

#11166 Node20 suport via FF.
  docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step.md
Labels: Content - chore/cleanup

#11130 Runbooks revamp
  docs/ai-sre/ai-agent/ai-agent.md
  docs/ai-sre/runbooks/create-runbook.md
  docs/ai-sre/runbooks/static/action-sequences.png
  docs/ai-sre/runbooks/static/add-action.png
  docs/ai-sre/runbooks/static/configure-parameters.png
  docs/ai-sre/runbooks/static/create-runbook.png
  docs/ai-sre/runbooks/static/custom-alert-type.png
  docs/ai-sre/runbooks/static/custom-incident-type.png
  docs/ai-sre/runbooks/static/test-runbook.png
  docs/ai-sre/runbooks/static/trigger-configuration.png
  docs/ai-sre/runbooks/static/workflow-variables.png
Labels: Content - gap / tech debt

#11220 docs: [IAC-4291]: Update iacm smp support docs
  docs/infra-as-code-management/manage-projects/iacm-smp.md
  docs/infra-as-code-management/whats-supported.md
Labels: Content - gap / tech debt

#10951 docs: [AH-1578]: Add Generic Artifact / CD integration.
  docs/artifact-registry/platform-integrations/cd-ar-integrations.md
Labels: Content - enhancement

#11117 Fix incorrect entry point reference.
  docs/continuous-integration/use-ci/manage-dependencies/background-step-settings.md
Labels: Content - chore/cleanup

#11284 roadmap: [IAC-4340]: IaCM Roadmap update
  src/components/Roadmap/data/iacmData.ts
Labels: Content - enhancement, Content - gap / tech debt

#11037 Add usage guide for AWS OIDC token plugin
  docs/continuous-integration/secure-ci/aws-oidc-token-plugin.md
  docs/continuous-integration/secure-ci/gcp-oidc-token-plugin.md
Labels: Content - enhancement

#11307 Update phrasing to highlight Code Repository access is not tied to CI licenses
  docs/code-repository/get-started/cr-subscription-mgmt.md
Labels: Content - chore/cleanup

#11305 roadmap: [IAC-4371] Update IaCM roadmap
  src/components/Roadmap/data/iacmData.ts
Labels: Content - chore/cleanup

#11310 Add note regarding HTTPS/TLS config.
  docs/continuous-integration/use-ci/run-tests/tests-v2.md
Labels: Content - chore/cleanup

#11357 roadmap: [IAC-4395]: Update roadmap quarters
  src/components/Roadmap/data/iacmData.ts
Labels: Content - chore/cleanup

#11319 Update Codeowner config approver
  .github/CODEOWNERS
Labels: Content - chore/cleanup, Content - gap / tech debt

#11391 1.93 RN + Addition to 1.92 RN
  docs/continuous-integration/secure-ci/secure-connect.md
  release-notes/continuous-integration.md
Labels: Release notes

#11322 docs: [AH-1777]: Update AR what's supported
  docs/artifact-registry/whats-supported.md
Labels: Content - gap / tech debt

#11361 Code 1.54.x release notes
  release-notes/code-repository.md
Labels: Release notes

#11413 Comma separated list support for Canary Deployment
  docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
Labels: Review - SME
